export const USER_COLLECTION = "COL_USERS";
export const CURRENCY_COLLECTION = "COL_CURRENCIES";
export const EXCHANGE_KEYS_COLLECTION = "COL_EXCHANGE_KEYS";
export const MARKET_PRICES_COLLECTION = "COL_MARKET_PRICES";
export const TRANSACTIONS_COLLECTION = "COL_TRANSACTIONS";
export const IPNS_COLLECTION = "COL_IPNS";
export const SUBSCRIPTIONS_COLLECTION = "COL_SUBSCRIPTIONS";
export const STRATEGY_COLLECTION = "COL_STRATS";
export const ORDER_TRACKINGS_COLLECTION = "COL_ORDER_TRACKINGS";
export const TRAINING_COLLECTION = "COL_TRAININGS";
export const TRAINING_ENROLL_COLLECTION = "COL_TRAINING_ENROLLS";
export const TRAINING_FORMAT_COLLECTION = "COL_TRAINING_FORMATS";
export const TRAINING_LANGUAGE_COLLECTION = "COL_TRAINING_LANGUAGES";
export const TRAINING_LEVEL_COLLECTION = "COL_TRAINING_LEVELS";
export const TRAINING_TOPIC_COLLECTION = "COL_TRAINING_TOPICS";
export const PORTFOLIO_EVOLUTION_COLLECTION = "COL_PORTFOLIO_EVOLUTIONS";
// export const SETTINGS = "COL_SETTINGS"; // deprecated
export const SETTINGS_VARS = "COL_SETTINGS_VARS";
export const SETTINGS_PAGES = "COL_SETTINGS_PAGES";
export const SETTINGS_MARKETS = "COL_SETTINGS_MARKETS";
export const COMINGSOON_COLLECTION = "COL_COMINGSOON";
export const COUPONS = "COL_COUPONS";
export const ALGOBOT_COLLECTION = "COL_ALGOBOTS";
export const ALGOBOT_STATS_COLLECTION = "COL_ALGOBOTS_STATS";
export const ALGOBOT_SUBSCRIPTION_COLLECTION = "COL_ALGOBOTS_SUBSCRIPTIONS";
export const ALGOBOT_SUBSCRIPTION_AUDIT_COLLECTION = "COL_ALGOBOTS_SUBSCRIPTIONS_AUDITS";
export const BOT_SEEDORDER_TRACKINGS_COLLECTION = "COL_BOT_SEEDORDER_TRACKINGS";
export const PERFORMANCE_SNAPSHOTS_COLLECTION = "COL_PERFORMANCES_SNAPSHOTS";
export const PERFORMANCE_DATA_WAREHOUSE_COLLECTION = "COL_PERFORMANCES_DATA_WAREHOUSE";
export const PERFORMANCE_CYCLES_COLLECTION = "COL_PERFORMANCES_CYCLES";
export const BOT_SIGNAL_TRACKING_COLLECTION = "COL_BOT_SIGNAL_TRACKING";
export const BOT_SIGNAL_TRACKING_AUDITS_COLLECTION = "COL_BOT_SIGNAL_TRACKING_AUDITS";
export const NOTIFICATIONS_COLLECTION = "COL_NOTIFICATIONS";
export const USERSETTINGS_COLLECTION = "COL_USERSETTINGS";
export const LOGIN_TRACKING_COLLECTION = "COL_LOGIN_TRACKING";

export const DEXMONITORING_COLLECTION = "COL_DEXMONITORING";
export const DEXASSETS_COLLECTION = "DEXASSETS_COLLECTION";

// PERFEES RELATED COLLECTIONS
export const PERFEES_SETTINGS_COLLECTION = "COL_PERFEES_SETTINGS";
export const PERFEES_LOGS_COLLECTION = "COL_PERFEES_LOGS";

export const PERFEES_USERS_WALLETS_COLLECTION = "COL_PERFEES_USERS_WALLETS";
export const PERFEES_USERS_WALLETS_TRACKINGS_COLLECTION = "COL_PERFEES_USERS_WALLETS_TRACKINGS";
export const PERFEES_USERS_TRANSACTIONS_COLLECTION = "COL_PERFEES_USERS_TRANSACTIONS";

export const PERFEES_BOTS_WALLETS_COLLECTION = "COL_PERFEES_BOTS_WALLETS";

export const PERFEES_FEES_WALLETS_COLLECTION = "COL_PERFEES_FEES_WALLETS";
export const PERFEES_FEES_TRACKINGS_COLLECTION = "COL_PERFEES_FEES_TRACKINGS";
export const PERFEES_FEES_TRANSACTIONS_COLLECTION = "COL_PERFEES_FEES_TRANSACTIONS";

export const PERFEES_USERS_REFERRALS_COLLECTION = "COL_PERFEES_USERS_REFERRALS";
export const PERFEES_REFERRALS_TRANSACTIONS_COLLECTION = "COL_PERFEES_REFERRALS_TRANSACTIONS";
export const PERFEES_REFERRALS_TRACKINGS_COLLECTION = "COL_PERFEES_REFERRALS_TRACKINGS";

// STAKING RELATED COLLECTIONS
export const STAKING_USERS_WALLETS_COLLECTION = "COL_STAKING_USERS_WALLETS";
export const STAKING_USER_TRANSACTION_COLLECTION = "COL_STAKING_USER_TRANSACTIONS";

// ACTIVE CAMPAIGN AUTOMATION COLLECTIONS
export const ACTIVE_CAMPAIGN_COLLECTION = "COL_ACTIVE_CAMPAIGN_AUTOMATION";
export const EMAIL_MARKETING_AUTOMATION_COLLECTION = "COL_EMAIL_MARKETING_AUTOMATION";

// STAKING MULTI-LEVEL
export const STAKING_LEVEL_COLLECTION = "COL_STAKING_LEVEL";

// INDACOIN COLLECTION
export const INDACOIN_TRANSACTIONS_COLLECTION = "COL_INDACOIN_TRANSACTIONS";

// INDACOIN COLLECTION
export const CRYPTOCOMPARE_COLLECTION = "COL_CRYPTOCOMPARE";

// COPY TRADING COLLECTIONS
export const COPYTRADING_TRADERS_COLLECTION = "COL_COPYTRADING_TRADERS";

// BROKER TRADING COLLECTIONS
export const BROKERTRADING_OWNERS_COLLECTION = "COL_BROKERTRADING_OWNERS";
export const BROKERTRADING_TRADERS_COLLECTION = "COL_BROKERTRADING_TRADERS";
