export const DEPOSIT_TRANSACTION = process.env.KAFKA_TOPIC_NAME_DEPOSIT_TX;
export const DEPOSIT_TRANSACTION_CONFIRM = process.env.KAFKA_TOPIC_NAME_DEPOSIT_TX_CONFIRM;
export const DEPOSIT_TRANSACTION_REMOVE = process.env.KAFKA_TOPIC_NAME_DEPOSIT_TX_REMOVE;
