import { Types } from "mongoose";
import { AlgoBotSubscriptionModel } from "../../algobot/models/algobot-subscription.model";
import { AlgoBotModel } from "../../algobot/models/algobot.model";

export const algobotSeedData = [
  {
    name: "Optimus V2 BTC",
    botRef: "OPTIMUSBTC", // seed identifier
    botVer: "2",
    description:
      "Optimus BTC is an algorithm based on success rate optimization. It is particularly effective in a volatile market based on multiple variables and safeties.",
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BTC", quote: "USDT" },
    creator: "4C-Trading",
    avgtrades: 9,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0xE11DCFB83BEbDE864a930128558eF28fd76d7446",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Optimus V2 ETH",
    botRef: "OPTIMUSETH", // seed identifier
    botVer: "2",
    description:
      "Optimus ETH is an algorithm based on success rate optimization. It is particularly effective in a volatile market based on multiple variables and safeties.",
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ETH", quote: "USDT" },
    creator: "4C-Trading",
    avgtrades: 7,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0xE11DCFB83BEbDE864a930128558eF28fd76d7446",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Optimus V2 BNB",
    botRef: "OPTIMUSBNB", // seed identifier
    botVer: "2",
    description:
      "Optimus BNB is an algorithm based on success rate optimization. It is particularly effective in a volatile market based on multiple variables and safeties.",
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BNB", quote: "USDT" },
    creator: "4C-Trading",
    avgtrades: 15,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0xE11DCFB83BEbDE864a930128558eF28fd76d7446",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Community Bot AVAX",
    botRef: "AVAXUSDT1", // seed identifier
    botVer: "2",
    description:
      "AVAX Trend follower is an algorithm that is not intended to trade at high frequency but rather to try to capture a trend as long as possible. It works on the basis of the price structure by integrating a volatility component and is a viable option for the AVAX holder, securing their capital while trying to get the maximum out of a pump.",
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "AVAX", quote: "USDT" },
    creator: "4C-Trading",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 0,
      address: "",
      distribution: { developer: 0, burn: 0, pool: 0, reserve: 0 },
    },
    exchangesType: ["Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Sonny BTC",
    botRef: "IROBOTBTC", // seed identifier
    botVer: "1",
    description:
      "I-Robot is multiple indicator strategy developed using technical indicators blended with machine learning to catch trends early and stay longest time possible.",
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BTC", quote: "USDT" },
    creator: "I-Robot",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x186D3F21fF43FD964c6142E228c10771CE3c5211",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Sonny ETH",
    botRef: "IROBOTETH", // seed identifier
    botVer: "1",
    description:
      "I-Robot is multiple indicator strategy developed using technical indicators blended with machine learning to catch trends early and stay longest time possible.",
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ETH", quote: "USDT" },
    creator: "I-Robot",
    avgtrades: 2,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x186D3F21fF43FD964c6142E228c10771CE3c5211",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Sonny BNB",
    botRef: "IROBOTBNB", // seed identifier
    botVer: "1",
    description:
      "I-Robot is multiple indicator strategy developed using technical indicators blended with machine learning to catch trends early and stay longest time possible.",
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BNB", quote: "USDT" },
    creator: "I-Robot",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x186D3F21fF43FD964c6142E228c10771CE3c5211",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Community bot TOMO LO1",
    botRef: "TOMOLO1", // seed identifier
    botVer: "1",
    description:
      "The TOMO Long only uses a moving average filter to enter only setups with the highest probability of success. It then uses an indicator well known to the Tradingview community as a trigger, the WaveTrend.",
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "TOMO", quote: "USDT" },
    creator: "4c-trading",
    avgtrades: 3,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 0,
      address: "",
      distribution: { developer: 0, burn: 0, pool: 0, reserve: 0 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "FRaMAV2 ETH",
    botRef: "FRAMAV2ETH", // seed identifier
    botVer: "1",
    description: `The FRaMAV2 strategy takes advantage of a volatility analysis in order to eliminate as much "noise" as possible. It is also based on buying and selling pressure in order to avoid positioning against the underlying trend.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ETH", quote: "USDT" },
    creator: "Gravity Trading",
    avgtrades: 20,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 18,
      address: "0xE11DCFB83BEbDE864a930128558eF28fd76d7446",
      distribution: { developer: 5.75, burn: 2.875, pool: 2.875, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Gravity DUSK",
    botRef: "GRAVITYDUSK", // seed identifier
    botVer: "1",
    description: `The Gravity strategy takes advantage of a volatility analysis in order to eliminate as much "noise" as possible. It is also based on buying and selling pressure in order to avoid positioning against the underlying trend.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "DUSK", quote: "USDT" },
    creator: "Gravity Trading",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 18,
      address: "0xE11DCFB83BEbDE864a930128558eF28fd76d7446",
      distribution: { developer: 5.75, burn: 2.875, pool: 2.875, reserve: 6.5 },
    },
    exchangesType: ["Binance", "KuCoin"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Gravity NULS",
    botRef: "GRAVITYNULS", // seed identifier
    botVer: "1",
    description: `The Gravity strategy takes advantage of a volatility analysis in order to eliminate as much "noise" as possible. It is also based on buying and selling pressure in order to avoid positioning against the underlying trend.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "NULS", quote: "USDT" },
    creator: "Gravity Trading",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 18,
      address: "0xE11DCFB83BEbDE864a930128558eF28fd76d7446",
      distribution: { developer: 5.75, burn: 2.875, pool: 2.875, reserve: 6.5 },
    },
    exchangesType: ["Binance", "KuCoin"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "ETH Infinity",
    botRef: "ETHINFINITY", // seed identifier
    botVer: "1",
    description: `Indicator optimization on a 15min timeframe, INFINITY ETH trades the trends in a filtered way to try to beat the market and get the maximum profit.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ETH", quote: "USDT" },
    creator: "XpR",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0x7D4Bf7054F5cfD1f15c4E7D680656f0faF840898",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "SuperTrader ETH",
    botRef: "SUPERTRADERETH", // seed identifier
    botVer: "1",
    description: `SuperTrader is a long and short trend following algorithm, based on volume and filters, preventing it from overtrade.`,
    stratType: "LONG_SHORT",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ETH", quote: "USDT" },
    creator: "XpR",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x7D4Bf7054F5cfD1f15c4E7D680656f0faF840898",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro", "KuCoin-future", "Binance-future", "Ftx-future"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "SuperTrader LINK",
    botRef: "SUPERTRADERLINK", // seed identifier
    botVer: "1",
    description: `SuperTrader is a long and short trend following algorithm, based on volume and filters, preventing it from overtrade.`,
    stratType: "LONG_SHORT",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "LINK", quote: "USDT" },
    creator: "XpR",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x7D4Bf7054F5cfD1f15c4E7D680656f0faF840898",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "KuCoin-future", "Coinbasepro", "Binance-future", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "SuperTrader BNB",
    botRef: "SUPERTRADERBNB", // seed identifier
    botVer: "1",
    description: `SuperTrader is a long and short trend following algorithm, based on volume and filters, preventing it from overtrade.`,
    stratType: "LONG_SHORT",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BNB", quote: "USDT" },
    creator: "XpR",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x7D4Bf7054F5cfD1f15c4E7D680656f0faF840898",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "KuCoin-future", "Binance-future", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Spooner BTC",
    botRef: "SPOONERBTC", // seed identifier
    botVer: "1",
    description: `Spooner is an aggressive algo strategy developed by I-Robot. It uses technical indicators blended with machine learning to catch trends early, and stay in for the longest time possible.  It will have more trades per month than I-Robot's Sonny algos. I-Robot recommends having both Spooner & Sonny strategies enabled for best results.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BTC", quote: "USDT" },
    creator: "I-Robot",
    avgtrades: 7,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x186D3F21fF43FD964c6142E228c10771CE3c5211",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Spooner ETH",
    botRef: "SPOONERETH", // seed identifier
    botVer: "1",
    description: `Spooner is an aggressive algo strategy developed by I-Robot. It uses technical indicators blended with machine learning to catch trends early, and stay in for the longest time possible.  It will have more trades per month than I-Robot's Sonny algos. I-Robot recommends having both Spooner & Sonny strategies enabled for best results.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ETH", quote: "USDT" },
    creator: "I-Robot",
    avgtrades: 7,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x186D3F21fF43FD964c6142E228c10771CE3c5211",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Spooner LINK",
    botRef: "SPOONERLINK", // seed identifier
    botVer: "1",
    description: `Spooner is an aggressive algo strategy developed by I-Robot. It uses technical indicators blended with machine learning to catch trends early, and stay in for the longest time possible.  It will have more trades per month than I-Robot's Sonny algos. I-Robot recommends having both Spooner & Sonny strategies enabled for best results.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "LINK", quote: "USDT" },
    creator: "I-Robot",
    avgtrades: 7,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x186D3F21fF43FD964c6142E228c10771CE3c5211",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Spooner FTT",
    botRef: "SPOONERFTT", // seed identifier
    botVer: "1",
    description: `Spooner is an aggressive algo strategy developed by I-Robot. It uses technical indicators blended with machine learning to catch trends early, and stay in for the longest time possible.  It will have more trades per month than I-Robot's Sonny algos. I-Robot recommends having both Spooner & Sonny strategies enabled for best results.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "FTT", quote: "USDT" },
    creator: "I-Robot",
    avgtrades: 9,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x186D3F21fF43FD964c6142E228c10771CE3c5211",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Swing Sniper: BTCUSDT",
    botRef: "PGBTC", // seed identifier
    botVer: "1",
    description: `This strategy uses volatility based technical indicators and trend confirmation analysis to find reliable entry and exit points. The Swing Sniper for BTC provides the best of both worlds between swing and day trading allowing you to buy the dip and sell as the momentum rolls over.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BTC", quote: "USDT" },
    creator: "Pure Gold Crypto Signals",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0x57E0284B8cf06106462a890Cb4fBadd164B1f1D5",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Swing Sniper: ETHUSDT",
    botRef: "PGETH", // seed identifier
    botVer: "1",
    description: `This strategy uses volatility based technical indicators and trend confirmation analysis to find reliable entry and exit points. The Swing Sniper for ETH provides the best of both worlds between swing and day trading allowing you to buy the dip and sell as the momentum rolls over.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ETH", quote: "USDT" },
    creator: "Pure Gold Crypto Signals",
    avgtrades: 2,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 16.5,
      address: "0x57E0284B8cf06106462a890Cb4fBadd164B1f1D5",
      distribution: { developer: 5, burn: 2.5, pool: 2.5, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Swing Sniper: BNBUSDT",
    botRef: "PGBNB", // seed identifier
    botVer: "1",
    description: `This strategy uses volatility based technical indicators and trend confirmation analysis to find reliable entry and exit points. The Swing Sniper for BNB provides the best of both worlds between swing and day trading allowing you to buy the dip and sell as the momentum rolls over.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BNB", quote: "USDT" },
    creator: "Pure Gold Crypto Signals",
    avgtrades: 2,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 16.5,
      address: "0x57E0284B8cf06106462a890Cb4fBadd164B1f1D5",
      distribution: { developer: 5, burn: 2.5, pool: 2.5, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Swing Sniper: TRXUSDT",
    botRef: "PGTRX", // seed identifier
    botVer: "1",
    description: `This strategy uses volatility based technical indicators and trend confirmation analysis to find reliable entry and exit points. The Swing Sniper for TRX provides the best of both worlds between swing and day trading allowing you to buy the dip and sell as the momentum rolls over.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "TRX", quote: "USDT" },
    creator: "Pure Gold Crypto Signals",
    avgtrades: 2,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20.0,
      address: "0x57E0284B8cf06106462a890Cb4fBadd164B1f1D5",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi"],
    priceDecimal: 4,
  } as AlgoBotModel,
  {
    name: "Gold Rush: BATUSDT",
    botRef: "PGBAT", // seed identifier
    botVer: "1",
    description: `Using several modified technical indicators on faster timeframes, the Gold Rush strategy allows you to take advantage of intraday volatility while following the broader trend.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BAT", quote: "USDT" },
    creator: "Pure Gold Crypto Signals",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x57E0284B8cf06106462a890Cb4fBadd164B1f1D5",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Gold Rush: MATICUSDT",
    botRef: "PGMATIC", // seed identifier
    botVer: "1",
    description: `Using several modified technical indicators on faster timeframes, the Gold Rush strategy allows you to take advantage of intraday volatility while following the broader trend.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "MATIC", quote: "USDT" },
    creator: "Pure Gold Crypto Signals",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0x57E0284B8cf06106462a890Cb4fBadd164B1f1D5",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Wow much profit: DOGEUSDT",
    botRef: "PGDOGE", // seed identifier
    botVer: "1",
    description: `By monitoring the intraday spikes and filtering them using longer term trends and strength indicators, we can capitalise on the inherant volatility of DOGE. Taking small profits regularly, the idea is to get in and out quickly. This algo is a very good boy.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "DOGE", quote: "USDT" },
    creator: "Pure Gold Crypto Signals",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 16.5,
      address: "0x57E0284B8cf06106462a890Cb4fBadd164B1f1D5",
      distribution: { developer: 5, burn: 2.5, pool: 2.5, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "WT ETH",
    botRef: "WTETH", // seed identifier
    botVer: "1",
    description: `Wave Trader is a trend bot that has built in safe scalping. The strategies have been tuned across many coins and exchanges. All strategies are walk forward tested with minimal drawdown as a priority.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ETH", quote: "USDT" },
    creator: "Wave Trader",
    avgtrades: 2,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20.5,
      address: "0x81e1b56039f35F19f17d3C5dC9a3EDC6Ca1D6F4A",
      distribution: { developer: 7, burn: 3.875, pool: 3.875, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "WT BNB",
    botRef: "WTBNB", // seed identifier
    botVer: "1",
    description: `Wave Trader is a trend bot that has built in safe scalping. The strategies have been tuned across many coins and exchanges. All strategies are walk forward tested with minimal drawdown as a priority.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BNB", quote: "USDT" },
    creator: "Wave Trader",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20.5,
      address: "0x81e1b56039f35F19f17d3C5dC9a3EDC6Ca1D6F4A",
      distribution: { developer: 7, burn: 3.875, pool: 3.875, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "WT ETC",
    botRef: "WTETC", // seed identifier
    botVer: "1",
    description: `Wave Trader is a trend bot that has built in safe scalping. The strategies have been tuned across many coins and exchanges. All strategies are walk forward tested with minimal drawdown as a priority.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ETC", quote: "USDT" },
    creator: "Wave Trader",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20.5,
      address: "0x81e1b56039f35F19f17d3C5dC9a3EDC6Ca1D6F4A",
      distribution: { developer: 7, burn: 3.875, pool: 3.875, reserve: 6.5 },
    },
    exchangesType: ["Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "WT SOL",
    botRef: "WTSOL", // seed identifier
    botVer: "1",
    description: `Wave Trader is a trend bot that has built in safe scalping. The strategies have been tuned across many coins and exchanges. All strategies are walk forward tested with minimal drawdown as a priority.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "SOL", quote: "USDT" },
    creator: "Wave Trader",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20.5,
      address: "0x81e1b56039f35F19f17d3C5dC9a3EDC6Ca1D6F4A",
      distribution: { developer: 7, burn: 3.875, pool: 3.875, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "WT CAKE",
    botRef: "WTCAKE", // seed identifier
    botVer: "1",
    description: `Wave Trader is a trend bot that has built in safe scalping. The strategies have been tuned across many coins and exchanges. All strategies are walk forward tested with minimal drawdown as a priority.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "CAKE", quote: "USDT" },
    creator: "Wave Trader",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20.5,
      address: "0x81e1b56039f35F19f17d3C5dC9a3EDC6Ca1D6F4A",
      distribution: { developer: 7, burn: 3.875, pool: 3.875, reserve: 6.5 },
    },
    exchangesType: ["Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "WT SHIB",
    botRef: "WTSHIB", // seed identifier
    botVer: "1",
    description: `Wave Trader is a trend bot that has built in safe scalping. The strategies have been tuned across many coins and exchanges. All strategies are walk forward tested with minimal drawdown as a priority.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "SHIB", quote: "USDT" },
    creator: "Wave Trader",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20.5,
      address: "0x81e1b56039f35F19f17d3C5dC9a3EDC6Ca1D6F4A",
      distribution: { developer: 7, burn: 3.875, pool: 3.875, reserve: 6.5 },
    },
    exchangesType: ["Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "INERTIALGO SWING FTT",
    botRef: "NLSFTT", // seed identifier
    botVer: "1",
    description: `Inertialgo is a swing strategy , based on momentum divergences. Order are placed for Long position when a bullish momentum is detected. The position will be closed when a bearish momentum will be detected.
    It's a long term strategy, with swing positions.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "FTT", quote: "USDT" },
    creator: "INERTIALGO",
    avgtrades: 2,
    allocated: { maxamount: 50000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 25,
      address: "0x976a7CBA73bFAb52B3b29Df58CfA8019C173EFF4",
      distribution: { developer: 9.25, burn: 4.625, pool: 4.625, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Surge Bot SXP",
    botRef: "SURGEBOTSXP", // seed identifier
    botVer: "1",
    description: `Surge Bot SXP is a multi-piece algorithm that is melded together to provide a strategy that combines volume, moving averages and momentum. Short and Long trades are executed based on trend on an hourly duration.`,
    stratType: "LONG_SHORT",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "SXP", quote: "USDT" },
    creator: "Kerokero",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 18,
      address: "0x552718b400EC6A3078124B53c581468af4bA176D",
      distribution: { developer: 5.75, burn: 2.875, pool: 2.875, reserve: 6.5 },
    },
    exchangesType: ["Binance", "Binance-future", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Fluctus BTC",
    botRef: "FLUCTUSBTC", // seed identifier
    botVer: "1",
    description: `Fluctus BTC is a trend trading bot. This algorithm is thoroughly tested and is optimized to reduce steep corrections. This implies that it is more conservative and waits to enter until a clear trend is identified and gets out when the movement evidently terminates, slowly climbing up. It won't buy the bottom and sell the top but is optimized for slow and steady returns.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BTC", quote: "USDT" },
    creator: "Fluctus Technology",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 16.5,
      address: "0x958673B7D849063A05F24C22d4eFbADDEAa7b053",
      distribution: { developer: 5, burn: 2.5, pool: 2.5, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro", "KuCoin-future", "Binance-future"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Harsi",
    botRef: "HARSIBTC", // seed identifier
    botVer: "1",
    description: `This script combines Heikin-ashi with volume weighted moving avarage to give multiple entries (all filtered using RSI , ADX and MFI).`,
    stratType: "LONG_SHORT",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BTC", quote: "USDT" },
    creator: "Olmo",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 16,
      address: "0x3C7976992b014B7DbA9FaCE3e5eb4d9392b66394",
      distribution: { developer: 4.75, burn: 2.375, pool: 2.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "Coinbasepro", "KuCoin-future", "Binance-future"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "ATAMA",
    botRef: "ATAMABTS", // seed identifier
    botVer: "1",
    description: `ATAMA bot.`,
    stratType: "LONG",
    category: "algobot",
    enabled: false,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BTS", quote: "USDT" },
    creator: "",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 16,
      address: "",
      distribution: { developer: 4.75, burn: 2.375, pool: 2.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi", "KuCoin-future", "Binance-future"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Smart ADA",
    botRef: "LAIKAADA", // seed identifier
    botVer: "1",
    description: `This algorithm is developed by LAIKA, and has the ability to find continuing trends while mitigating declines. The algorithm has been thoroughly tested and optimised in various type of markets, making it ready for anything. It trades between ADA and USD when necessary, in order to avoid extreme volatility and steep declines.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ADA", quote: "USDT" },
    creator: "LAIKA",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0x2Bb10591aDA9048Db72Bb37cf8e7962A726D64b2",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Smart AVAX",
    botRef: "LAIKAAVAX", // seed identifier
    botVer: "1",
    description: `This algorithm is developed by LAIKA, and has the ability to find continuing trends while mitigating declines. The algorithm has been thoroughly tested and optimised in various type of markets, making it ready for anything. It trades between AVAX and USD when necessary, in order to avoid extreme volatility and steep declines.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "AVAX", quote: "USDT" },
    creator: "LAIKA",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0x2Bb10591aDA9048Db72Bb37cf8e7962A726D64b2",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["Binance", "KuCoin", "Huobi", "Coinbasepro"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Smart ATOM",
    botRef: "LAIKAATOM", // seed identifier
    botVer: "1",
    description: `This algorithm is developed by LAIKA, and has the ability to find continuing trends while mitigating declines. The algorithm has been thoroughly tested and optimised in various type of markets, making it ready for anything. It trades between ATOM and USDT when necessary, in order to avoid extreme volatility and steep declines.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "ATOM", quote: "USDT" },
    creator: "LAIKA",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0x2Bb10591aDA9048Db72Bb37cf8e7962A726D64b2",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Smart NEAR",
    botRef: "LAIKANEAR", // seed identifier
    botVer: "1",
    description: `This algorithm is developed by LAIKA, and has the ability to find continuing trends while mitigating declines. The algorithm has been thoroughly tested and optimised in various type of markets, making it ready for anything. It trades between NEAR and USDT when necessary, in order to avoid extreme volatility and steep declines.`,
    stratType: "LONG",
    category: "algobot",
    enabled: true,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "NEAR", quote: "USDT" },
    creator: "LAIKA",
    avgtrades: 12,
    allocated: { maxamount: 100000, currency: "USDT" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 20,
      address: "0x2Bb10591aDA9048Db72Bb37cf8e7962A726D64b2",
      distribution: { developer: 6.75, burn: 3.375, pool: 3.375, reserve: 6.5 },
    },
    exchangesType: ["FTX", "Binance", "KuCoin", "Huobi"],
    priceDecimal: 2,
  } as AlgoBotModel,
  {
    name: "Optimus BTC FTX (local old)",
    botRef: "OPTIMUSBTC_FTX", // seed identifier
    botVer: "1",
    description:
      "Optimus BTC is an algorithm based on success rate optimization. It is particularly effective in a volatile market based on multiple variables and safeties.",
    stratType: "LONG",
    category: "algobot",
    enabled: false,
    owner: new Types.ObjectId("5ffffcfdb44fdb4239f369c9"),
    market: { base: "BTC", quote: "USD" },
    creator: "4C-Trading",
    avgtrades: 9,
    allocated: { maxamount: 50000, currency: "USD" },
    ratings: 4.2,
    reviews: { username: "Elena", userimg: "/img/bots-card/user-img.png", botrating: 5.0 },
    perfFees: {
      percent: 0,
      address: "",
      distribution: { developer: 0, burn: 0, pool: 0, reserve: 0 },
    },
  } as AlgoBotModel,
];

export const algbotFollowers = [
  {
    id: new Types.ObjectId("5f7adf2351729c07b0df0afc"), // needs an id for seed identification
    userId: "5ef31aef22ebd022d3b01b7d", // local test user
    botId: new Types.ObjectId("5f74fa57010ce73f3dbd73da"),
    apiKeyRef: "5f57c3bdc6e49d114aac27ee", // local bitmex_test account
    enabled: false,
    isOwner: false,
    botRunning: false,
    stratType: "LONG",
    cycleSequence: 1,
    status: 4,
    accountPercent: 0.19,
  } as AlgoBotSubscriptionModel,
];
