export const exchangesList = [
  { id: "uniswap", label: "Uniswap" },
  { id: "oasis", label: "Oasis" },
  { id: "zero_x", label: "Ox V3" },
  { id: "kyber", label: "Kyber" },
  { id: "bancor", label: "Bancor" },
  { id: "synthetix", label: "Synthetix" },
  { id: "balancer", label: "Balancer" },
  { id: "curve", label: "Curve" },
  { id: "curve_susd", label: "Curve SUSD" },
  { id: "curve_btc", label: "Curve BTC" },
  { id: "chai", label: "Chai" },
  { id: "coumpound", label: "Coumpound" },
  { id: "aave", label: "Aave" },
  { id: "mstable", label: "mStable" },
  { id: "uniswap_v2", label: "Uniswap V2" },
  { id: "zero_x_v2", label: "0x V2" },
  { id: "sushiswap", label: "Sushiswap" },
  { id: "swerve", label: "Swerve" },
];

export const coinsList = [
  { id: "ETH", label: "ETH" },
  { id: "ZRX", label: "0x" },
  { id: "0XBTC", label: "0xBitcoin" },
  { id: "AAVE", label: "Aave" },
  { id: "ABAT", label: "aBat" },
  { id: "ABUSD", label: "aBUSD" },
  { id: "ABYSS", label: "Abyss Token" },
  { id: "ADAI", label: "aDAI" },
  { id: "ELF", label: "Aelf" },
  { id: "AETH", label: "aETH" },
  { id: "AKNC", label: "aKNC" },
  { id: "AKRO", label: "Akropolis" },
  { id: "ALEND", label: "aLEND" },
  { id: "aLINK", label: "aLINK" },
  { id: "AMANA", label: "aMANA" },
  { id: "AMKR", label: "aMKR" },
  { id: "AMN", label: "Amon" },
  { id: "AMPL", label: "AMPL" },
  { id: "ANT", label: "Aragon Ne...k Token" },
  { id: "ABT", label: "ArcBlock" },
  { id: "AREP", label: "aREP" },
  { id: "ASNX", label: "aSNX" },
  { id: "ASUSD", label: "aSUSD" },
  { id: "ATUSD", label: "aTUSD" },
  { id: "AUC", label: "Auctus" },
  { id: "REP", label: "Augur V1" },
  { id: "REPV2", label: "Augur V2" },
  { id: "AUSDC", label: "aUSDC" },
  { id: "AUSDT", label: "aUSDT" },
  { id: "AWBTC", label: "aWBTC" },
  { id: "AZRX", label: "aZRX" },
  { id: "BAL", label: "Balancer" },
  { id: "BNT", label: "Bancor" },
  { id: "BAND", label: "Band Token" },
  { id: "$BASED", label: "Based" },
  { id: "BAT", label: "Basic Att...n Token" },
  { id: "BEE", label: "Bee Token" },
  { id: "BLT", label: "Bloom" },
  { id: "CDT", label: "Blox" },
  { id: "BLZ", label: "Bluezelle" },
  { id: "BNTY", label: "Bounty0x" },
  { id: "BTU", label: "BTU Protocol" },
  { id: "BZRX", label: "bZx Protocol Token" },
  { id: "CBAT", label: "cBAT" },
  { id: "CDAI", label: "cDAI" },
  { id: "CETH", label: "cETH" },
  { id: "CHAI", label: "Chai" },
  { id: "LINK", label: "Chainlink" },
  { id: "CND", label: "Cindicator" },
  { id: "CVC", label: "Civic" },
  { id: "CBI", label: "Coin Bank...ational" },
  { id: "COMP", label: "Compound Token" },
  { id: "CREAM", label: "Cream" },
  { id: "CREP", label: "cRep" },
  { id: "MCO", label: "Crypto.com" },
  { id: "C20", label: "Crypto20" },
  { id: "XCHF", label: "CryptyoFranc" },
  { id: "CRV", label: "Curve DAO Token" },
  { id: "CUSDC", label: "cUSDC" },
  { id: "CWBTC", label: "cWBTC" },
  { id: "CZRX", label: "cZRX" },
  { id: "DAI", label: "DAI" },
  { id: "GEN", label: "DAOstack" },
  { id: "RING", label: "Darwinia...k Token" },
  { id: "DAT", label: "Datum" },
  { id: "MANA", label: "Decentraland" },
  { id: "DIP", label: "Decentral...surance" },
  { id: "DPI", label: "DefiPulse Index" },
  { id: "DGD", label: "DigixDAO" },
  { id: "DNT", label: "district0x" },
  { id: "DODO", label: "Dodo" },
  { id: "DXD", label: "DXDao" },
  { id: "EKO", label: "EchoLink" },
  { id: "EDO", label: "Eidoo" },
  { id: "ENJ", label: "Enjin" },
  { id: "LEND", label: "ETH Lend" },
  { id: "FARM", label: "FARM Reward Token" },
  { id: "FTX", label: "FintruX Network" },
  { id: "FOAM", label: "FOAM" },
  { id: "FRONT", label: "Frontier Token" },
  { id: "FND", label: "FundRequest" },
  { id: "FUN", label: "FunFair" },
  { id: "FUSE", label: "Fuse Network Token" },
  { id: "GNO", label: "Gnosis" },
  { id: "GLM", label: "Golem Netork Token" },
  { id: "GRID", label: "Grid+" },
  { id: "HOT", label: "Holo" },
  { id: "RLC", label: "iExec RLC" },
  { id: "ISLA", label: "Insula" },
  { id: "IOTX", label: "IoTeX" },
  { id: "JRT", label: "Jarvis Reward Token" },
  { id: "KEEP", label: "Keep" },
  { id: "KNC", label: "Kyber Network" },
  { id: "LCX", label: "LCX" },
  { id: "LQD", label: "Liquidity.Network" },
  { id: "LPT", label: "Live Peer" },
  { id: "LOOM", label: "Loom Network" },
  { id: "LRC", label: "Loopring" },
  { id: "MGN", label: "Magnolia Token" },
  { id: "MKR", label: "Maker" },
  { id: "MATIC", label: "Matic Token" },
  { id: "MCB", label: "MCDEX Token" },
  { id: "MLN", label: "Melon" },
  { id: "MTA", label: "mStable Meta" },
  { id: "MUSD", label: "mStable USD" },
  { id: "NEC", label: "Nectar" },
  { id: "NEST", label: "Nest" },
  { id: "NEXO", label: "Nexo" },
  { id: "NMR", label: "Numeraire" },
  { id: "OMG", label: "OmiseGO" },
  { id: "PAN", label: "Panvala Token" },
  { id: "PAX", label: "Pax" },
  { id: "BTC++", label: "PieDAO BTC++" },
  { id: "PLR", label: "Pillar" },
  { id: "PNK", label: "Pinakion" },
  { id: "PNT", label: "pNetwork Token" },
  { id: "POA20", label: "POE ERC20" },
  { id: "POLY", label: "Polymath" },
  { id: "POWR", label: "Power Ledger" },
  { id: "PBTC", label: "pTokens BTC" },
  { id: "NPXS", label: "Pundi X" },
  { id: "QASH", label: "QASH" },
  { id: "QKC", label: "QuarkChain" },
  { id: "RAE", label: "RAE Token" },
  { id: "RDN", label: "Raiden Ne...k Token" },
  { id: "RDAI", label: "rDAI" },
  { id: "REN", label: "Ren" },
  { id: "RENBTC", label: "renBTC" },
  { id: "RSR", label: "Reserve Rights" },
  { id: "RHOC", label: "RHOC" },
  { id: "RCN", label: "Ripio" },
  { id: "RPL", label: "Rocket Pool" },
  { id: "IDRT", label: "Rupiah Token" },
  { id: "SALT", label: "Salt" },
  { id: "SAN", label: "Santiment...k Token" },
  { id: "SELF", label: "Self Token" },
  { id: "SHUF", label: "SHUF Token" },
  { id: "AGI", label: "SingularityNET" },
  { id: "SRN", label: "Sirin Labs Token" },
  { id: "SPANK", label: "SpankChain" },
  { id: "SNT", label: "Status" },
  { id: "STORJ", label: "Storj" },
  { id: "DATA", label: "Stramr" },
  { id: "SUSHI", label: "Sushi" },
  { id: "SWRV", label: "Swerve DAO Token" },
  { id: "IADA", label: "Synthetix iADA" },
  { id: "IBCH", label: "Synthetix iBCH" },
  { id: "IBNB", label: "Synthetix iBNB" },
  { id: "IBTC", label: "Synthetix iBTC" },
  { id: "ICEX", label: "Synthetix iCEX" },
  { id: "IDASH", label: "Synthetix iDASH" },
  { id: "IDEFI", label: "Synthetix iDEFI" },
  { id: "IEOS", label: "Synthetix iEOS" },
  { id: "IETC", label: "Synthetix iETC" },
  { id: "IETH", label: "Synthetix iETH" },
  { id: "ILINK", label: "Synthetix iLINK" },
  { id: "ILTC", label: "Synthetix iLTC" },
  { id: "ITRX", label: "Synthetix iTRX" },
  { id: "IXMR", label: "Synthetix iXMR" },
  { id: "IXRP", label: "Synthetix iXRP" },
  { id: "IXTZ", label: "Synthetix iXTZ" },
  { id: "SNX", label: "Synthetix...k Token" },
  { id: "SADA", label: "Synthetix sADA" },
  { id: "SAUD", label: "Synthetix sAUD" },
  { id: "SBCH", label: "Synthetix sBCH" },
  { id: "SBNB", label: "Synthetix sBNB" },
  { id: "SBTC", label: "Synthetix sBTC" },
  { id: "SCEX", label: "Synthetix sCEX" },
  { id: "SCHF", label: "Synthetix sCHF" },
  { id: "SDASH", label: "Synthetix sDASH" },
  { id: "SDEFI", label: "Synthetix sDEFI" },
  { id: "SEOS", label: "Synthetix sEOS" },
  { id: "SETC", label: "Synthetix sETC" },
  { id: "SETH", label: "Synthetix sETH" },
  { id: "SEUR", label: "Synthetix sEUR" },
  { id: "SFTSE", label: "Synthetix sFTSE" },
  { id: "SGBP", label: "Synthetix sGBP" },
  { id: "SJPY", label: "Synthetix sJPY" },
  { id: "SLINK", label: "Synthetix sLINK" },
  { id: "SLTC", label: "Synthetix sLTC" },
  { id: "SNIKKEI", label: "Synthetix sNIKKEI" },
  { id: "STRX", label: "Synthetix sTRX" },
  { id: "SUSD", label: "Synthetix sUSD" },
  { id: "SXAG", label: "Synthetix sXAG" },
  { id: "SXAU", label: "Synthetix sXAU" },
  { id: "SXMR", label: "Synthetix sXMR" },
  { id: "SXRP", label: "Synthetix sXRP" },
  { id: "SXTZ", label: "Synthetix sXTZ" },
  { id: "TBTC", label: "tBTC" },
  { id: "TKN", label: "TokenCard" },
  { id: "TAUD", label: "TrueAUD" },
  { id: "TGBP", label: "TrueGBP" },
  { id: "THKD", label: "TrueHKD" },
  { id: "TUSD", label: "TrueUSD" },
  { id: "TRST", label: "TrustCoin" },
  { id: "TLN", label: "Trustline...k Token" },
  { id: "ULT", label: "Unblocked Ledger" },
  { id: "UBT", label: "Unibright" },
  { id: "UFT", label: "UniLend" },
  { id: "UNDT", label: "Union Network" },
  { id: "UNI", label: "Uniswap" },
  { id: "UBXT", label: "UpBots (UBXT)" },
  { id: "USDC", label: "USD Coin" },
  { id: "USDT", label: "USDT" },
  { id: "GOO", label: "Vials of Goo" },
  { id: "WTC", label: "WaltonChain" },
  { id: "WAX", label: "WAX" },
  { id: "WBTC", label: "Wrapped Bitcoin" },
  { id: "WCK", label: "Wrapped C...kitties" },
  { id: "WNXM", label: "Wrapped NXM" },
  { id: "STAKE", label: "xDAI Stake" },
  { id: "YAM", label: "Yam" },
  { id: "YAMV1", label: "Yam V1 Deprecated" },
  { id: "YAMV2", label: "Yam V2" },
  { id: "YFI", label: "Yearn.Finance" },
];

export const SwapErrors = {
  NETWORK_ERROR: "There seems to be a network error, please try again.",
  FETCH_TABLE_DATA_ERROR: "Failed to fetch trades from DEX.AG.",
  METAMASK_MISSING_ERROR: "Please install MetaMask and try again.",
};

export const dexagStatusNotification = {
  init: {
    text: `Starting validation`,
    type: "info",
  },
  request_wrap: {
    text: `WETH is required (Radar Relay). Wrapping WETH before continuing`,
    type: "info",
  },
  send_wrap: {
    text: `Waiting for wrap to finish mining`,
    type: "info",
  },
  mined_wrap: {
    text: `Wrap is finished mining`,
    type: "success",
  },
  allowance: {
    text: `Setting a token allowance for the DEX contract`,
    type: "info",
  },
  send_approve: {
    text: `Token allowance is mining`,
    type: "success",
  },
  mined_approve: {
    text: `Approve order has finished mining`,
    type: "success",
  },
  send_trade: {
    text: `Waiting for trade to finish mining`,
    type: "info",
  },
  mined_trade: {
    text: `Trade order has finished mining`,
    type: "success",
  },
  failed: {
    text: `Trade order failed`,
    type: "error",
  },
  web3_undefined: {
    text: `Web3 wallet is not enabled`,
    type: "error",
  },
  balance: {
    text: `Not enough funds to execute trade`,
    type: "error",
  },
  rejected: {
    text: `The checkout process was rejected`,
    type: "error",
  },
  bancor_notice: {
    text: `Executing trade on bancor with the gas restriction / feature`,
    type: "info",
  },
  bad_tx: {
    text: `The trade didn't pass final checks`,
    type: "warning",
  },
  connect_rejected: {
    text: `Web3 access was not allowed`,
    type: "error",
  },
  network: {
    text: `Please switch to the Main Ethereum network`,
    type: "error",
  },
};
