/* eslint-disable import/prefer-default-export */
export const avaxusdt1 = [
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.8468",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08T17:00:00.000Z",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.1349",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-14T13:00:00.000Z",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.0208",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-21T21:00:00.000Z",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.0837",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28T04:00:00.000Z",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.335",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-06T00:00:00.000Z",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.4093",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-08T00:00:00.000Z",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.7612",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11T08:00:00.000Z",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.5295",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26T04:00:00.000Z",
    botCycle: "4",
  },

  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.1531",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-09T16:00:00.000Z",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.1439",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-15T00:00:00.000Z",
    botCycle: "5",
  },

  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.3012",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-16T00:00:00.000Z",
    botCycle: "6",
  },

  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.3393",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-20T20:00:00.000Z",
    botCycle: "6",
  },

  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.2187",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-23T20:00:00.000Z",
    botCycle: "7",
  },

  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.8742",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-24T04:00:00.000Z",
    botCycle: "7",
  },

  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.1859",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-01T00:00:00.000Z",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11.2693",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20T12:00:00.000Z",
    botCycle: "8",
  },

  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13.6112",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31T12:00:00.000Z",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "41.387",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14T04:00:00.000Z",
    botCycle: "9",
  },

  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.1987",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01T16:00:00.000Z",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "24.4101",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-05T04:00:00.000Z",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.2576",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-07T08:00:00.000Z",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.92",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12T20:00:00.000Z",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33.036",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17T00:00:00.000Z",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32.8075",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21T12:00:00.000Z",
    botCycle: "12",
  },

  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.658",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-19T13:00:00.000Z",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.42",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26T01:00:00.000Z",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.339",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-20T21:00:00.000Z",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.121",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-21T09:00:00.000Z",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.449",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04T17:00:00.000Z",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.38",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06T01:00:00.000Z",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6.01",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11T21:00:00.000Z",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7.634",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12T05:00:00.000Z",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "44.069",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14T01:00:00.000Z",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "41.203",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14T01:00:00.000Z",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.647",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12T13:00:00.000Z",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.721",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12T13:00:00.000Z",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.838",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15T01:00:00.000Z",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36.626",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19T09:00:00.000Z",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.62",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07T18:00:00.000Z",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37.618",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14T14:00:00.000Z",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "35.21",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17T14:00:00.000Z",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32.921",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18T02:00:00.000Z",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.307",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05T02:00:00.000Z",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "38.485",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06T10:00:00.000Z",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.262",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-08T18:00:00.000Z",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "AVAXUSDT1",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11.464",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14T02:00:00.000Z",
    botCycle: "11",
  },
];
