/* eslint-disable import/prefer-default-export */
export const ethinfinity = [
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "608.43",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "1",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "593.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-02",
    botCycle: "1",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "596.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-02",
    botCycle: "2",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "593.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-02",
    botCycle: "2",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "595.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-03",
    botCycle: "3",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "604.84",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-04",
    botCycle: "3",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "609.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-04",
    botCycle: "4",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "588.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-04",
    botCycle: "4",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "589.45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-04",
    botCycle: "5",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "594",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-07",
    botCycle: "5",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "595.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-07",
    botCycle: "6",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "593.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-07",
    botCycle: "6",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "576.81",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-08",
    botCycle: "7",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "548.36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-09",
    botCycle: "7",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "567.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-09",
    botCycle: "8",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "554.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-10",
    botCycle: "8",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "557.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-10",
    botCycle: "9",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "541.43",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-11",
    botCycle: "9",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "558.39",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-12",
    botCycle: "10",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "584.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-13",
    botCycle: "10",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "588.23",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-14",
    botCycle: "11",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "585.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-14",
    botCycle: "11",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "588.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-14",
    botCycle: "12",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "578.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-14",
    botCycle: "12",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "582.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-14",
    botCycle: "13",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "614.11",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-23",
    botCycle: "13",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "579.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-24",
    botCycle: "14",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "607.8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-25",
    botCycle: "14",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "611.2",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-25",
    botCycle: "15",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "627.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-26",
    botCycle: "15",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "639.8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-27",
    botCycle: "16",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "724.45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-29",
    botCycle: "16",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "711.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-29",
    botCycle: "17",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "725.04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-30",
    botCycle: "17",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "728.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-30",
    botCycle: "18",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1120.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "18",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1022.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "19",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1103.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "19",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1114.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "20",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1187.46",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-07",
    botCycle: "20",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1242.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-07",
    botCycle: "21",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1085.46",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "21",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1080.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "22",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1164.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "22",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1217.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "23",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1381.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "23",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1368.96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "24",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1298.12",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-21",
    botCycle: "24",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1164.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-22",
    botCycle: "25",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1221.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-23",
    botCycle: "25",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1342.89",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "26",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1316.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "26",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1329.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "27",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1312.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "27",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1305.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "28",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1329.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-28",
    botCycle: "28",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1366.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "29",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1295.29",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "29",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1321.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "30",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1340.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-30",
    botCycle: "30",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1347.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-30",
    botCycle: "31",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1342.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-30",
    botCycle: "31",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1348.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-30",
    botCycle: "32",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1418.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-02",
    botCycle: "32",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1439.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-02",
    botCycle: "33",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1655.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "33",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1676",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "34",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1615.93",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "34",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1662.79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "35",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1799.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "35",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1840.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "36",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1802.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "36",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1817.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "37",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1781.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "37",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1780.49",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-17",
    botCycle: "38",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1952",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-20",
    botCycle: "38",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1961",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-20",
    botCycle: "39",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1872.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "39",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1561.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "40",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1465.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "40",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1489.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "41",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1592.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "41",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1560.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "42",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1548.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "42",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1561.65",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "43",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1465.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-05",
    botCycle: "43",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1477.89",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-05",
    botCycle: "44",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1817.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "44",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1832.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "45",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1805.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "45",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1800.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "46",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1806.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "46",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1885.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "47",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1900.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "47",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1903.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "48",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1896.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "48",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1883.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "49",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1871.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "49",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1867.02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "50",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1813.51",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "50",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1814.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "51",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1828.39",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-20",
    botCycle: "51",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1783.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "52",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1769.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "52",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1677.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "53",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1798.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-30",
    botCycle: "53",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1802.71",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-30",
    botCycle: "54",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1831.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-30",
    botCycle: "54",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1843.69",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-30",
    botCycle: "55",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2093.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "55",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2018.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "56",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2058.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "56",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2070.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "57",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1965.62",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "57",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1985.02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "58",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2070.96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "58",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2166.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "59",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2154.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "59",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2159.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "60",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2153.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "60",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2158.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "61",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2419.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "61",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2423.92",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "62",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2305.91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-21",
    botCycle: "62",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2312.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-21",
    botCycle: "63",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2588.65",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "63",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2626.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "64",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2737.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "64",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2866.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-01",
    botCycle: "65",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3457.25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "65",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3493.35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "66",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3966.3",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "66",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4004.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "67",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4284.12",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "67",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4285.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "68",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3878.17",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "68",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3884.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "69",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3354.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "69",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2669.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "70",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2679.96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "70",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1924.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "71",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2704.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "71",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2561.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "72",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2410",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "72",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2278.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "73",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2737.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "73",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2638.71",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "74",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2624.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "74",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2633.79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "75",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2624.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "75",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2633.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "76",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2696.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "76",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2707.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "77",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2399",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "77",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2299.11",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "78",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2577.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "78",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2598.44",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "79",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2573.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "79",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2566.15",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "80",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2407.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "80",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2436.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "81",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2317.43",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "81",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2239.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "82",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2170",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "82",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1960.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "83",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1929.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "83",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1952.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "84",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1944.71",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "84",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1921.16",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "85",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1987.94",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "85",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1941.23",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "86",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1983.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "86",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1836.92",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "87",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1818.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "87",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1827.56",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "88",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1836.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "88",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1844.11",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "89",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2135.04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "89",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2126.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "90",
  },
  {
    botRef: "ETHINFINITY",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2198.27",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "90",
  },
];
