/* eslint-disable import/prefer-default-export */
export const fluctusbtc = [
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "49566.19",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-02",
    botCycle: "1",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "50936.38",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "1",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "48348.35",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-16",
    botCycle: "2",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "47322.99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "2",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "43291.2",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-30",
    botCycle: "3",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "54653.53",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-10",
    botCycle: "3",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56512.74",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "4",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "55324.24",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-12",
    botCycle: "4",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56002.52",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-12",
    botCycle: "5",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "54607.14",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-13",
    botCycle: "5",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56174.46",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-13",
    botCycle: "6",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "62964.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-21",
    botCycle: "6",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "61603.34",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-30",
    botCycle: "7",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "60461.76",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-31",
    botCycle: "7",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "61305.92",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-31",
    botCycle: "8",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "60461.76",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-01",
    botCycle: "8",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "61080.6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-02",
    botCycle: "9",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "62183.78",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-03",
    botCycle: "9",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "62806.28",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-03",
    botCycle: "10",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "61847.6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-04",
    botCycle: "10",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "62210.02",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-05",
    botCycle: "11",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "61253.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-05",
    botCycle: "11",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "65206.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-08",
    botCycle: "12",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "64875.94",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-10",
    botCycle: "12",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "64695.45",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-13",
    botCycle: "13",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "63935.25",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-13",
    botCycle: "13",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "65525.65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-14",
    botCycle: "14",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "64281.73",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-15",
    botCycle: "14",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57608.21",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "15",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "56294.48",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-02",
    botCycle: "15",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "59129.24",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-12",
    botCycle: "16",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "48868.3",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-13",
    botCycle: "16",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "49253.92",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-22",
    botCycle: "17",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "48124.78",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-23",
    botCycle: "17",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "48359.6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-23",
    botCycle: "18",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "50394.62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-25",
    botCycle: "18",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "50347.54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-26",
    botCycle: "19",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "49823.07",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-28",
    botCycle: "19",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "43113.31",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-14",
    botCycle: "20",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "42972.92",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-16",
    botCycle: "20",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "43206.53",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-16",
    botCycle: "21",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "42963.99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-16",
    botCycle: "21",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "43223.85",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-16",
    botCycle: "22",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "42820.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-16",
    botCycle: "22",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "42356.35",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-18",
    botCycle: "23",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "41702.23",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-19",
    botCycle: "23",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "37570.57",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-29",
    botCycle: "24",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37508.61",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-30",
    botCycle: "24",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "37885.54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-30",
    botCycle: "25",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37021.97",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-31",
    botCycle: "25",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "37726.68",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "26",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "38280.86",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-02",
    botCycle: "26",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "38493.84",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-02",
    botCycle: "27",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37426.03",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-02",
    botCycle: "27",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "37873.09",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-04",
    botCycle: "28",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "43338.94",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-09",
    botCycle: "28",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "43812.13",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-09",
    botCycle: "29",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "43491.09",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-10",
    botCycle: "29",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "38932.1",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-26",
    botCycle: "30",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37602.72",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-27",
    botCycle: "30",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "38351.41",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-28",
    botCycle: "31",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "42222.51",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-03",
    botCycle: "31",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "42458.24",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-03",
    botCycle: "32",
  },
  {
    botRef: "FLUCTUSBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "41445.79",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-04",
    botCycle: "32",
  },
];
