/* eslint-disable import/prefer-default-export */
export const framav2eth = [
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "381.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-03",
    botCycle: "1",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "379.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "1",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "438.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-06",
    botCycle: "2",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "440.54",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-06",
    botCycle: "2",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "448.89",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-06",
    botCycle: "3",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "458.4",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "3",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "461.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "4",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "453.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "4",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "445.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-08",
    botCycle: "5",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "442.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-09",
    botCycle: "5",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "451.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-10",
    botCycle: "6",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "463.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-12",
    botCycle: "6",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "468.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-13",
    botCycle: "7",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "460.71",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-14",
    botCycle: "7",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "454.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-16",
    botCycle: "8",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "481.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-17",
    botCycle: "8",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "487.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-20",
    botCycle: "9",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "516.79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-21",
    botCycle: "9",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "515.8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-21",
    botCycle: "10",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "546.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-21",
    botCycle: "10",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "552.93",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-22",
    botCycle: "11",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "554.26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-23",
    botCycle: "11",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "578.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-23",
    botCycle: "12",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "584.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-23",
    botCycle: "12",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "606.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-23",
    botCycle: "13",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "608.26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-24",
    botCycle: "13",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "517.25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "14",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "508.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "14",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "509.68",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "15",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "517.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-27",
    botCycle: "15",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "524.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-28",
    botCycle: "16",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "533.68",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-29",
    botCycle: "16",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "548.44",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-29",
    botCycle: "17",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "581.35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-30",
    botCycle: "17",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "594.52",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-30",
    botCycle: "18",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "597.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-30",
    botCycle: "18",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "598.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-02",
    botCycle: "19",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "600.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-04",
    botCycle: "19",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "555.56",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-09",
    botCycle: "20",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "564.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-10",
    botCycle: "20",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "557.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-12",
    botCycle: "21",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "590.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-13",
    botCycle: "21",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "597.16",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-16",
    botCycle: "22",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "633",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-16",
    botCycle: "22",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "653.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-18",
    botCycle: "23",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "646.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-20",
    botCycle: "23",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "608.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-22",
    botCycle: "24",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "617.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-23",
    botCycle: "24",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "589.81",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-24",
    botCycle: "25",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "625.2",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-25",
    botCycle: "25",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "629.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-26",
    botCycle: "26",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "634.69",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-26",
    botCycle: "26",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "651.49",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-27",
    botCycle: "27",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "625.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-27",
    botCycle: "27",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "705.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-28",
    botCycle: "28",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "723.67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-28",
    botCycle: "28",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "743.25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-28",
    botCycle: "29",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "734.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-28",
    botCycle: "29",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "738.36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-29",
    botCycle: "30",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "719.13",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-29",
    botCycle: "30",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "728.39",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-29",
    botCycle: "31",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "724.16",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-30",
    botCycle: "31",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "759.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-02",
    botCycle: "32",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "756.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-02",
    botCycle: "32",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "786.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-03",
    botCycle: "33",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "834.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-03",
    botCycle: "33",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "917.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-03",
    botCycle: "34",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "973.02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-03",
    botCycle: "34",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "943.56",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-03",
    botCycle: "35",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1000.18",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "35",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1127.11",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "36",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1194.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "36",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1280.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-09",
    botCycle: "37",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1315.62",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "37",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1064.02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11",
    botCycle: "38",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1127.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "38",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1076.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-13",
    botCycle: "39",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1140.92",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-14",
    botCycle: "39",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1136.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-14",
    botCycle: "40",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1205.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-14",
    botCycle: "40",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1247.22",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "41",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1220.16",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "41",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1186.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "42",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1258.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "42",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1261.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "43",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1224.26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-18",
    botCycle: "43",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1243.13",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-18",
    botCycle: "44",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1317.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "44",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1374.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "45",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1382.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "45",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1430.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "46",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1396.54",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "46",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1198.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-22",
    botCycle: "47",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1270.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-22",
    botCycle: "47",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1265.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "48",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1341.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "48",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1360.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "49",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1442.04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "49",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1433.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "50",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1394.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "50",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1292.46",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "51",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1240.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "51",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1282.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-28",
    botCycle: "52",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1359.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-28",
    botCycle: "52",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1563.23",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-03",
    botCycle: "53",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1620.16",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-03",
    botCycle: "53",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1653.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "54",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1752.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "54",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1599.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "55",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1695.51",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "55",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1739.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-09",
    botCycle: "56",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1734.1",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-09",
    botCycle: "56",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1784.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "57",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1786.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "57",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1801.02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-11",
    botCycle: "58",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1762.27",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-11",
    botCycle: "58",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1812.25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-12",
    botCycle: "59",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1847.4",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "59",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1832.23",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "60",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1807",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "60",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1759.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "61",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1768.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "61",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1799.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-17",
    botCycle: "62",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1907.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-18",
    botCycle: "62",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1959.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-19",
    botCycle: "63",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1932",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-20",
    botCycle: "63",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1746.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "64",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1723.81",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "64",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1547.55",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "65",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1640.43",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-24",
    botCycle: "65",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1647.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-25",
    botCycle: "66",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1590.26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-25",
    botCycle: "66",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1506.11",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "67",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1449.25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "67",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1505.27",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "68",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1458.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "68",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1507.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "69",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1447.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-28",
    botCycle: "69",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1393.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-28",
    botCycle: "70",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1476.94",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "70",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1558.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "71",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1547.55",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "71",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1588.55",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "72",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1525.02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "72",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1629.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "73",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1592.23",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "73",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1522.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-05",
    botCycle: "74",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1542.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "74",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1588.51",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "75",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1683.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-07",
    botCycle: "75",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1692.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "76",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1705.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "76",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1746.67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "77",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1851.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "77",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1866.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "78",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1791.96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "78",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1844.28",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "79",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1804.2",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "79",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1812.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "80",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1770.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "80",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1790.17",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "81",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1897.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "81",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1790.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-16",
    botCycle: "82",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1768.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "82",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1817.29",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "83",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1799.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "83",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1821.03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "84",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1803.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "84",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1705.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "85",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1672.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "85",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1610.62",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-25",
    botCycle: "86",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1579.93",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-25",
    botCycle: "86",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1616.65",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-25",
    botCycle: "87",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1713.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-27",
    botCycle: "87",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1735.03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "88",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1839.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "88",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1855",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "89",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1966.3",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-01",
    botCycle: "89",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2052.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "90",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2040.22",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "90",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2105.84",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "91",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2086.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "91",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2018.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-08",
    botCycle: "92",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1997.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-08",
    botCycle: "92",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2029.55",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-08",
    botCycle: "93",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2151.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "93",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2194.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "94",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2264.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "94",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2341.45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "95",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2347",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "95",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2391.1",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "96",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2406.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "96",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2453.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "97",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2436.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "97",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2482",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "98",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2495.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "98",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2470.68",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "99",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2421.26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "99",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2220.55",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "100",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2131.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "100",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2146.03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "101",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2274.79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-19",
    botCycle: "101",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2147.8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-20",
    botCycle: "102",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2276.67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-20",
    botCycle: "102",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2311.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-25",
    botCycle: "103",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2287.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-25",
    botCycle: "103",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2410.84",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "104",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2425.78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "104",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2495.17",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "105",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2474.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "105",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2516.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-27",
    botCycle: "106",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2667.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-27",
    botCycle: "106",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2666.13",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "107",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2653.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "107",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2682.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "108",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2705.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "108",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2751.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "109",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2725.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "109",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2783.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "110",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2746.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "110",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2780.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "111",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2946.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-01",
    botCycle: "111",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2938.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-02",
    botCycle: "112",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2946.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "112",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2987.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "113",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3167.27",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "113",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3171.28",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "114",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3271.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "114",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3331.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "115",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3351.45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "115",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3412.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "116",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3440.36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "116",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3499.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "117",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3464.7",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "117",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3552.29",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "118",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3437.04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "118",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3543.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "119",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3755.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "119",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3946.94",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "120",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3911.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "120",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4127.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "121",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4038.18",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "121",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4155.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "122",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4102.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "122",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4055.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "123",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4299.35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "123",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4308.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "124",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4237.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "124",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3818.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "125",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4047.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "125",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3433.92",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "126",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3445.03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "126",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2587.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "127",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2742.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "127",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1981.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "128",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2100.54",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "128",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2826.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "129",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2737.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "129",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2521.49",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "130",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2420.65",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "130",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2293.36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "131",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2430.97",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "131",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2555.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "132",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2709.11",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "132",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2642.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "133",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2801.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "133",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2784.52",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "134",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2673.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "134",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2665.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "135",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2825.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "135",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2446.92",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "136",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2430.94",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "136",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2568.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "137",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2465.46",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "137",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2340.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "138",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2360.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "138",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2430.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "139",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2576.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "139",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2431.25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "140",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2392.78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "140",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2134.67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "141",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2262.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "141",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1969.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "142",
  },
  {
    botRef: "FRAMAV2ETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1909.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "142",
  },
];
