/* eslint-disable import/prefer-default-export */
export const gravitydusk = [
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0392",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-14",
    botCycle: "1",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0368",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-16",
    botCycle: "1",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0401",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-18",
    botCycle: "2",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0376",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-19",
    botCycle: "2",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.037",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-26",
    botCycle: "3",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0347",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-29",
    botCycle: "3",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0365",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-02",
    botCycle: "4",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0395",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-03",
    botCycle: "4",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0404",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-06",
    botCycle: "5",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0437",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-06",
    botCycle: "5",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0445",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-08",
    botCycle: "6",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0418",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-08",
    botCycle: "6",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0507",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-14",
    botCycle: "7",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0476",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-15",
    botCycle: "7",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0442",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-25",
    botCycle: "8",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0415",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-25",
    botCycle: "8",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0365",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-03",
    botCycle: "9",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0395",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-05",
    botCycle: "9",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0408",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-06",
    botCycle: "10",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0383",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-07",
    botCycle: "10",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0177",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-21",
    botCycle: "11",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0166",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-21",
    botCycle: "11",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0173",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-25",
    botCycle: "12",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0187",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-27",
    botCycle: "12",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.018",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-01",
    botCycle: "13",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0195",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-03",
    botCycle: "13",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0185",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-04",
    botCycle: "14",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.02",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-06",
    botCycle: "14",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0198",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-08",
    botCycle: "15",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0186",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-10",
    botCycle: "15",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0185",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-23",
    botCycle: "16",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.02",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-24",
    botCycle: "16",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0205",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-26",
    botCycle: "17",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0222",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-28",
    botCycle: "17",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0223",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-29",
    botCycle: "18",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0209",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-30",
    botCycle: "18",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0217",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-01",
    botCycle: "19",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0235",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-01",
    botCycle: "19",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0223",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-07",
    botCycle: "20",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0209",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-07",
    botCycle: "20",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0209",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-17",
    botCycle: "21",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0226",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-20",
    botCycle: "21",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0274",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-26",
    botCycle: "22",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0257",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-27",
    botCycle: "22",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0272",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-27",
    botCycle: "23",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0294",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-30",
    botCycle: "23",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0277",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-03",
    botCycle: "24",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.03",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-03",
    botCycle: "24",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0324",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-11",
    botCycle: "25",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0304",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-11",
    botCycle: "25",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0303",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-18",
    botCycle: "26",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0328",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-18",
    botCycle: "26",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0312",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-19",
    botCycle: "27",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0337",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-19",
    botCycle: "27",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0354",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-20",
    botCycle: "28",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0332",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-24",
    botCycle: "28",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0317",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-05",
    botCycle: "29",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0343",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-09",
    botCycle: "29",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0386",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-12",
    botCycle: "30",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0362",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-14",
    botCycle: "30",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0374",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-14",
    botCycle: "31",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0404",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-15",
    botCycle: "31",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0502",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-17",
    botCycle: "32",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0543",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-17",
    botCycle: "32",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0562",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-20",
    botCycle: "33",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0607",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-22",
    botCycle: "33",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.059",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-04",
    botCycle: "34",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0638",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-05",
    botCycle: "34",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.084",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-08",
    botCycle: "35",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0789",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-09",
    botCycle: "35",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0979",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-13",
    botCycle: "36",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1058",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-13",
    botCycle: "36",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1023",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-02",
    botCycle: "37",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0961",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-02",
    botCycle: "37",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0626",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-11",
    botCycle: "38",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0677",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-12",
    botCycle: "38",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0462",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-26",
    botCycle: "39",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0434",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-27",
    botCycle: "39",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0404",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-11",
    botCycle: "40",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0437",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-11",
    botCycle: "40",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0516",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-13",
    botCycle: "41",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0485",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-13",
    botCycle: "41",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0403",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-24",
    botCycle: "42",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0378",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-26",
    botCycle: "42",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0462",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-31",
    botCycle: "43",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0499",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-01",
    botCycle: "43",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0477",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "44",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0448",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-12",
    botCycle: "44",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0582",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-24",
    botCycle: "45",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0547",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-24",
    botCycle: "45",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0545",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-25",
    botCycle: "46",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0589",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-25",
    botCycle: "46",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0501",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-30",
    botCycle: "47",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.047",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "47",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0535",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-17",
    botCycle: "48",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0578",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-19",
    botCycle: "48",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0567",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-20",
    botCycle: "49",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0613",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-20",
    botCycle: "49",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0578",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-21",
    botCycle: "50",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0543",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-21",
    botCycle: "50",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0473",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-05",
    botCycle: "51",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0511",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "51",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0573",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-09",
    botCycle: "52",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0619",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-09",
    botCycle: "52",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0625",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "53",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0587",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "53",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0575",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "54",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0621",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "54",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0586",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "55",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0633",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-18",
    botCycle: "55",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0664",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "56",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0624",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "56",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0899",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-06",
    botCycle: "57",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0971",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "57",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0989",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "58",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1069",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-09",
    botCycle: "58",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1584",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-12",
    botCycle: "59",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1711",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-12",
    botCycle: "59",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1807",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "60",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1952",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "60",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2382",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-19",
    botCycle: "61",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2239",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-20",
    botCycle: "61",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2407",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "62",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.26",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "62",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2333",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "63",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2193",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "63",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2408",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "64",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2263",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "64",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2933",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "65",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3182",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "65",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2994",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "66",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2814",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "66",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2946",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "67",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3182",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "67",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3293",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "68",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3557",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "68",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3539",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-28",
    botCycle: "69",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3823",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "69",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3896",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "70",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3662",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "70",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3978",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-01",
    botCycle: "71",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4297",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-02",
    botCycle: "71",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4007",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "72",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3766",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "72",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.261",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "73",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2819",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "73",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.272",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "74",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2938",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "74",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1359",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "75",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1468",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "75",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.125",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "76",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.135",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "76",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.132",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "77",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.124",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "77",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1158",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "78",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1088",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "78",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1023",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-23",
    botCycle: "79",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1105",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "79",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1064",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "80",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.115",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "80",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1099",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-28",
    botCycle: "81",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1187",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-05",
    botCycle: "81",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1409",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "82",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1324",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "82",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1451",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "83",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1363",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "83",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1564",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "84",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.147",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "84",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1611",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "85",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1514",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "85",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1616",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-29",
    botCycle: "86",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1746",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-29",
    botCycle: "86",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1925",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-06",
    botCycle: "87",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1809",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "87",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1477",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "88",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1596",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-25",
    botCycle: "88",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1531",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-27",
    botCycle: "89",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1439",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-27",
    botCycle: "89",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1576",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-07",
    botCycle: "90",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1703",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-09",
    botCycle: "90",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1799",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "91",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1999",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "91",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1806",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-18",
    botCycle: "92",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1951",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-18",
    botCycle: "92",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1838",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-18",
    botCycle: "93",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1727",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-21",
    botCycle: "93",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1621",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-30",
    botCycle: "94",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1751",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-31",
    botCycle: "94",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1706",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-02",
    botCycle: "95",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1843",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-03",
    botCycle: "95",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1706",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-03",
    botCycle: "96",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1843",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-04",
    botCycle: "96",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2043",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-06",
    botCycle: "97",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2207",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-07",
    botCycle: "97",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2517",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-08",
    botCycle: "98",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2719",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-08",
    botCycle: "98",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2649",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-10",
    botCycle: "99",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2861",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-10",
    botCycle: "99",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3264",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-25",
    botCycle: "100",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3068",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-26",
    botCycle: "100",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3402",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-08",
    botCycle: "101",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3197",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-09",
    botCycle: "101",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4819",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-14",
    botCycle: "102",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5205",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-14",
    botCycle: "102",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6107",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-16",
    botCycle: "103",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.574",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-16",
    botCycle: "103",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6025",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-16",
    botCycle: "104",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5663",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-17",
    botCycle: "104",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5272",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-21",
    botCycle: "105",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5694",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-21",
    botCycle: "105",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6777",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-23",
    botCycle: "106",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.732",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-24",
    botCycle: "106",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.7301",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-26",
    botCycle: "107",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6862",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-27",
    botCycle: "107",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.97",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-01",
    botCycle: "108",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.9118",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-02",
    botCycle: "108",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5319",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-06",
    botCycle: "109",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5745",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-07",
    botCycle: "109",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3339",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-16",
    botCycle: "110",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3138",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-18",
    botCycle: "110",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3521",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-20",
    botCycle: "111",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3803",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-22",
    botCycle: "111",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3682",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-23",
    botCycle: "112",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3461",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-26",
    botCycle: "112",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.403",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-29",
    botCycle: "113",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4353",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-29",
    botCycle: "113",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4912",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-31",
    botCycle: "114",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5305",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-31",
    botCycle: "114",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4865",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-04-01",
    botCycle: "115",
  },
  {
    botRef: "GRAVITYDUSK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5255",
    sbl: "DUSKUSDT",
    base: "DUSK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-04-02",
    botCycle: "115",
  },
];
