/* eslint-disable import/prefer-default-export */
export const gravitynuls = [
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2352",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-13",
    botCycle: "1",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2541",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-15",
    botCycle: "1",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2597",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-16",
    botCycle: "2",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2805",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-18",
    botCycle: "2",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2686",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-29",
    botCycle: "3",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2901",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-30",
    botCycle: "3",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3983",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-14",
    botCycle: "4",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4302",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-14",
    botCycle: "4",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4235",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-15",
    botCycle: "5",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.398",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-15",
    botCycle: "5",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2551",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-04",
    botCycle: "6",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2756",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-05",
    botCycle: "6",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1552",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-21",
    botCycle: "7",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1458",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-22",
    botCycle: "7",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1495",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-24",
    botCycle: "8",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1615",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-26",
    botCycle: "8",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.196",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-01",
    botCycle: "9",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2117",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-07",
    botCycle: "9",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2078",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-08",
    botCycle: "10",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1953",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-09",
    botCycle: "10",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2088",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-10",
    botCycle: "11",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1962",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-10",
    botCycle: "11",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-12",
    botCycle: "12",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.188",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-13",
    botCycle: "12",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1959",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-17",
    botCycle: "13",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1841",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-20",
    botCycle: "13",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1933",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-23",
    botCycle: "14",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2088",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-23",
    botCycle: "14",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2121",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-26",
    botCycle: "15",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2291",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-30",
    botCycle: "15",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2224",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-01",
    botCycle: "16",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.209",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-04",
    botCycle: "16",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.221",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-08",
    botCycle: "17",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2077",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-10",
    botCycle: "17",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.215",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-15",
    botCycle: "18",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2322",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-20",
    botCycle: "18",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.234",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-25",
    botCycle: "19",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2528",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-26",
    botCycle: "19",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3199",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-01",
    botCycle: "20",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3007",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-02",
    botCycle: "20",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3307",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-04",
    botCycle: "21",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3108",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-07",
    botCycle: "21",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3274",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-07",
    botCycle: "22",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3536",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-08",
    botCycle: "22",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3497",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-09",
    botCycle: "23",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3287",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-11",
    botCycle: "23",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3962",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-19",
    botCycle: "24",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4279",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-21",
    botCycle: "24",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5099",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-29",
    botCycle: "25",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5507",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-02",
    botCycle: "25",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5293",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-03",
    botCycle: "26",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5717",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-03",
    botCycle: "26",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5658",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-04",
    botCycle: "27",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6111",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-05",
    botCycle: "27",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.469",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-21",
    botCycle: "28",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5066",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-24",
    botCycle: "28",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4896",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-25",
    botCycle: "29",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4602",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-26",
    botCycle: "29",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4553",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-03",
    botCycle: "30",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4918",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-07",
    botCycle: "30",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5011",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-08",
    botCycle: "31",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5412",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-09",
    botCycle: "31",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4572",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-29",
    botCycle: "32",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4938",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-29",
    botCycle: "32",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4824",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-30",
    botCycle: "33",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4534",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-01",
    botCycle: "33",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3247",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-11",
    botCycle: "34",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3052",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-13",
    botCycle: "34",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2761",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-04",
    botCycle: "35",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2595",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-06",
    botCycle: "35",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2753",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-11",
    botCycle: "36",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2587",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-14",
    botCycle: "36",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2455",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-23",
    botCycle: "37",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2307",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-27",
    botCycle: "37",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2103",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-09",
    botCycle: "38",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2272",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-10",
    botCycle: "38",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2428",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-16",
    botCycle: "39",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2282",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-18",
    botCycle: "39",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2613",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-29",
    botCycle: "40",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2456",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "40",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2572",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-02",
    botCycle: "41",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2778",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-04",
    botCycle: "41",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2615",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-07",
    botCycle: "42",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2825",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-08",
    botCycle: "42",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2608",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-14",
    botCycle: "43",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2817",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-14",
    botCycle: "43",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2773",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-15",
    botCycle: "44",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2995",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-17",
    botCycle: "44",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2789",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-18",
    botCycle: "45",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3013",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-19",
    botCycle: "45",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2906",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-20",
    botCycle: "46",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3139",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-20",
    botCycle: "46",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2177",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "47",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2352",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "47",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2581",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "48",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2788",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "48",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2685",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "49",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.29",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-18",
    botCycle: "49",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3516",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "50",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3305",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "50",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.375",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-03",
    botCycle: "51",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.405",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-03",
    botCycle: "51",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3775",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "52",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4077",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "52",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4004",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-06",
    botCycle: "53",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3763",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "53",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.728",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "54",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8045",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "54",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.71",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "55",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6674",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "55",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.7106",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "56",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6679",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "56",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5562",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "57",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6007",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-07",
    botCycle: "57",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.68",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "58",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6392",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "58",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.9249",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "59",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8694",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "59",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.8584",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-16",
    botCycle: "60",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.9271",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "60",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.8982",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "61",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8443",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "61",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.8829",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "62",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.9536",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-20",
    botCycle: "62",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.88",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "63",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.9504",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "63",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.9113",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "64",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.9843",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "64",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.0921",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "65",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0265",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "65",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.077",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "66",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.1632",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-01",
    botCycle: "66",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.113",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "67",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.2021",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "67",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.4166",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "68",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.3316",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "68",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.1283",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-01",
    botCycle: "69",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.2186",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-01",
    botCycle: "69",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.1482",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-02",
    botCycle: "70",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0793",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "70",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.2701",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "71",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.3718",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "71",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5754",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "72",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6215",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "72",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6038",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "73",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5675",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "73",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3824",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "74",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.413",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "74",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3722",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-15",
    botCycle: "75",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3498",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "75",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3553",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "76",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3838",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "76",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3864",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-28",
    botCycle: "77",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4174",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-29",
    botCycle: "77",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4032",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-01",
    botCycle: "78",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4355",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "78",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6172",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-14",
    botCycle: "79",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5801",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "79",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5955",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "80",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5597",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "80",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6032",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-22",
    botCycle: "81",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6515",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-23",
    botCycle: "81",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6316",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "82",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6822",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-04",
    botCycle: "82",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5636",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-12",
    botCycle: "83",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5297",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-13",
    botCycle: "83",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4718",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-03",
    botCycle: "84",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4434",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-04",
    botCycle: "84",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5245",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-13",
    botCycle: "85",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5665",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-15",
    botCycle: "85",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5707",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "86",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6164",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "86",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5793",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-20",
    botCycle: "87",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6257",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-22",
    botCycle: "87",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5876",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-23",
    botCycle: "88",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5523",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-27",
    botCycle: "88",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.562",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-30",
    botCycle: "89",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.607",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-04",
    botCycle: "89",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5746",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-05",
    botCycle: "90",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6206",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-09",
    botCycle: "90",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.61",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-10",
    botCycle: "91",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5734",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-10",
    botCycle: "91",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.5302",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-23",
    botCycle: "92",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5727",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-25",
    botCycle: "92",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.9165",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-07",
    botCycle: "93",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8615",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-07",
    botCycle: "93",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.8738",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-13",
    botCycle: "94",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8213",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-13",
    botCycle: "94",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.8406",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-14",
    botCycle: "95",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.9079",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-14",
    botCycle: "95",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.8359",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-15",
    botCycle: "96",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.9028",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-15",
    botCycle: "96",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.9378",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-19",
    botCycle: "97",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0129",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-19",
    botCycle: "97",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.9053",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-25",
    botCycle: "98",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8509",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-28",
    botCycle: "98",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6324",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-16",
    botCycle: "99",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5944",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-16",
    botCycle: "99",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.379",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-28",
    botCycle: "100",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4094",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-31",
    botCycle: "100",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4033",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-01",
    botCycle: "101",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3791",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-02",
    botCycle: "101",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.413",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-06",
    botCycle: "102",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4461",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-06",
    botCycle: "102",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4718",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-16",
    botCycle: "103",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4434",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-17",
    botCycle: "103",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4929",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-17",
    botCycle: "104",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4571",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-17",
    botCycle: "104",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4652",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-20",
    botCycle: "105",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4372",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-20",
    botCycle: "105",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.454",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-20",
    botCycle: "106",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4267",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-20",
    botCycle: "106",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3888",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-10",
    botCycle: "107",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.42",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-10",
    botCycle: "107",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3893",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-13",
    botCycle: "108",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.3659",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-13",
    botCycle: "108",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3851",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-18",
    botCycle: "109",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.416",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-18",
    botCycle: "109",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4042",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-20",
    botCycle: "110",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4366",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-20",
    botCycle: "110",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.436",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-26",
    botCycle: "111",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4709",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-28",
    botCycle: "111",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4821",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-04-03",
    botCycle: "112",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5207",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-04-03",
    botCycle: "112",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4966",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-04-04",
    botCycle: "113",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5364",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-04-04",
    botCycle: "113",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.4906",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-04-15",
    botCycle: "114",
  },
  {
    botRef: "GRAVITYNULS",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.4611",
    sbl: "NULSUSDT",
    base: "NULS",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-04-18",
    botCycle: "114",
  },
];
