/* eslint-disable import/prefer-default-export */
export const harsibtc = [
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "63800.97",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-12",
    botCycle: "1",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "65339.51",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-15",
    botCycle: "1",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "65339.51",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-15",
    botCycle: "2",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "60588.06",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-16",
    botCycle: "2",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "60588.06",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-16",
    botCycle: "3",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "58795.56",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-21",
    botCycle: "3",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "58795.56",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-21",
    botCycle: "4",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "57034.25",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-24",
    botCycle: "4",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57034.25",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-24",
    botCycle: "5",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57740.01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "5",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "57740.01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "6",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "56544.53",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-03",
    botCycle: "6",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56544.53",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-03",
    botCycle: "7",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "49767.8",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-13",
    botCycle: "7",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "49767.8",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-13",
    botCycle: "8",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "47167.77",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-14",
    botCycle: "8",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "47167.77",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-14",
    botCycle: "9",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "48667.99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-16",
    botCycle: "9",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "48667.99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-16",
    botCycle: "10",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "47255.67",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-17",
    botCycle: "10",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "47255.67",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-17",
    botCycle: "11",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "50600.14",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-27",
    botCycle: "11",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "50699.19",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-27",
    botCycle: "12",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "42313.34",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-18",
    botCycle: "12",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "42328.37",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-18",
    botCycle: "13",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "42375.75",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-20",
    botCycle: "13",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "42375.75",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-20",
    botCycle: "14",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "37327.99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-31",
    botCycle: "14",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "37327.99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-31",
    botCycle: "15",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "38312.62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-01",
    botCycle: "15",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "38312.62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-01",
    botCycle: "16",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "36861.48",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-03",
    botCycle: "16",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36861.48",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-03",
    botCycle: "17",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "44088.03",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-16",
    botCycle: "17",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "43980.19",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-16",
    botCycle: "18",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "35575.3",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-24",
    botCycle: "18",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "35575.3",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-24",
    botCycle: "19",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39021.49",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-26",
    botCycle: "19",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "39021.49",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-26",
    botCycle: "20",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "38250.42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-28",
    botCycle: "20",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "38250.42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-28",
    botCycle: "21",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "43422.91",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-01",
    botCycle: "21",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "43422.91",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-01",
    botCycle: "22",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "39425.31",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-06",
    botCycle: "22",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39425.31",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-06",
    botCycle: "23",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "41316.49",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-10",
    botCycle: "23",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "41316.49",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-10",
    botCycle: "24",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "39162.89",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-11",
    botCycle: "24",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39162.89",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-11",
    botCycle: "25",
  },
  {
    botRef: "HARSIBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39265.36",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-16",
    botCycle: "25",
  },
];
