/* eslint-disable import/prefer-default-export */
export const irobotbtc = [
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10548.05",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-14",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10834.62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-20",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10538.04",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-24",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10617.74",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10772.27",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13221.26",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13808.04",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-31",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "14643.52",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15888.61",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17891.76",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-22",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "18883.11",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-24",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17927.98",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19397.92",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-30",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18762.95",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-08",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19329.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-13",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22646.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-21",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "24181.86",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-25",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30742.99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34601.03",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37472.4",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34535.16",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37921.12",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "40611.28",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "54515",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "51562.03",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "48000.37",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "52168.54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57789.75",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56773.16",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57051.95",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "59417.46",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "56320.47",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "59155.63",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "IROBOTBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "60853.8",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "17",
  },
];
