/* eslint-disable import/prefer-default-export */
export const irobotbnb = [
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "25.633",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-10",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.1384",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-11",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "25.4521",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-11",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.4193",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-15",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.5402",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-29",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.7408",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.7979",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-10",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.3715",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-16",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.9111",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-22",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.9711",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-25",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31.0831",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-26",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.1816",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-06",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.3747",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.3858",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-17",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.7249",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-18",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.1049",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-19",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.9756",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.2408",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-13",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32.3244",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-21",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34.2899",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-27",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39.0528",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "44.9116",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "42.5226",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "43.1646",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "253.01",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "252.0494",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "261.396",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "267.90",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-27",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "IROBOTBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "508.26",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "15",
  },
];
