/* eslint-disable import/prefer-default-export */
export const iroboteth = [
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "387.2",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-17",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "370.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-20",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "344.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-24",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "353.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "353.3",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "365.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-16",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "380.1",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-19",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "367.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-20",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "382.39",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-21",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "393.62",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-26",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "402.44",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "431.04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "465.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "445.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-15",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "475.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-17",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "532.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "620.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "567.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-05",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "604.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-16",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "606.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-21",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "634.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-26",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1105.02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1341.25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1265.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1375.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1312.8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1459.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-02",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1538.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1744,75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1727.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1833.78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1912.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1639.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1793.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1730.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-27",
    botCycle: "18",
  },
  {
    botId: undefined,
    botRef: "IROBOTETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1977.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "18",
  },
];
