/* eslint-disable import/prefer-default-export */
export const laikanear = [
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.020",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "1",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.256",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "1",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.611",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-03",
    botCycle: "2",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.953",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "2",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.592",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "3",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5.853",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "3",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6.520",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "4",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "6.341",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "4",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5.754",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "5",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5.637",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "5",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6.052",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "6",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5.211",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "6",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.343",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "7",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.092",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "7",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.165",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "8",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8.181",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-20",
    botCycle: "8",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8.493",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-08",
    botCycle: "9",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7.580",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "9",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8.536",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-20",
    botCycle: "10",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9.829",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-31",
    botCycle: "10",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.262",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-11",
    botCycle: "11",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10.344",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-16",
    botCycle: "11",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9.603",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-09",
    botCycle: "12",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8.711",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-17",
    botCycle: "12",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11.368",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-22",
    botCycle: "13",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15.209",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-07",
    botCycle: "13",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "16.423",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-11",
    botCycle: "14",
  },
  {
    botRef: "LAIKANEAR",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17.451",
    sbl: "NEARUSDT",
    base: "NEAR",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-19",
    botCycle: "14",
  },
];
