/* eslint-disable import/prefer-default-export */
export const laikaavax = [
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6.0351",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11",
    botCycle: "1",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "41.38",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-18",
    botCycle: "1",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.499",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "2",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.4335",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-16",
    botCycle: "2",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.5641",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "3",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.17",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "3",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.5929",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "4",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.25",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "4",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.2991",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "5",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.4094",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "5",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33.1785",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "6",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.5356",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "6",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.15",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "7",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34.652",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "7",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "38.462",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "8",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35.591",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "8",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "20.023",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "9",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17.914",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "9",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.019",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "10",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.645",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "10",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.283",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-23",
    botCycle: "11",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "45.86",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "11",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "52.61",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-11",
    botCycle: "12",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57.72",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-21",
    botCycle: "12",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "74.38",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-23",
    botCycle: "13",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "62.91",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-26",
    botCycle: "13",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "61.02",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-20",
    botCycle: "14",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "62.06",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-27",
    botCycle: "14",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "71.13",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-03",
    botCycle: "15",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "112.74",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-26",
    botCycle: "15",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "101.24",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-15",
    botCycle: "16",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "111.95",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-26",
    botCycle: "16",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "73.7",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-02",
    botCycle: "17",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "68.5",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-03",
    botCycle: "17",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "76.67",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-04",
    botCycle: "18",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "81.97",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-12",
    botCycle: "18",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "92.97",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-15",
    botCycle: "19",
  },
  {
    botRef: "LAIKAAVAX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "83.39",
    sbl: "AVAXUSDT",
    base: "AVAX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-18",
    botCycle: "19",
  },
];
