/* eslint-disable import/prefer-default-export */
export const laikaatom = [
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-09",
    botCycle: "1",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5.61",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11",
    botCycle: "1",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-14",
    botCycle: "2",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-21",
    botCycle: "2",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "3",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "20",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "3",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "20",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "4",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-19",
    botCycle: "4",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "21",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "5",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "19",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "5",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19.8",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "6",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "19",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "6",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "20",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "7",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "21",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "7",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "20",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-30",
    botCycle: "8",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "8",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "9",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "21",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "9",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-11",
    botCycle: "10",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "10",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "21",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "11",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "11",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "25",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "12",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "25",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "12",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.05",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "13",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13.46",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "13",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "14",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "14",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "14",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "15",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-08",
    botCycle: "15",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "16",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "16",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-24",
    botCycle: "17",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "17",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.1",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-31",
    botCycle: "18",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "18",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "19",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "14",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "19",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "20",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "14",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "20",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "18",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "21",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "20",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "21",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.14",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "22",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "21.08",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "22",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "26.7",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-09",
    botCycle: "23",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34.01",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-20",
    botCycle: "23",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39.97",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-23",
    botCycle: "24",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36.19",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-26",
    botCycle: "24",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "40.62",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-02",
    botCycle: "25",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37.96",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-04",
    botCycle: "25",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33.62",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-20",
    botCycle: "26",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34.19",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-24",
    botCycle: "26",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36.2",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-26",
    botCycle: "27",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36.95",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-31",
    botCycle: "27",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31.88",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-22",
    botCycle: "28",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.05",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "28",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.06",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-03",
    botCycle: "29",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "25.27",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-04",
    botCycle: "29",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.63",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-21",
    botCycle: "30",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.92",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-28",
    botCycle: "30",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.88",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-31",
    botCycle: "31",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36.78",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-08",
    botCycle: "31",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "40.08",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-12",
    botCycle: "32",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "38.06",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-14",
    botCycle: "32",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "40.11",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-15",
    botCycle: "33",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "38.45",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-18",
    botCycle: "33",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.23",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-04",
    botCycle: "34",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.39",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-08",
    botCycle: "34",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.85",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-17",
    botCycle: "35",
  },
  {
    botRef: "LAIKAATOM",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.41",
    sbl: "ATOMUSDT",
    base: "ATOM",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-18",
    botCycle: "35",
  },
];
