/* eslint-disable import/prefer-default-export */
export const laikaada = [
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.31881",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "1",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.32363",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-22",
    botCycle: "1",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.35981",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "2",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.34355",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "2",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.40876",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-01",
    botCycle: "3",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.97236",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "3",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.02669",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-24",
    botCycle: "4",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.115",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "4",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.24924",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-16",
    botCycle: "5",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.1015",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "5",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.20787",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-02",
    botCycle: "6",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.181",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "6",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.25775",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "7",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.18283",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "7",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.22395",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "8",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.24902",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "8",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.3379",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "9",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.7823",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "9",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.7117",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "10",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.6763",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "10",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.3853",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "11",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.313",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "11",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.3946",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "12",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.3725",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-08",
    botCycle: "12",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.3465",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "13",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.833",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-06",
    botCycle: "13",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.311",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-02",
    botCycle: "14",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.196",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-04",
    botCycle: "14",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.285",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "15",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.226",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "15",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.038",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-08",
    botCycle: "16",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.013",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-12",
    botCycle: "16",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.345",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-22",
    botCycle: "17",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.332",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-29",
    botCycle: "17",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.291",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-15",
    botCycle: "18",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.207",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-21",
    botCycle: "18",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.102",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-04",
    botCycle: "19",
  },
  {
    botRef: "LAIKAADA",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.079",
    sbl: "ADAUSDT",
    base: "ADA",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-11",
    botCycle: "19",
  },
];
