/* eslint-disable import/prefer-default-export */
export const nlsftt = [
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8.29",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11",
    botCycle: "1",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9.32",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-14",
    botCycle: "1",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9.07",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "2",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9.51",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "2",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10.07",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "3",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10.19",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "3",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9.78",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "4",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.5",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "4",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11.02",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "5",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.89",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-03",
    botCycle: "5",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13.86",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "6",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "16.79",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-09",
    botCycle: "6",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19.02",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "7",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "20.4",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "7",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.81",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-20",
    botCycle: "8",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "33.4",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "8",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.2",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "9",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.35",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-24",
    botCycle: "9",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.05",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "10",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.47",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "10",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36.75",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "11",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "40.24",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "11",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39.55",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-16",
    botCycle: "12",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39.89",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "12",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39.97",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "13",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "40.84",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "13",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "38.74",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "14",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39.44",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "14",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "35.56",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "15",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "33.43",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-26",
    botCycle: "15",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "53.09",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "16",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "53.64",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "16",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "51.37",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "17",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "51.24",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-19",
    botCycle: "17",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "48.1",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-20",
    botCycle: "18",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "52.4",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-21",
    botCycle: "18",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "44.49",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-23",
    botCycle: "19",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "49.39",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "19",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "51.52",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "20",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "54.34",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "20",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "54.67",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "21",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "56.76",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "21",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "58.7",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "22",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57.72",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "22",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "50.07",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "23",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "52.13",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "23",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "35.38",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "24",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31.63",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "24",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.12",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "25",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "33.28",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "25",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31.73",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "26",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31.79",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "26",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34.28",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "27",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35.82",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "27",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.46",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "28",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32.63",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "28",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.75",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "29",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32.71",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "29",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31.97",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "30",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.49",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "30",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.63",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "31",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.04",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "31",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "26.38",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "32",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.1",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-03",
    botCycle: "32",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "26.51",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "33",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.03",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "33",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.5",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "34",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.99",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "34",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.23",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "35",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.86",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-18",
    botCycle: "35",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "24.88",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "36",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.87",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-21",
    botCycle: "36",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34.99",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-01",
    botCycle: "37",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36.11",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "37",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "46.9",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-14",
    botCycle: "38",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "52.44",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-16",
    botCycle: "38",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "44.85",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "39",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "51.93",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-20",
    botCycle: "39",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "49.61",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-22",
    botCycle: "40",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "50.77",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-23",
    botCycle: "40",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "46.03",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-31",
    botCycle: "41",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "64.14",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-01",
    botCycle: "41",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "68.49",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "42",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "77.66",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-09",
    botCycle: "42",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "68.24",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-13",
    botCycle: "43",
  },
  {
    botRef: "NLSFTT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "67.86",
    sbl: "FTTUSDT",
    base: "FTT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-14",
    botCycle: "43",
  },
];
