/* eslint-disable import/prefer-default-export */
export const optimusbnb = [
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.39440",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-01",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15.67070",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-02",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.40160",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-03",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15.28560",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-04",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.35920",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-04",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15.35310",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-05",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.57030",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-06",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "16.94530",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-09",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17.05230",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-10",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18.04830",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-13",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "18.74000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-13",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18.40070",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-14",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17.14170",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-17",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17.06750",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-18",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17.18520",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-18",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "16.95420",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-19",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17.75750",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-19",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17.72370",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-20",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17.83590",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-21",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17.72680",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-22",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17.72290",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-22",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17.46900",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-22",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17.70000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-22",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18.40960",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-24",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19.04240",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-24",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "19.45800",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-26",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19.74890",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-28",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "20.10590",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-29",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19.98500",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-30",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "20.17440",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-02",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "20.97920",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-03",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "21.64250",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-04",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.29670",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-05",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22.92720",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-06",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.53770",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-08",
    botCycle: "18",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22.53590",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-09",
    botCycle: "18",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.71320",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-10",
    botCycle: "19",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22.40570",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-11",
    botCycle: "19",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "21.69860",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-12",
    botCycle: "20",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "21.52130",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-13",
    botCycle: "20",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "21.77510",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-14",
    botCycle: "21",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.10450",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-16",
    botCycle: "21",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.61580",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-16",
    botCycle: "22",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.14430",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-17",
    botCycle: "22",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.69420",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-17",
    botCycle: "23",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.10420",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-18",
    botCycle: "23",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.27590",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-20",
    botCycle: "24",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22.47490",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-21",
    botCycle: "24",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.20100",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-23",
    botCycle: "25",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "21.99370",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-23",
    botCycle: "25",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.21500",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-24",
    botCycle: "26",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22.24400",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-25",
    botCycle: "26",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.03950",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-26",
    botCycle: "27",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.07830",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-29",
    botCycle: "27",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.97510",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-29",
    botCycle: "28",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22.94410",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-30",
    botCycle: "28",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.34000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-30",
    botCycle: "29",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.35050",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-31",
    botCycle: "29",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.33100",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-01",
    botCycle: "30",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.06460",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-01",
    botCycle: "30",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.53320",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-01",
    botCycle: "31",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "24.64580",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-02",
    botCycle: "31",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "25.10020",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-03",
    botCycle: "32",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.87770",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-03",
    botCycle: "32",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "20.99950",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-05",
    botCycle: "33",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "20.61700",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-05",
    botCycle: "33",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "20.01170",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-06",
    botCycle: "34",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22.02750",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-07",
    botCycle: "34",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.45980",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-08",
    botCycle: "35",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "24.55790",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-11",
    botCycle: "35",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "24.79250",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-11",
    botCycle: "36",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.29140",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-14",
    botCycle: "36",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.71310",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-14",
    botCycle: "37",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31.25460",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-15",
    botCycle: "37",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.88760",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-16",
    botCycle: "38",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.97850",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-17",
    botCycle: "38",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.82440",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-18",
    botCycle: "39",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.30710",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-18",
    botCycle: "39",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.34940",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-19",
    botCycle: "40",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.15410",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-19",
    botCycle: "40",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.97300",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-22",
    botCycle: "41",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.80020",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-23",
    botCycle: "41",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.81800",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-24",
    botCycle: "42",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "24.45000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-25",
    botCycle: "42",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "24.71420",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-25",
    botCycle: "43",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.24350",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-28",
    botCycle: "43",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "26.45930",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-28",
    botCycle: "44",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "25.90190",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-28",
    botCycle: "44",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.27560",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-28",
    botCycle: "45",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.05060",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-30",
    botCycle: "45",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.16270",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-30",
    botCycle: "46",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.74080",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "46",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.33380",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-03",
    botCycle: "47",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.22070",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-05",
    botCycle: "47",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.66860",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-06",
    botCycle: "48",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.18270",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-06",
    botCycle: "48",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.67610",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-07",
    botCycle: "49",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.77480",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08",
    botCycle: "49",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.44360",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08",
    botCycle: "50",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.48990",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-10",
    botCycle: "50",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.47480",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-11",
    botCycle: "51",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.89280",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-13",
    botCycle: "51",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31.07450",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-14",
    botCycle: "52",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.46920",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-14",
    botCycle: "52",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.83520",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-15",
    botCycle: "53",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.37150",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-16",
    botCycle: "53",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.23510",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-17",
    botCycle: "54",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.24230",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-18",
    botCycle: "54",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.53180",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-18",
    botCycle: "55",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.65680",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-19",
    botCycle: "55",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.49650",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-21",
    botCycle: "56",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.73440",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-23",
    botCycle: "56",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.96390",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-23",
    botCycle: "57",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.40430",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-23",
    botCycle: "57",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.69510",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-24",
    botCycle: "58",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.97110",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-25",
    botCycle: "58",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.62910",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-26",
    botCycle: "59",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31.60000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28",
    botCycle: "59",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.49000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-31",
    botCycle: "60",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.40000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-31",
    botCycle: "60",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.49000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-02",
    botCycle: "61",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.28000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-02",
    botCycle: "61",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "26.28000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "62",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.27000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "62",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "26.94000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-05",
    botCycle: "63",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.38000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "63",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.56000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-08",
    botCycle: "64",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.60000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-09",
    botCycle: "64",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.33000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "65",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.06000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "65",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.80000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-13",
    botCycle: "66",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.65000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-14",
    botCycle: "66",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.90000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-15",
    botCycle: "67",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.69000",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-16",
    botCycle: "67",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.82680",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-16",
    botCycle: "68",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.24270",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-18",
    botCycle: "68",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.24270",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-19",
    botCycle: "69",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.92190",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-21",
    botCycle: "69",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.92190",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-21",
    botCycle: "70",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.75350",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-22",
    botCycle: "70",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.59910",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-22",
    botCycle: "71",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBNB",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.98720",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-23",
    botCycle: "71",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "224,64",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "1",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "250,17",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "1",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "249,2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "2",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "240,53",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "2",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "227,31",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-05",
    botCycle: "3",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "221,42",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "3",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "226,37",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-07",
    botCycle: "4",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "232,4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "4",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "235,38",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "5",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "278,61",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "5",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "291,51",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "6",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "279,37",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "6",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "254,42",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-16",
    botCycle: "7",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "254,86",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "7",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "263,43",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "8",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "258,59",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "8",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "266,83",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "9",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "264,03",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "9",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "264,39",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "10",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "254,74",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "10",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "245,74",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-26",
    botCycle: "11",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "265,57",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-28",
    botCycle: "11",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "273,36",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "12",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "298,35",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "12",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "305,63",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-01",
    botCycle: "13",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "337,68",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "13",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "345,92",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "14",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "370,94",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "14",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "395,87",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-08",
    botCycle: "15",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "471,38",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-11",
    botCycle: "15",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "492,53",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-11",
    botCycle: "16",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "549,86",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "16",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "567,55",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "17",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "546,76",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "17",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "536,49",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "18",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "510,31",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "18",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "481,44",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-19",
    botCycle: "19",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "504,13",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-19",
    botCycle: "19",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "527,77",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-20",
    botCycle: "20",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "583,08",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-21",
    botCycle: "20",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "569,53",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "21",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "526,14",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "21",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "519,06",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-23",
    botCycle: "22",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "489,82",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-24",
    botCycle: "22",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "511,74",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-25",
    botCycle: "23",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "554,64",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "23",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "561,5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "24",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "654,88",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "24",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "641,83",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "25",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "639,86",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "25",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "635,78",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "26",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "665,12",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "26",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "654,76",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "27",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "664,5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "27",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "596,92",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "28",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "581,03",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "28",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "591,41",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "29",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "549,62",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "29",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "524,54",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "30",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "502,6",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "30",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "372,42",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "31",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "381,63",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "31",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "372,13",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "32",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "346,38",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "32",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "346,18",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "33",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "375,72",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "33",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "352,77",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "34",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "366,53",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "34",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "360,17",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "35",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "346,06",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "35",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "345,84",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "36",
  },
  {
    botRef: "OPTIMUSBNB",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "335,76",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "36",
  },
];
