/* eslint-disable import/prefer-default-export */
export const optimuseth = [
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "227,98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-30",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "225,58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-01",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "227,66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-01",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "225,73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-02",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "229,24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-05",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "224,96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-05",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "232,82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-06",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "241,97",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-10",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "239,54",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-12",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "237,7",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-12",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "242,76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-13",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "238,67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-14",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "240,45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-15",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "239,26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-15",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "234,95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-18",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "316,09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-30",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "333,28",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-30",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "385,47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-07",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "397,05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-09",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "391,46",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-11",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "394,54",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-13",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "417,84",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-16",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "437,39",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-17",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "427",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-18",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "415,95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-21",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "404,21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-21",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "393,22",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-24",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "385,56",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-25",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "393,68",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-28",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "435,71",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-02",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "348,79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-08",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "341,34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-08",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "352,48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-09",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "363,04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-13",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "374,51",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-14",
    botCycle: "18",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "366",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-15",
    botCycle: "18",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "379,91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-17",
    botCycle: "19",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "384,82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-19",
    botCycle: "19",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "385,25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-20",
    botCycle: "20",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "381,38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-20",
    botCycle: "20",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "345,97",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-24",
    botCycle: "21",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "357,64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-29",
    botCycle: "21",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "359,78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-30",
    botCycle: "22",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "355,05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-30",
    botCycle: "22",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "362,33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "23",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "353,23",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-02",
    botCycle: "23",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "347,79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-04",
    botCycle: "24",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "340,36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-06",
    botCycle: "24",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "351,2",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08",
    botCycle: "25",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "375,82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-14",
    botCycle: "25",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "372,78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-18",
    botCycle: "26",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "371,03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-20",
    botCycle: "26",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "379,37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-21",
    botCycle: "27",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "409,55",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-25",
    botCycle: "27",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "403",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28",
    botCycle: "28",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "386",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28",
    botCycle: "28",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "388",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-31",
    botCycle: "29",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "385",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-02",
    botCycle: "29",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "401,91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "30",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "435,38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-08",
    botCycle: "30",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "453,84",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-08",
    botCycle: "31",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "437,57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-09",
    botCycle: "31",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "462",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "32",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "460",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-14",
    botCycle: "32",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "460,03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-17",
    botCycle: "33",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "470,8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-19",
    botCycle: "33",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "491,35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-19",
    botCycle: "34",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSETH",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "586,25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-25",
    botCycle: "34",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1368,05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-02",
    botCycle: "1",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1633,42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "1",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1694,35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "2",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1722,78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-11",
    botCycle: "2",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1790,25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-11",
    botCycle: "3",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1802,75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "3",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1805,02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-17",
    botCycle: "4",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1914,05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "4",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1618,42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-25",
    botCycle: "5",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1479,66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "5",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1522,83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "6",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1539,72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-05",
    botCycle: "6",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1589,04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "7",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1765,88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "7",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1871,94",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "8",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1771,6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "8",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1824,45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "9",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1774,98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "9",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1822,77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "10",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1770,79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "10",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1661,61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-26",
    botCycle: "11",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2033,53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "11",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2101,53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "12",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1975,76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "12",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2069,91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "13",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2134,14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "13",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2161,43",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "14",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2344,59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "14",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2323,48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-20",
    botCycle: "15",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2130,35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-23",
    botCycle: "15",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2267,25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-25",
    botCycle: "16",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3928,63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "16",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4051,95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "17",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3754,22",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "17",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2490,27",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "18",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2563,9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "18",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2554,82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "19",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2621,57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "19",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2720,91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "20",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2491,22",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "20",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2562,31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "21",
  },
  {
    botRef: "OPTIMUSETH",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2473,34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "21",
  },
];
