/* eslint-disable import/prefer-default-export */
export const optimusbtc = [
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9112.12",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-28",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9048,92",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-02",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9129,31",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-04",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9034,54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-05",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9087,91",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-06",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9208,58",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-09",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9272,47",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-12",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9215,75",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-12",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9303,31",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-13",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9242,61",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-14",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9255,85",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-15",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9234,86",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-15",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9154,31",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-18",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9135,01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-18",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9159,91",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-18",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9124,41",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-19",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9208,99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-20",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9160,78",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-21",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9180,71",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-21",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10941,64",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-30",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11116,82",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-30",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10976,26",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-31",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11131,11",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-31",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11105,54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-02",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11240,56",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-05",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11488,9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-07",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11738,39",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-08",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11567,42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-09",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12009,4",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-10",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11741,47",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-11",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11779,77",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-14",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11750,65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-16",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11818,11",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-16",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11806,94",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-17",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11908,67",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-17",
    botCycle: "18",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11981,99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-18",
    botCycle: "18",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11853,54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-21",
    botCycle: "19",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11715,6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-21",
    botCycle: "19",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11684,98",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-23",
    botCycle: "20",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11586,41",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-25",
    botCycle: "20",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11379,63",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-28",
    botCycle: "21",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11406,01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-02",
    botCycle: "21",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10373,45",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-08",
    botCycle: "22",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9981,74",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-08",
    botCycle: "22",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10221,47",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-09",
    botCycle: "23",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10280,15",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-13",
    botCycle: "23",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10469,92",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-14",
    botCycle: "24",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10866,55",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-18",
    botCycle: "24",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10975,99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-19",
    botCycle: "25",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10962,6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-20",
    botCycle: "25",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10545,07",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-24",
    botCycle: "26",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10623,62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-27",
    botCycle: "26",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10732,01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-27",
    botCycle: "27",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10689,94",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-29",
    botCycle: "27",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10840,58",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-30",
    botCycle: "28",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10706,56",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-30",
    botCycle: "28",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10798,38",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "29",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10617,74",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "29",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10612,83",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-04",
    botCycle: "30",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10571,35",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-06",
    botCycle: "30",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10896,96",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08",
    botCycle: "31",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11244,41",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-12",
    botCycle: "31",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11549,39",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-12",
    botCycle: "32",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11387,83",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-13",
    botCycle: "32",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11520,93",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-15",
    botCycle: "33",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11369,27",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-16",
    botCycle: "33",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11455,4",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-18",
    botCycle: "34",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12951,73",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-25",
    botCycle: "34",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13029,64",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-26",
    botCycle: "35",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13004,49",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-26",
    botCycle: "35",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13020",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-27",
    botCycle: "36",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13162",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28",
    botCycle: "36",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13491",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-29",
    botCycle: "37",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13220",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-30",
    botCycle: "37",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13549",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-30",
    botCycle: "38",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13404",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-02",
    botCycle: "38",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13723",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-03",
    botCycle: "39",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "14634",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "39",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15333",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-08",
    botCycle: "40",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15360",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-09",
    botCycle: "40",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15406",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "41",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15960",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-14",
    botCycle: "41",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "16225",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-16",
    botCycle: "42",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18297",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-22",
    botCycle: "42",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19067,79",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-24",
    botCycle: "43",
  },
  {
    botId: undefined,
    botRef: "OPTIMUSBTC",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17607,76",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "43",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27398,95",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-30",
    botCycle: "1",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30774,68",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "1",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33608,62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-05",
    botCycle: "2",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39151,48",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "2",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34317,11",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-13",
    botCycle: "3",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35609,05",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "3",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36462,57",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-18",
    botCycle: "4",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35926,9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "4",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32011,51",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "5",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31255,88",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "5",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33554,26",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "6",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31518,95",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "6",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31906,62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-28",
    botCycle: "7",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "33578,49",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "7",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39404,23",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "8",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "45160,02",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-01",
    botCycle: "8",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34172,72",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "9",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37923,08",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "9",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "47897,43",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-11",
    botCycle: "10",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "46758,56",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "10",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "47942,37",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "11",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "56400,99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "11",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "46212,42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "12",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "49419,87",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "12",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "48845,62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-07",
    botCycle: "13",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57779,33",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "13",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57877,65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "14",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57762,79",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "14",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "53750,7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-26",
    botCycle: "15",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "58912,93",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "15",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "58947",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "16",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "58202,47",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "16",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57714,06",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-08",
    botCycle: "17",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "60088,17",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "17",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "60498,64",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "18",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "62392,27",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "18",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "52377,85",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "19",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "54489,98",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "19",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57646,35",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "20",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "55780,46",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "20",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57615,76",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "21",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57462,85",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "21",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57768,7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "22",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "56422,82",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "22",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36770,66",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "23",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35928,73",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "23",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34990,78",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "24",
  },
  {
    botRef: "OPTIMUSBTC",
    botVer: "2",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35551,52",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "24",
  },
];
