/* eslint-disable import/prefer-default-export */
export const pgbat = [
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.2557",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-02",
    botCycle: "1",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.2956",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "1",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.2393",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "2",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.1897",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "2",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.1806",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "3",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.3577",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "3",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.3738",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "4",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.5799",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "4",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.4141",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "5",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.3575",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "5",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.3763",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "6",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.4754",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "6",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.305",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "7",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.2528",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "7",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.151",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "8",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.2214",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "8",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.1307",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "9",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0854",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "9",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.0908",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "10",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0471",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "10",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.0631",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "11",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0205",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "11",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.979",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "12",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.940",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "12",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.792",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "13",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.911",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "13",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.736",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "14",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.707",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "14",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.690",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "15",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.662",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "15",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.499",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "16",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.574",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "16",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.698",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "17",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.803",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "17",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.745",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "18",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.716",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "18",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.728",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "19",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.699",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "19",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.654",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "20",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.752",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "20",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.741",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "21",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.768",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "21",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.758",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "22",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.727",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "22",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.637",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "23",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.695",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "23",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.611",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "24",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.646",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "24",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.680",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "25",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.652",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "25",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.651",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "26",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.625",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "26",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.603",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "27",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.579",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "27",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.571",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "28",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.549",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "28",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.532",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "29",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.510",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "29",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.473",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "30",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.544",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "30",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.536",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "31",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.571",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "31",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.549",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "32",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.527",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "32",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.526",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "33",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.505",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "33",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.503",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "34",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.579",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "34",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.577",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "35",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.604",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "35",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.559",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "36",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.592",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-03",
    botCycle: "36",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.577",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "37",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.587",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-06",
    botCycle: "37",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.554",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "38",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.531",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "38",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.533",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "39",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.512",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "39",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.507",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "40",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.583",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-17",
    botCycle: "40",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.537",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-17",
    botCycle: "41",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.516",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-18",
    botCycle: "41",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.525",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-18",
    botCycle: "42",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.504",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "42",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.499",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "43",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.479",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "43",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.466",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "44",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.536",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-24",
    botCycle: "44",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.529",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "45",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.575",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "45",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.542",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "46",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.608",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "46",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.579",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "47",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.666",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-01",
    botCycle: "47",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.651",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "48",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.625",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "48",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.663",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-05",
    botCycle: "49",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.698",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-06",
    botCycle: "49",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.681",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "50",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.654",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "50",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.661",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "51",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.761",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-11",
    botCycle: "51",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.731",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "52",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.702",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "52",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.708",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "53",
  },
  {
    botRef: "PGBAT",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.759",
    sbl: "BATUSDT",
    base: "BAT",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "53",
  },
];
