/* eslint-disable import/prefer-default-export */
export const pgbnb = [
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "386.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "1",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "424.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "1",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "333.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "2",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "367.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "2",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "366.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "3",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "348.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "3",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "350.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "4",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "333.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "4",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "336.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "5",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "319.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "5",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "284.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "6",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "270",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "6",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "271.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "7",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "282.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "7",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "300.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "8",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "314.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-06",
    botCycle: "8",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "314.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-08",
    botCycle: "9",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "322.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "9",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "315.6",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "10",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "299.801",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "10",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "301.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-17",
    botCycle: "11",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "305.1",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-18",
    botCycle: "11",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "300.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "12",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "285.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "12",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "299.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "13",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "316.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "13",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "336.1",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "14",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "319.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "14",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "323.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "15",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "322.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "15",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "382.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "16",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "401",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "16",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "406",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "17",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "385.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "17",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "399.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "18",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "439.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-20",
    botCycle: "18",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "452.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-22",
    botCycle: "19",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "498.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-23",
    botCycle: "19",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "479.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "20",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "482.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "20",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "484.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-26",
    botCycle: "21",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "459.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-31",
    botCycle: "21",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "463.6",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-31",
    botCycle: "22",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "490.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-02",
    botCycle: "22",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "410.701",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-17",
    botCycle: "23",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "416.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-18",
    botCycle: "23",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "410.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "24",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "390.1",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-20",
    botCycle: "24",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "349.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "25",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "331.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-26",
    botCycle: "25",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "340",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-28",
    botCycle: "26",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "374",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-29",
    botCycle: "26",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "426.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-03",
    botCycle: "27",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "439.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-05",
    botCycle: "27",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "435.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-08",
    botCycle: "28",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "414",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-10",
    botCycle: "28",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "421.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-12",
    botCycle: "29",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "463.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-13",
    botCycle: "29",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "466.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-15",
    botCycle: "30",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "443.1",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-16",
    botCycle: "30",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "466.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "31",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "466.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "31",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "484.101",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-20",
    botCycle: "32",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "500.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-21",
    botCycle: "32",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "476.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-21",
    botCycle: "33",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "484.1",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-22",
    botCycle: "33",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "485.1",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-26",
    botCycle: "34",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "460.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-27",
    botCycle: "34",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "455.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-27",
    botCycle: "35",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "501.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-29",
    botCycle: "35",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "523.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-31",
    botCycle: "36",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "558.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-02",
    botCycle: "36",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "566.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-04",
    botCycle: "37",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "623.6",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-06",
    botCycle: "37",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "642.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-08",
    botCycle: "38",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "646.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-10",
    botCycle: "38",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "619.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-12",
    botCycle: "39",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "650.6",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-14",
    botCycle: "39",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "643.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-14",
    botCycle: "40",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "645.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-15",
    botCycle: "40",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "590",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-16",
    botCycle: "41",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "560.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-17",
    botCycle: "41",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "579.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-17",
    botCycle: "42",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "550.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-18",
    botCycle: "42",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "541.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-19",
    botCycle: "43",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "595.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-20",
    botCycle: "43",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "571.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-22",
    botCycle: "44",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "628.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-25",
    botCycle: "44",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "635.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-26",
    botCycle: "45",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "603.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-26",
    botCycle: "45",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "586.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-26",
    botCycle: "46",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "600.3",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-27",
    botCycle: "46",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "595.9",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-28",
    botCycle: "47",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "623",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "47",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "621.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "48",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "590.6",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-03",
    botCycle: "48",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "544.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-04",
    botCycle: "49",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "598.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-08",
    botCycle: "49",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "579.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-09",
    botCycle: "50",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "550.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-11",
    botCycle: "50",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "525.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-14",
    botCycle: "51",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "533.7",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-19",
    botCycle: "51",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "534.2",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-20",
    botCycle: "52",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "507.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-20",
    botCycle: "52",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "515.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-20",
    botCycle: "53",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "533.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-22",
    botCycle: "53",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "544.5",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-25",
    botCycle: "54",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "560.6",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-28",
    botCycle: "54",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "535.6",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-29",
    botCycle: "55",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "508.8",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-30",
    botCycle: "55",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "515.4",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-30",
    botCycle: "56",
  },
  {
    botRef: "PGBNB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "523.1",
    sbl: "BNBUSDT",
    base: "BNB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-02",
    botCycle: "56",
  },
];
