/* eslint-disable import/prefer-default-export */
export const pgbtc = [
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29218",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-02",
    botCycle: "1",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "33601",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-03",
    botCycle: "1",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31771",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11",
    botCycle: "2",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36537",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "2",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "35680",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "3",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34252",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "3",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30734",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "4",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35345",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "4",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33984",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "5",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32624",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "5",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32895",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "6",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34857",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-02",
    botCycle: "6",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39030",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "7",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37468",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "7",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "38479",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "8",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "44251",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "8",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "44895",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "9",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "51630",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-17",
    botCycle: "9",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "48587",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "10",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "46643",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "10",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "47150",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-05",
    botCycle: "11",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "50651",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-07",
    botCycle: "11",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "53930.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "12",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "59700.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "12",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56510.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "13",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "54249.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-16",
    botCycle: "13",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "55054.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-16",
    botCycle: "14",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "59280.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-20",
    botCycle: "14",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "55501.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "15",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "59550.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-02",
    botCycle: "15",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57544.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "16",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "60610.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "16",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "61344.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "17",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "58890.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "17",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "50204.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-24",
    botCycle: "18",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "48195.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-25",
    botCycle: "18",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "54798.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "19",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "52606.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "19",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "53132.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "20",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57012.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "20",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "54609.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "21",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57126.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "21",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39601.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "22",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "38016.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "22",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "37033.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "23",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37274.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "23",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36800.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "24",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37603.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "24",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36288.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "25",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34836.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "25",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "35441.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "26",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "40758.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "26",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "40062.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "27",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "38459.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "27",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "37978.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "28",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36458.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "28",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "35816.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "29",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34383.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "29",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31266.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "30",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34394.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "30",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33583.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "31",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35488.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "31",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34098.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "32",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34205.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-06",
    botCycle: "32",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32334.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "33",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32691.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "33",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31880.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "34",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30604.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "34",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29744.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "35",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32152.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-22",
    botCycle: "35",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39006.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "36",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37445.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-05",
    botCycle: "36",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39013.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-05",
    botCycle: "37",
  },
  {
    botRef: "PGBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "42551.000",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-06",
    botCycle: "37",
  },
];
