/* eslint-disable import/prefer-default-export */
export const pgdoge = [
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0047",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-01",
    botCycle: "1",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0104",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "1",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0095",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "2",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0092",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-05",
    botCycle: "2",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009701",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-05",
    botCycle: "3",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0094",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-05",
    botCycle: "3",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0095",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-05",
    botCycle: "4",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0096",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-05",
    botCycle: "4",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0101",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "5",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0097",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "5",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.010101",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "6",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0097",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "6",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0104",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "7",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0102",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-07",
    botCycle: "7",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0096001",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-08",
    botCycle: "8",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0093001",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-08",
    botCycle: "8",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.01",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-09",
    botCycle: "9",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0097",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "9",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00870001",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "10",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.008300001",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "10",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0085",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "11",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0082",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "11",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.008",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-13",
    botCycle: "12",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.01",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "12",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "13",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "13",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "14",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "14",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "15",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "15",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "16",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "16",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "17",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-18",
    botCycle: "17",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "18",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "18",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "19",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-21",
    botCycle: "19",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.008",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-22",
    botCycle: "20",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-23",
    botCycle: "20",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-23",
    botCycle: "21",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "21",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "22",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.009",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "22",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.008",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "23",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.008",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "23",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.008",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-28",
    botCycle: "24",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.054",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "24",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.028",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "25",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.039",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-01",
    botCycle: "25",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.038",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-01",
    botCycle: "26",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.037",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-01",
    botCycle: "26",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.033",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-03",
    botCycle: "27",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.032",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-03",
    botCycle: "27",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.05",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "28",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.049",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "28",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.046",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "29",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.049",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "29",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.045",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "30",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.079",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-09",
    botCycle: "30",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.071",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "31",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.068",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "31",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.073",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "32",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.071",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-11",
    botCycle: "32",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.067",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-12",
    botCycle: "33",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.068",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "33",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.059",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "34",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.058",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "34",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.058",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "35",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.056",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "35",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.053",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-17",
    botCycle: "36",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-17",
    botCycle: "36",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-18",
    botCycle: "37",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.052",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-18",
    botCycle: "37",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.057",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-19",
    botCycle: "38",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.055",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-19",
    botCycle: "38",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.056",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-20",
    botCycle: "39",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.057",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-20",
    botCycle: "39",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.055",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "40",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.055",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "40",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.055",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "41",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.053",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "41",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.053",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "42",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "42",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.053",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-24",
    botCycle: "43",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.056",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-25",
    botCycle: "43",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "44",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "44",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.049",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "45",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.05",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "45",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.05",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "46",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "46",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "47",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.05",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "47",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "48",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "48",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.051",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-07",
    botCycle: "49",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.057",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "49",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.057",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "50",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.055",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "50",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.056",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "51",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.055",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "51",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.062",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "52",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "52",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.062",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "53",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "53",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.057",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "54",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.058",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "54",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.059",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "55",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.058",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "55",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.058",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "56",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.058",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "56",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.058",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-20",
    botCycle: "57",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.057",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "57",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.058",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "58",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.056",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "58",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.055",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "59",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.053",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "59",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.052",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-26",
    botCycle: "60",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.055",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-28",
    botCycle: "60",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.054",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "61",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.054",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "61",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.055",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-30",
    botCycle: "62",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.054",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-30",
    botCycle: "62",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.053",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "63",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.054",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-01",
    botCycle: "63",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.054",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-01",
    botCycle: "64",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.059",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-01",
    botCycle: "64",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.059",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-02",
    botCycle: "65",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-02",
    botCycle: "65",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.057",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "66",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.058",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "66",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.06",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-08",
    botCycle: "67",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.062",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "67",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.061",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "68",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.07",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "68",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.074",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "69",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.127",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "69",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.129",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "70",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.274",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "70",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.295",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "71",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.286",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "71",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.3",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "72",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.391",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-19",
    botCycle: "72",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.385",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-20",
    botCycle: "73",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.374",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-20",
    botCycle: "73",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.308",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "74",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.299",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "74",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.23",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-23",
    botCycle: "75",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.272",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-25",
    botCycle: "75",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.268",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "76",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.26",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "76",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.264",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "77",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.267",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-27",
    botCycle: "77",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.266",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-27",
    botCycle: "78",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.272",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "78",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.306",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "79",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.31",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "79",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.312",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "80",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.38",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-02",
    botCycle: "80",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.384",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-02",
    botCycle: "81",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.372",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "81",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.383",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "82",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.627",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "82",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.617",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "83",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.598",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "83",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.617",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "84",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.673",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "84",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.548",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "85",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.531",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "85",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.521",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "86",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.505",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "86",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.485",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "87",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.471",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "87",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.535",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "88",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.518",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "88",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.534",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "89",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.518",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "89",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.495",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "90",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.48",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "90",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.358",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "91",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.347",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "91",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.412",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "92",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.399",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "92",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.34",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "93",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.344",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "93",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.35",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "94",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.34",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "94",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.308",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "95",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.299",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "95",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.312",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "96",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.349",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "96",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.344",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "97",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.342",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "97",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.341",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "98",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.331",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "98",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.315",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "99",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.305",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "99",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.297",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "100",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.304",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "100",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.305",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "101",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.296",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "101",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.313",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "102",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.424",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "102",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.417",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "103",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.404",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "103",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.386",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "104",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.375",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "104",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.372",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "105",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.369",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "105",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.373",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "106",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.361",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "106",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.32",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "107",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.323",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "107",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.325",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "108",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.329",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "108",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.323",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "109",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.313",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "109",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.313",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "110",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.311",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "110",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.324",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "111",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.326",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "111",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.311",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "112",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.307",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "112",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.289",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "113",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.291",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "113",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.191",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "114",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.185",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "114",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.195",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "115",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.189",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "115",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.187",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "116",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.182",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "116",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.201",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "117",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.236",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "117",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.244",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "118",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.253",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "118",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.24",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "119",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.246",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "119",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.245",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "120",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.257",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "120",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.267",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "121",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.259",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "121",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.254",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "122",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.246",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "122",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.247",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "123",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.241",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "123",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.242",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "124",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.245",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "124",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.248",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "125",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.249",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "125",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.249",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "126",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.242",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "126",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.233",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-06",
    botCycle: "127",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.231",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "127",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.216",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "128",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.219",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-10",
    botCycle: "128",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.212",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-11",
    botCycle: "129",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.213",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-11",
    botCycle: "129",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.214",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-11",
    botCycle: "130",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.208",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "130",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "131",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.197",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-15",
    botCycle: "131",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.171",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-17",
    botCycle: "132",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.19",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-18",
    botCycle: "132",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.171",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-21",
    botCycle: "133",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.191",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-22",
    botCycle: "133",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.189",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-22",
    botCycle: "134",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.191",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-23",
    botCycle: "134",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.193",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-24",
    botCycle: "135",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.194",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "135",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.222",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "136",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.215",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "136",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.204",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "137",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.198",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "137",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.207",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-28",
    botCycle: "138",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.202",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-28",
    botCycle: "138",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.204",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-29",
    botCycle: "139",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.203",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-29",
    botCycle: "139",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.207",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "140",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.2",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "140",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.206",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-31",
    botCycle: "141",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.207",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-31",
    botCycle: "141",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.207",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-31",
    botCycle: "142",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.21",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-01",
    botCycle: "142",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.206",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "143",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.205",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "143",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.197",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "144",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.199",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-05",
    botCycle: "144",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.2",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-06",
    botCycle: "145",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.244",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "145",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.252",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "146",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.264",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "146",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.274",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "147",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.283",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-14",
    botCycle: "147",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.289",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-14",
    botCycle: "148",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.328",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "148",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.327",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "149",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.317",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "149",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.299",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-19",
    botCycle: "150",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.298",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-19",
    botCycle: "150",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.318",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-20",
    botCycle: "151",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.321",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "151",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.328",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "152",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.317",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "152",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.289",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "153",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.293",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "153",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.293",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-26",
    botCycle: "154",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.284",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-26",
    botCycle: "154",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.269",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-27",
    botCycle: "155",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.289",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-28",
    botCycle: "155",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.284",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "156",
  },
  {
    botRef: "PGDOGE",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.281",
    sbl: "DOGEUSDT",
    base: "DOGE",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "156",
  },
];
