/* eslint-disable import/prefer-default-export */
export const pgeth = [
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1174.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-08",
    botCycle: "1",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1316.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "1",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1134.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11",
    botCycle: "2",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1089.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11",
    botCycle: "2",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "975.91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-11",
    botCycle: "3",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1141.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "3",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1049.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-13",
    botCycle: "4",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1228.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-14",
    botCycle: "4",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1202.45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "5",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1406.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "5",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1319.26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "6",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1266.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "6",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1230.94",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-21",
    botCycle: "7",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1181.7",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-21",
    botCycle: "7",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1366.52",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "8",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1311.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "8",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1308.45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "9",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1256.11",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "9",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1310.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "10",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1371.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-02",
    botCycle: "10",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1581.55",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "11",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1850.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-12",
    botCycle: "11",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1737.690",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "12",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1896.050",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-18",
    botCycle: "12",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1943.870",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "13",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1866.110",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "13",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1887.120",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "14",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1811.630",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "14",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1538.880",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "15",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1477.320",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "15",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1504.690",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "16",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1444.500",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "16",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1476.460",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "17",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1417.400",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "17",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1363.150",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-28",
    botCycle: "18",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1308.620",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-28",
    botCycle: "18",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1487.150",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "19",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1739.970",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "19",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1771.120",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-11",
    botCycle: "20",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1823.170",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "20",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1784.650",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "21",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1713.260",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "21",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1700.810",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-23",
    botCycle: "22",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1632.770",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-24",
    botCycle: "22",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1573.540",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-25",
    botCycle: "23",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1841.050",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "23",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1815.480",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "24",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1994.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-02",
    botCycle: "24",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2058.190",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "25",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1975.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "25",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2013.450",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "26",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1932.910",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "26",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2139.630",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "27",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2503.370",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "27",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2406.770",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "28",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2310.490",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "28",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2209.730",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "29",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2121.340",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "29",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2258.560",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-23",
    botCycle: "30",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2168.210",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-24",
    botCycle: "30",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2250.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-24",
    botCycle: "31",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2633.510",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-27",
    botCycle: "31",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3439.800",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "32",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3835.400",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "32",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3922.030",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "33",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3765.140",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "33",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3715.300",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "34",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3566.680",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "34",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3531.870",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "35",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3390.590",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "35",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2742.240",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "36",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2632.550",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "36",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2603.260",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "37",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2499.120",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "37",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2428.220",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "38",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2331.090",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "38",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1967.440",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "39",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2301.910",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "39",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2563.150",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "40",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2460.620",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "40",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2261.090",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "41",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2645.480",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "41",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2578.240",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "42",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2704.440",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "42",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2515.750",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "43",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2415.120",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "43",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2312.830",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "44",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2499.270",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "44",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2531.420",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "45",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2430.160",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "45",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2418.870",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "46",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2322.110",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "46",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2346.920",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "47",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2253.040",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "47",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2221.730",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "48",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2132.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "48",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2123.350",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "49",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2038.410",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "49",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2011.800",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "50",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1931.320",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "50",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1839.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "51",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1765.440",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "51",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1783.200",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "52",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2086.350",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "52",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2036.980",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "53",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1955.500",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "53",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1937.310",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "54",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1859.810",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "54",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1908.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "55",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1969.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-18",
    botCycle: "55",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1823.470",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "56",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1750.530",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "56",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1757.940",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "57",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2056.790",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-23",
    botCycle: "57",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2151.270",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "58",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2343.400",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "58",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2511.470",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "59",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2938.420",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-06",
    botCycle: "59",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3037.350",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "60",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2915.850",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "60",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2954.200",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "61",
  },
  {
    botRef: "PGETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3234.570",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "61",
  },
];
