/* eslint-disable import/prefer-default-export */
export const pgmatic = [
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.808",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "1",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.699",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "1",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.612",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "2",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.637",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "2",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.538",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "3",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.574",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "3",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.674",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "4",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.664",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "4",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.461",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "5",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.46801",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "5",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.379",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "6",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.366",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "6",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.512",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "7",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.69401",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "7",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.386",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "8",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.373",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "8",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.189",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "9",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.11701",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "9",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.143",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "10",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.168",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "10",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.103",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "11",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.132",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "11",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.14501",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "12",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.076",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "12",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.077",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "13",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.121",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "13",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.154",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "14",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.084",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "14",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.127",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-06",
    botCycle: "15",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.151",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "15",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.039",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "16",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.046",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-10",
    botCycle: "16",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.042",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-10",
    botCycle: "17",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.043",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "17",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.874",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "18",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.821",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "18",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.696",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "19",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.78",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-21",
    botCycle: "19",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.897",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-22",
    botCycle: "20",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.923",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-24",
    botCycle: "20",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.936",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "21",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.04901",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "21",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.081",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "22",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.016",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "22",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.052",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-31",
    botCycle: "23",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.049",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "23",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.023",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "24",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.022",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "24",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.054",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-06",
    botCycle: "25",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.085",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "25",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.119",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "26",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.145",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "26",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.142",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "27",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.073",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "27",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.363",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-11",
    botCycle: "28",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.38",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "28",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.312",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "29",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.47",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "29",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.459",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "30",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.48",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-14",
    botCycle: "30",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.442",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "31",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.35501",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "31",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.353",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "32",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.324",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-19",
    botCycle: "32",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.322",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-19",
    botCycle: "33",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.48101",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-20",
    botCycle: "33",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.51",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-20",
    botCycle: "34",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.519",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "34",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.634",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-23",
    botCycle: "35",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.53501",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-24",
    botCycle: "35",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.497",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "36",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.532",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-26",
    botCycle: "36",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.507",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-27",
    botCycle: "37",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.468",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-28",
    botCycle: "37",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.34301",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-01",
    botCycle: "38",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.467",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-02",
    botCycle: "38",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.47401",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-03",
    botCycle: "39",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.651",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-04",
    botCycle: "39",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.63901",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-04",
    botCycle: "40",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.639001",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "40",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.33",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "41",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.351",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "41",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.347",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "42",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.26601",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "42",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.301",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "43",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.458",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-10",
    botCycle: "43",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.315",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-11",
    botCycle: "44",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.328",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-12",
    botCycle: "44",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.346",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-12",
    botCycle: "45",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.265",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-12",
    botCycle: "45",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.258",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-14",
    botCycle: "46",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.409",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-16",
    botCycle: "46",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.474",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-16",
    botCycle: "47",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.385",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-16",
    botCycle: "47",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.393",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-18",
    botCycle: "48",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.357",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "48",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.355",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "49",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.356",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "49",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.343",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "50",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.262",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-20",
    botCycle: "50",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.207001",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-23",
    botCycle: "51",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.22",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-23",
    botCycle: "51",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.225",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "52",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.221",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "52",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.137",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "53",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.126",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-25",
    botCycle: "53",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.129",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-25",
    botCycle: "54",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.112",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-26",
    botCycle: "54",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.065",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-29",
    botCycle: "55",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.125",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-30",
    botCycle: "55",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.117",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-30",
    botCycle: "56",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.252",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-01",
    botCycle: "56",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.244",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-02",
    botCycle: "57",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.266",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-04",
    botCycle: "57",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.298",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-06",
    botCycle: "58",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.342",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-10",
    botCycle: "58",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.337",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-10",
    botCycle: "59",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.256",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-10",
    botCycle: "59",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.214",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-12",
    botCycle: "60",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.207",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-13",
    botCycle: "60",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.215",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-13",
    botCycle: "61",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.248",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-15",
    botCycle: "61",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.263",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-15",
    botCycle: "62",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.415",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-15",
    botCycle: "62",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.535",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-16",
    botCycle: "63",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.513",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-16",
    botCycle: "63",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.526",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-18",
    botCycle: "64",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.481",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-19",
    botCycle: "64",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.564",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-21",
    botCycle: "65",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.594",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-24",
    botCycle: "65",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.635",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-25",
    botCycle: "66",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.832",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-26",
    botCycle: "66",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.985",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-28",
    botCycle: "67",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.033",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-29",
    botCycle: "67",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.941",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-30",
    botCycle: "68",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.903",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-30",
    botCycle: "68",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.886",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-01",
    botCycle: "69",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.901",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-01",
    botCycle: "69",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.889",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-02",
    botCycle: "70",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.116",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-03",
    botCycle: "70",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.983",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-04",
    botCycle: "71",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.864",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-04",
    botCycle: "71",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.887",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-06",
    botCycle: "72",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.891",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-07",
    botCycle: "72",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.839",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-10",
    botCycle: "73",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.728",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-10",
    botCycle: "73",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.764",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-12",
    botCycle: "74",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.658",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-12",
    botCycle: "74",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.56",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-17",
    botCycle: "75",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.648",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-18",
    botCycle: "75",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.5",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-19",
    botCycle: "76",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.606",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-20",
    botCycle: "76",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.613",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-20",
    botCycle: "77",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.618",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-20",
    botCycle: "77",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.639",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-21",
    botCycle: "78",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.54",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-22",
    botCycle: "78",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.563",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-22",
    botCycle: "79",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.581",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-23",
    botCycle: "79",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.694",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-25",
    botCycle: "80",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.898",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-25",
    botCycle: "80",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.698",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-27",
    botCycle: "81",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.596",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-27",
    botCycle: "81",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.647",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-29",
    botCycle: "82",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.845",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "82",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.79",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "83",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.005",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-01",
    botCycle: "83",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.999",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-01",
    botCycle: "84",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.066001",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-02",
    botCycle: "84",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.837",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-04",
    botCycle: "85",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.058",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-05",
    botCycle: "85",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.066",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-05",
    botCycle: "86",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.942",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-05",
    botCycle: "86",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.318",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-07",
    botCycle: "87",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.409",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-08",
    botCycle: "87",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.47",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-08",
    botCycle: "88",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.321",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-09",
    botCycle: "88",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.16",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-10",
    botCycle: "89",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.216",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-10",
    botCycle: "89",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.081",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-11",
    botCycle: "90",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.062",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-12",
    botCycle: "90",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.853",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-14",
    botCycle: "91",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.006",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-15",
    botCycle: "91",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.129",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-16",
    botCycle: "92",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.147",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-16",
    botCycle: "92",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.087",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-17",
    botCycle: "93",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.217",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-19",
    botCycle: "93",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.139",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-21",
    botCycle: "94",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.396",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-21",
    botCycle: "94",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.312",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-21",
    botCycle: "95",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.59",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-22",
    botCycle: "95",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.615",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-23",
    botCycle: "96",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.544001",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-23",
    botCycle: "96",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.515",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-25",
    botCycle: "97",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.697",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-26",
    botCycle: "97",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.549",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-31",
    botCycle: "98",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.538",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-31",
    botCycle: "98",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.544",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-01",
    botCycle: "99",
  },
  {
    botRef: "PGMATIC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.529",
    sbl: "MATICUSDT",
    base: "MATIC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-03",
    botCycle: "99",
  },
];
