/* eslint-disable import/prefer-default-export */
export const pgtrx = [
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07633",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "1",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.07699",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "1",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07611",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "2",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.07662",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "2",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07053",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "3",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.07398",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "3",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07272",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "4",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06835",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "4",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.06803",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "5",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.07062",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "5",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07139",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "6",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0712",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "6",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0697",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "7",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06551",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "7",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.05525",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "8",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.05193",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "8",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0624301",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "9",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06243",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "9",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0649",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "10",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0655",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-03",
    botCycle: "10",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.06495",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "11",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06522",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "11",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0616",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-08",
    botCycle: "12",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06182",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-11",
    botCycle: "12",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.06052",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "13",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.05688",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "13",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.05866",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "14",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.05971",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-15",
    botCycle: "14",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.05814",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "15",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.05655",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-18",
    botCycle: "15",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.05571",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "16",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.05236",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "16",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.05029",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "17",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.05477",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-23",
    botCycle: "17",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.05895",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "18",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06065",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-28",
    botCycle: "18",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0607",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-29",
    botCycle: "19",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0608",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "19",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.06507",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "20",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06471",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "20",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.06393",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "21",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.06413",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "21",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07119",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "22",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.07364",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-10",
    botCycle: "22",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08369",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "23",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0871",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "23",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09087",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "24",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09208",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-16",
    botCycle: "24",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09075",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "25",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0853",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "25",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08501",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "26",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0873101",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-20",
    botCycle: "26",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08877",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-22",
    botCycle: "27",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08914",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-23",
    botCycle: "27",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08618",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "28",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08833",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-29",
    botCycle: "28",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08731",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "29",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08831",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-31",
    botCycle: "29",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10338",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-06",
    botCycle: "30",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09717",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "30",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08636",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "31",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09673",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "31",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08919",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-11",
    botCycle: "32",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0999",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-12",
    botCycle: "32",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10979",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-13",
    botCycle: "33",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1032",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-13",
    botCycle: "33",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.11597",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-15",
    botCycle: "34",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1176",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-16",
    botCycle: "34",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10513",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "35",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09882",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-20",
    botCycle: "35",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09219",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-21",
    botCycle: "36",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09377",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-21",
    botCycle: "36",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08982",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-22",
    botCycle: "37",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.1006",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-23",
    botCycle: "37",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09172",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "38",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08621",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-26",
    botCycle: "38",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08615",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-28",
    botCycle: "39",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08766",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-30",
    botCycle: "39",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09265",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-04",
    botCycle: "40",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09431",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-05",
    botCycle: "40",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10179",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-10",
    botCycle: "41",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09568",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "41",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09464",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-13",
    botCycle: "42",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.0988",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-16",
    botCycle: "42",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09893",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "43",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09999",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "43",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.0986",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-18",
    botCycle: "44",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09966",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-19",
    botCycle: "44",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10048",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-22",
    botCycle: "45",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09998",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-23",
    botCycle: "45",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10008",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-24",
    botCycle: "46",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.10081",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-25",
    botCycle: "46",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10055",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-31",
    botCycle: "47",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.10729",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-02",
    botCycle: "47",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10328",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-05",
    botCycle: "48",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.10377",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-05",
    botCycle: "48",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10345",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-06",
    botCycle: "49",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.10267",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-07",
    botCycle: "49",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10844",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-11",
    botCycle: "50",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.11253",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-14",
    botCycle: "50",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.11229",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-14",
    botCycle: "51",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.12577",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-15",
    botCycle: "51",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.1099",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-17",
    botCycle: "52",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.11127",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-17",
    botCycle: "52",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10059",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-19",
    botCycle: "53",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.10386",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-19",
    botCycle: "53",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.10361",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-22",
    botCycle: "54",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.10276",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-23",
    botCycle: "54",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09351",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-26",
    botCycle: "55",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09427",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-27",
    botCycle: "55",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09147",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-28",
    botCycle: "56",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.09601",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "56",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08364000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-04",
    botCycle: "57",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08435000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-06",
    botCycle: "57",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.09149000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-09",
    botCycle: "58",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08600000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-13",
    botCycle: "58",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08586000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-15",
    botCycle: "59",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08070000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-17",
    botCycle: "59",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07982000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-18",
    botCycle: "60",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08119000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-18",
    botCycle: "60",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07680000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-20",
    botCycle: "61",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.07842000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-21",
    botCycle: "61",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07923000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-23",
    botCycle: "62",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08188000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-24",
    botCycle: "62",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08111000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-25",
    botCycle: "63",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08153000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-25",
    botCycle: "63",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.08079000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-26",
    botCycle: "64",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.08135000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-27",
    botCycle: "64",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07907000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-28",
    botCycle: "65",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.07776000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-30",
    botCycle: "65",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.07809000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-31",
    botCycle: "66",
  },
  {
    botRef: "PGTRX",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.07644000",
    sbl: "TRXUSDT",
    base: "TRX",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-02",
    botCycle: "66",
  },
];
