/* eslint-disable import/prefer-default-export */
export const spoonereth = [
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "154.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-05",
    botCycle: "1",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "149.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-06",
    botCycle: "1",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "156.45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-06",
    botCycle: "2",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "149.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-07",
    botCycle: "2",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "124",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-14",
    botCycle: "3",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "117.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-15",
    botCycle: "3",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "121.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-19",
    botCycle: "4",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "119.13",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-20",
    botCycle: "4",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "117.92",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-21",
    botCycle: "5",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "116.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-23",
    botCycle: "5",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "107.16",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-01",
    botCycle: "6",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "107.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-03",
    botCycle: "6",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "106.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-08",
    botCycle: "7",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "116.79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-10",
    botCycle: "7",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "119.18",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-10",
    botCycle: "8",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "119.44",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-11",
    botCycle: "8",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "125.97",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-13",
    botCycle: "9",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "121.78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-13",
    botCycle: "9",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "124.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-16",
    botCycle: "10",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "125.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-17",
    botCycle: "10",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "148.26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-20",
    botCycle: "11",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "139.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-24",
    botCycle: "11",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "134.45",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-05",
    botCycle: "12",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "136.22",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-07",
    botCycle: "12",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "136.03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-15",
    botCycle: "13",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "138.4",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-17",
    botCycle: "13",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "141.35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-18",
    botCycle: "14",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "136.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-18",
    botCycle: "14",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "134.67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-27",
    botCycle: "15",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "142.03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-30",
    botCycle: "15",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "142.94",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-02",
    botCycle: "16",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "162.78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-04",
    botCycle: "16",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "177.3",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-08",
    botCycle: "17",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "171.1",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-08",
    botCycle: "17",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "165.28",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-15",
    botCycle: "18",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "159.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-15",
    botCycle: "18",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "168.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-18",
    botCycle: "19",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "169.51",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-19",
    botCycle: "19",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "175.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-20",
    botCycle: "20",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "172.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-20",
    botCycle: "20",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "173.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-23",
    botCycle: "21",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "169.15",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-24",
    botCycle: "21",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "164.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-27",
    botCycle: "22",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "157.29",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-27",
    botCycle: "22",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "158.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-30",
    botCycle: "23",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "165.43",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-04",
    botCycle: "23",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "165.22",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-06",
    botCycle: "24",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "173.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-07",
    botCycle: "24",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "178.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-11",
    botCycle: "25",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "183.67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-12",
    botCycle: "25",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "203.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-13",
    botCycle: "26",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "248.04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-16",
    botCycle: "26",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "272.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-16",
    botCycle: "27",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "236.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-17",
    botCycle: "27",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "256.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-25",
    botCycle: "28",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "261.84",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-29",
    botCycle: "28",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "275.29",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-30",
    botCycle: "29",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "272.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-30",
    botCycle: "29",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "247.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-05",
    botCycle: "30",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "238.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-06",
    botCycle: "30",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "246.44",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-07",
    botCycle: "31",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "242.56",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-08",
    botCycle: "31",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "244.36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-10",
    botCycle: "32",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "239.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-11",
    botCycle: "32",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "245.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-11",
    botCycle: "33",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "254.49",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-14",
    botCycle: "33",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "261.08",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-14",
    botCycle: "34",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "266.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-18",
    botCycle: "34",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "274.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-21",
    botCycle: "35",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "304.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-24",
    botCycle: "35",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "320.54",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-26",
    botCycle: "36",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "330.8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-27",
    botCycle: "36",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "313.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-29",
    botCycle: "37",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "304.65",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-30",
    botCycle: "37",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "296.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-03",
    botCycle: "38",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "282.86",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-05",
    botCycle: "38",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "295.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-06",
    botCycle: "39",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "287.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-07",
    botCycle: "39",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "296.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-07",
    botCycle: "40",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "307.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-09",
    botCycle: "40",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "234.39",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-20",
    botCycle: "41",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "225.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-21",
    botCycle: "41",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "218.8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-25",
    botCycle: "42",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "214.49",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-26",
    botCycle: "42",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "219.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-02",
    botCycle: "43",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "216.62",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-02",
    botCycle: "43",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "220.4",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-03",
    botCycle: "44",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "217.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-04",
    botCycle: "44",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "223.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-05",
    botCycle: "45",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "228.65",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-06",
    botCycle: "45",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "213.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-11",
    botCycle: "46",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "207.13",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-13",
    botCycle: "46",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "192.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-26",
    botCycle: "47",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "186.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-26",
    botCycle: "47",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "174.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-02",
    botCycle: "48",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "171.36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-05",
    botCycle: "48",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "175.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-06",
    botCycle: "49",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "171.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-06",
    botCycle: "49",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "177.67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-07",
    botCycle: "50",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "189.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-16",
    botCycle: "50",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "195.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-16",
    botCycle: "51",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "206.16",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-19",
    botCycle: "51",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "216.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-19",
    botCycle: "52",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "211.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-22",
    botCycle: "52",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "170.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-27",
    botCycle: "53",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "170.56",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-28",
    botCycle: "53",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "175.16",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-28",
    botCycle: "54",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "165.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-29",
    botCycle: "54",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "175",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-30",
    botCycle: "55",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "175.75",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-03",
    botCycle: "55",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "176.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-07",
    botCycle: "56",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "188.55",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-11",
    botCycle: "56",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "184.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-13",
    botCycle: "57",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "180.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-13",
    botCycle: "57",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "184.7",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-14",
    botCycle: "58",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "183.54",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-15",
    botCycle: "58",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "167.49",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-25",
    botCycle: "59",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "179.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-26",
    botCycle: "59",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "185.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-02",
    botCycle: "60",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "181.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-03",
    botCycle: "60",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "184.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-04",
    botCycle: "61",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "188.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-07",
    botCycle: "61",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "188.15",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-10",
    botCycle: "62",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "186.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-11",
    botCycle: "62",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "187.27",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-12",
    botCycle: "63",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "185.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-14",
    botCycle: "63",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "185.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-15",
    botCycle: "64",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "179.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-15",
    botCycle: "64",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "151.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-25",
    botCycle: "65",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "142.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-27",
    botCycle: "65",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "148.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-27",
    botCycle: "66",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "150.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-29",
    botCycle: "66",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "154.25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-29",
    botCycle: "67",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "151.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-30",
    botCycle: "67",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "152.2",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-01",
    botCycle: "68",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "148",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-02",
    botCycle: "68",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "148.8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-04",
    botCycle: "69",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "145.94",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-04",
    botCycle: "69",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "149.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-06",
    botCycle: "70",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "148.03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-09",
    botCycle: "70",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "132.35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-18",
    botCycle: "71",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "129.33",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-23",
    botCycle: "71",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "129.56",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-26",
    botCycle: "72",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "126.27",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-26",
    botCycle: "72",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "131.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-29",
    botCycle: "73",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "132.78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-30",
    botCycle: "73",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "130.22",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-03",
    botCycle: "74",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "135.03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-06",
    botCycle: "74",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "138.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-06",
    botCycle: "75",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "140.93",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-07",
    botCycle: "75",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "143.67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-07",
    botCycle: "76",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "138.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-08",
    botCycle: "76",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "143.67001",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-10",
    botCycle: "77",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "142.4",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-12",
    botCycle: "77",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "146.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-14",
    botCycle: "78",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "166.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-19",
    botCycle: "78",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "169.12",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-21",
    botCycle: "79",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "166.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-22",
    botCycle: "79",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "164.17",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-26",
    botCycle: "80",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "172.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-30",
    botCycle: "80",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "177.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-30",
    botCycle: "81",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "185.65",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-04",
    botCycle: "81",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "191.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-05",
    botCycle: "82",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "216.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-08",
    botCycle: "82",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "224.51",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-08",
    botCycle: "83",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "220.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-10",
    botCycle: "83",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "229.2",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-11",
    botCycle: "84",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "274.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-15",
    botCycle: "84",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "273.29",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-18",
    botCycle: "85",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "262.93",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-19",
    botCycle: "85",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "227.23",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-02",
    botCycle: "86",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "221.86",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-03",
    botCycle: "86",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "231.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-05",
    botCycle: "87",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "238.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-07",
    botCycle: "87",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "129.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-15",
    botCycle: "88",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "116.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-16",
    botCycle: "88",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "119.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-19",
    botCycle: "89",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "130.7",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-20",
    botCycle: "89",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "136.8301",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-23",
    botCycle: "90",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "134.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-25",
    botCycle: "90",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "130.08",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-30",
    botCycle: "91",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "129.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-01",
    botCycle: "91",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "133.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-02",
    botCycle: "92",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "163.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-07",
    botCycle: "92",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "157.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-16",
    botCycle: "93",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "180.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-19",
    botCycle: "93",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "186.17",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-23",
    botCycle: "94",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "178.79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-23",
    botCycle: "94",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "186.53",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-23",
    botCycle: "95",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "191.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-27",
    botCycle: "95",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "198.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-29",
    botCycle: "96",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "206.23",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-30",
    botCycle: "96",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "211.3",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-05",
    botCycle: "97",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "198.92",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-07",
    botCycle: "97",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "210.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-07",
    botCycle: "98",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "192.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-10",
    botCycle: "98",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "192.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-11",
    botCycle: "99",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "194.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-15",
    botCycle: "99",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "201.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-16",
    botCycle: "100",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "210.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-19",
    botCycle: "100",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "215.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-19",
    botCycle: "101",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "207.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-20",
    botCycle: "101",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "204.89",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-27",
    botCycle: "102",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "234.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-02",
    botCycle: "102",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "246.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-05",
    botCycle: "103",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "238.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-07",
    botCycle: "103",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "243.84",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-08",
    botCycle: "104",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "243.78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-11",
    botCycle: "104",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "236.91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-17",
    botCycle: "105",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "231.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-17",
    botCycle: "105",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "230.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-21",
    botCycle: "106",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "242.4",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-24",
    botCycle: "106",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "231.3",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-01",
    botCycle: "107",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "228.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-02",
    botCycle: "107",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "229.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-06",
    botCycle: "108",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "237.27",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-07",
    botCycle: "108",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "243.51",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-08",
    botCycle: "109",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "242.3",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-09",
    botCycle: "109",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "242.08",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-12",
    botCycle: "110",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "237.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-12",
    botCycle: "110",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "241.35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-13",
    botCycle: "111",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "238.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-13",
    botCycle: "111",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "236.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-20",
    botCycle: "112",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "235.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-20",
    botCycle: "112",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "238.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-21",
    botCycle: "113",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "313.16",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-27",
    botCycle: "113",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "328.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-28",
    botCycle: "114",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "315.79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-30",
    botCycle: "114",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "323.27",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-30",
    botCycle: "115",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "372.37",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-02",
    botCycle: "115",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "406.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-05",
    botCycle: "116",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "384.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-07",
    botCycle: "116",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "397.17",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-09",
    botCycle: "117",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "385.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-09",
    botCycle: "117",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "395.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-13",
    botCycle: "118",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "417.84",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-16",
    botCycle: "118",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "438.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-17",
    botCycle: "119",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "420.13",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-18",
    botCycle: "119",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "395.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-28",
    botCycle: "120",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "466.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-02",
    botCycle: "120",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "355.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-09",
    botCycle: "121",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "357.03",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-11",
    botCycle: "121",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "371.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-11",
    botCycle: "122",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "372.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-13",
    botCycle: "122",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "389.97",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-17",
    botCycle: "123",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "376.91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-18",
    botCycle: "123",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "388.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-19",
    botCycle: "124",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "372.29",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-20",
    botCycle: "124",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "343.14",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-24",
    botCycle: "125",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "353.22",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-27",
    botCycle: "125",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "355.56",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-27",
    botCycle: "126",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "353.91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-29",
    botCycle: "126",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "367.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "127",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "361.11",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "127",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "350.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-04",
    botCycle: "128",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "346.12",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-06",
    botCycle: "128",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "342.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08",
    botCycle: "129",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "367.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-12",
    botCycle: "129",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "386.29",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-14",
    botCycle: "130",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "375.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-14",
    botCycle: "130",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "380.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-15",
    botCycle: "131",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "368.97",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-16",
    botCycle: "131",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "379.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-19",
    botCycle: "132",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "374.49",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-20",
    botCycle: "132",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "380.48",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-21",
    botCycle: "133",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "405.71",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-23",
    botCycle: "133",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "407.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-27",
    botCycle: "134",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "396.91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28",
    botCycle: "134",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "392.09",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-29",
    botCycle: "135",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "378.18",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-30",
    botCycle: "135",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "391.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-31",
    botCycle: "136",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "384.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-02",
    botCycle: "136",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "388.39",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-03",
    botCycle: "137",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "378.25",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "137",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "389.71",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "138",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "446.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "138",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "458.35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "139",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "458.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-12",
    botCycle: "139",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "468.71",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-13",
    botCycle: "140",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "462.95",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-14",
    botCycle: "140",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "462.5",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-16",
    botCycle: "141",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "470.15",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-18",
    botCycle: "141",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "480.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-20",
    botCycle: "142",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "584.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-25",
    botCycle: "142",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "529.96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-28",
    botCycle: "143",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "576.72",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "143",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "616.05",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "144",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "594.2",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "144",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "603.3",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-07",
    botCycle: "145",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "573.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-08",
    botCycle: "145",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "568.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-12",
    botCycle: "146",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "582.86",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-15",
    botCycle: "146",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "587.78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-15",
    botCycle: "147",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "639.62",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-18",
    botCycle: "147",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "620.89",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-25",
    botCycle: "148",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "700",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-29",
    botCycle: "148",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "746.98",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-30",
    botCycle: "149",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "969.94",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "149",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1154.54",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "150",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1183.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-08",
    botCycle: "150",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1273.2",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-08",
    botCycle: "151",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1259.28",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "151",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1145.92",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "152",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1025.71",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "152",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1123.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-13",
    botCycle: "153",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1141.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "153",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1244.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "154",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1265.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "154",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1386.36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "155",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1327.87",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "155",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1371.68",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "156",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1311.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "156",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1369.67",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-02",
    botCycle: "157",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1591.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "157",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1690.28",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "158",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1660.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-06",
    botCycle: "158",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1653.61",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "159",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1745.35",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "159",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1833.04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-12",
    botCycle: "160",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1796.63",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "160",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1831.3",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "161",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1894.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "161",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1520.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "162",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1497.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "162",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1589.89",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "163",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1507.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "163",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1595.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "164",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1795.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "164",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1843.43",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "165",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1811.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "165",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1801.64",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-16",
    botCycle: "166",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1767.73",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "166",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1829.84",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "167",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1806.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "167",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1719.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-24",
    botCycle: "168",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1666.36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-24",
    botCycle: "168",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1712.97",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "169",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1814.04",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "169",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1860.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "170",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2032.06",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "170",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2081.89",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "171",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2006.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "171",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2124.83",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "172",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2096.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "172",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2165.58",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "173",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2129.76",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "173",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2200.96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "174",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2422.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "174",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2215.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-20",
    botCycle: "175",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2400.47",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "175",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2354.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "176",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2589.18",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "176",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2712.77",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "177",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3225.57",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "177",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3445.26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "178",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3228.36",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "178",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3445.2601",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "179",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3747.96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "179",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3978.15",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "180",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3903.38",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "180",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4200.41",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "181",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4145.66",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "181",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3564.91",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "182",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3311.96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "182",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3444.17",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "183",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3188.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "183",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2376.9",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "184",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2393.15",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "184",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2677.68",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "185",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2679.26",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "185",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2461.24",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "186",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2737.99",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "186",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2800.79",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "187",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2725.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "187",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2447.28",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "188",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2460",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "188",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2220.11",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "189",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2123.62",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "189",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1993.31",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "190",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1933.97",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "190",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1850.19",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "191",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2126.59",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "191",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2242.17",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "192",
  },
  {
    botRef: "SPOONERETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2129.01",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "192",
  },
];
