/* eslint-disable import/prefer-default-export */
export const spoonerlink = [
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.491",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-20",
    botCycle: "1",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.480",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-20",
    botCycle: "1",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.491",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-21",
    botCycle: "2",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.512",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-23",
    botCycle: "2",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.440",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-08",
    botCycle: "3",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.447",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-10",
    botCycle: "3",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.444",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-15",
    botCycle: "4",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.465",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-19",
    botCycle: "4",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.477",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-19",
    botCycle: "5",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.458",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-21",
    botCycle: "5",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.463",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-25",
    botCycle: "6",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.416",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-27",
    botCycle: "6",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.441",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-28",
    botCycle: "7",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.422",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-02",
    botCycle: "7",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.429",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-05",
    botCycle: "8",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.461",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-09",
    botCycle: "8",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.498",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-10",
    botCycle: "9",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.463",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-11",
    botCycle: "9",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.483",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-20",
    botCycle: "10",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.477",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-20",
    botCycle: "10",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.483",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-20",
    botCycle: "11",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.437",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-21",
    botCycle: "11",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.462",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-25",
    botCycle: "12",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.454",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-26",
    botCycle: "12",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.482",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-27",
    botCycle: "13",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.489",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-30",
    botCycle: "13",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.503",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-31",
    botCycle: "14",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.570",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-04",
    botCycle: "14",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.583",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-06",
    botCycle: "15",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.561",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-08",
    botCycle: "15",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.499",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-12",
    botCycle: "16",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.515",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-14",
    botCycle: "16",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.524",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-19",
    botCycle: "17",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.512",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-20",
    botCycle: "17",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.514",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-22",
    botCycle: "18",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.495",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-22",
    botCycle: "18",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.454",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-30",
    botCycle: "19",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.483",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-04",
    botCycle: "19",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.521",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-05",
    botCycle: "20",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.671",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-12",
    botCycle: "20",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.686",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-14",
    botCycle: "21",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.800",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-16",
    botCycle: "21",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.884",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-16",
    botCycle: "22",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.841",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-17",
    botCycle: "22",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.385",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-24",
    botCycle: "23",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.292",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-24",
    botCycle: "23",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.177",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-27",
    botCycle: "24",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.192",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-29",
    botCycle: "24",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.928",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-05",
    botCycle: "25",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.119",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-06",
    botCycle: "25",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.126",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-10",
    botCycle: "26",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.604",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-16",
    botCycle: "26",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.787",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-17",
    botCycle: "27",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.804",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-18",
    botCycle: "27",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.787",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-22",
    botCycle: "28",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.784",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-23",
    botCycle: "28",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.904",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-25",
    botCycle: "29",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.083",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-26",
    botCycle: "29",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.389",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-26",
    botCycle: "30",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.526",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-01",
    botCycle: "30",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.173",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-10",
    botCycle: "31",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.656",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-12",
    botCycle: "31",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.237",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-12",
    botCycle: "32",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.021",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-14",
    botCycle: "32",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.344",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-17",
    botCycle: "33",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.578",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-21",
    botCycle: "33",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.511",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-24",
    botCycle: "34",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.362",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-26",
    botCycle: "34",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.190",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-31",
    botCycle: "35",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.122",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-01",
    botCycle: "35",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.230",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-02",
    botCycle: "36",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.430",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-04",
    botCycle: "36",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.378",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-10",
    botCycle: "37",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.366",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-12",
    botCycle: "37",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.476",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-14",
    botCycle: "38",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.365",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-14",
    botCycle: "38",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.453",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-18",
    botCycle: "39",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.488",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-20",
    botCycle: "39",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.286",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-23",
    botCycle: "40",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.177",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-24",
    botCycle: "40",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.177",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-27",
    botCycle: "41",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.034",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-28",
    botCycle: "41",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.800",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-02",
    botCycle: "42",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.803",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-04",
    botCycle: "42",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.822",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-08",
    botCycle: "43",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.776",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-09",
    botCycle: "43",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.635",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-17",
    botCycle: "44",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.777",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-20",
    botCycle: "44",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.863",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-21",
    botCycle: "45",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.810",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-22",
    botCycle: "45",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.857",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-23",
    botCycle: "46",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.803",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-24",
    botCycle: "46",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.875",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-24",
    botCycle: "47",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.784",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-24",
    botCycle: "47",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.723",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-30",
    botCycle: "48",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.901",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-03",
    botCycle: "48",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.030",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-06",
    botCycle: "49",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.522",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-10",
    botCycle: "49",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.641",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-14",
    botCycle: "50",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.465",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-15",
    botCycle: "50",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.496",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-21",
    botCycle: "51",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.594",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-23",
    botCycle: "51",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.679",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-24",
    botCycle: "52",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.660",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-29",
    botCycle: "52",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.764",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-01",
    botCycle: "53",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.649",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-05",
    botCycle: "53",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.728",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-06",
    botCycle: "54",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.683",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-07",
    botCycle: "54",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.729",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-08",
    botCycle: "55",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.769",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-10",
    botCycle: "55",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.836",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-12",
    botCycle: "56",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.975",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-15",
    botCycle: "56",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.292",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-25",
    botCycle: "57",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.177",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-26",
    botCycle: "57",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.351",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-29",
    botCycle: "58",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.275",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-30",
    botCycle: "58",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.069",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-06",
    botCycle: "59",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.014",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-08",
    botCycle: "59",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.074",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-08",
    botCycle: "60",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.021",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-09",
    botCycle: "60",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.074",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-10",
    botCycle: "61",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.149",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-11",
    botCycle: "61",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.093",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-15",
    botCycle: "62",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.975",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-16",
    botCycle: "62",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.827",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-18",
    botCycle: "63",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.872",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-21",
    botCycle: "63",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.917",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-22",
    botCycle: "64",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.902",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-23",
    botCycle: "64",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.838",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-26",
    botCycle: "65",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.852",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-29",
    botCycle: "65",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.879",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-29",
    botCycle: "66",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.832",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-30",
    botCycle: "66",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.819",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-01",
    botCycle: "67",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.793",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-02",
    botCycle: "67",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.808",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-03",
    botCycle: "68",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.801",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-05",
    botCycle: "68",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.841",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-06",
    botCycle: "69",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.163",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-08",
    botCycle: "69",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.342",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-11",
    botCycle: "70",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.188",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-13",
    botCycle: "70",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.242",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-14",
    botCycle: "71",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.330",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-16",
    botCycle: "71",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.452",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-16",
    botCycle: "72",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.668",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-19",
    botCycle: "72",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.506",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-24",
    botCycle: "73",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.807",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-31",
    botCycle: "73",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.839",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-02",
    botCycle: "74",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.750",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-03",
    botCycle: "74",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.802",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-05",
    botCycle: "75",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.294",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-09",
    botCycle: "75",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.474",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-10",
    botCycle: "76",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.350",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-15",
    botCycle: "76",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.587",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-16",
    botCycle: "77",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.242",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-16",
    botCycle: "77",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.842",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-26",
    botCycle: "78",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.030",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-01",
    botCycle: "78",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.187",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-02",
    botCycle: "79",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.590",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-04",
    botCycle: "79",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.726",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-13",
    botCycle: "80",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.116",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-15",
    botCycle: "80",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.363",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-19",
    botCycle: "81",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.281",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-20",
    botCycle: "81",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.327",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-24",
    botCycle: "82",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.210",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-25",
    botCycle: "82",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.337",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-27",
    botCycle: "83",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.240",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-27",
    botCycle: "83",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.115",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-30",
    botCycle: "84",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.163",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-01",
    botCycle: "84",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.282",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-02",
    botCycle: "85",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.310",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-02",
    botCycle: "85",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.473",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-06",
    botCycle: "86",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.039",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-10",
    botCycle: "86",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.459",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-12",
    botCycle: "87",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.348",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-13",
    botCycle: "87",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.269",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-16",
    botCycle: "88",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.613",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-19",
    botCycle: "88",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.786",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-23",
    botCycle: "89",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.677",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-26",
    botCycle: "89",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.808",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-29",
    botCycle: "90",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.688",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-30",
    botCycle: "90",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.749",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-04",
    botCycle: "91",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.673",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-05",
    botCycle: "91",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.762",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-07",
    botCycle: "92",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.764",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-10",
    botCycle: "92",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.825",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-14",
    botCycle: "93",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.700",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-15",
    botCycle: "93",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.851",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-17",
    botCycle: "94",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.806",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-19",
    botCycle: "94",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.924",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-20",
    botCycle: "95",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.938",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-20",
    botCycle: "95",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.079",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-20",
    botCycle: "96",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.888",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-21",
    botCycle: "96",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.905",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-27",
    botCycle: "97",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.983",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-29",
    botCycle: "97",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.101",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-30",
    botCycle: "98",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.312",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-02",
    botCycle: "98",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.407",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-08",
    botCycle: "99",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.392",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-09",
    botCycle: "99",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.128",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-17",
    botCycle: "100",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.019",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-17",
    botCycle: "100",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.128",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-17",
    botCycle: "101",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.712",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-24",
    botCycle: "101",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.615",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-29",
    botCycle: "102",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.666",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-02",
    botCycle: "102",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.845",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-06",
    botCycle: "103",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "6.100",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-09",
    botCycle: "103",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6.354",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-12",
    botCycle: "104",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7.365",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-13",
    botCycle: "104",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8.408",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-15",
    botCycle: "105",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7.913",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-18",
    botCycle: "105",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7.668",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-23",
    botCycle: "106",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7.502",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-24",
    botCycle: "106",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7.789",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-25",
    botCycle: "107",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7.382",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-26",
    botCycle: "107",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7.585",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-31",
    botCycle: "108",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7.610",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-02",
    botCycle: "108",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8.445",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-02",
    botCycle: "109",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9.522",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-07",
    botCycle: "109",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10.085",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-07",
    botCycle: "110",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.482",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-11",
    botCycle: "110",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13.536",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-12",
    botCycle: "111",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18.636",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-17",
    botCycle: "111",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "16.228",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-22",
    botCycle: "112",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "14.380",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-25",
    botCycle: "112",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.331",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-26",
    botCycle: "113",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "14.345",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-27",
    botCycle: "113",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.405",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-28",
    botCycle: "114",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "16.637",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-31",
    botCycle: "114",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.724",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-06",
    botCycle: "115",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11.500",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-08",
    botCycle: "115",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.702",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-10",
    botCycle: "116",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.353",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-10",
    botCycle: "116",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13.140",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-13",
    botCycle: "117",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.258",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-13",
    botCycle: "117",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8.485",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-24",
    botCycle: "118",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10.084",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-26",
    botCycle: "118",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10.209",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "119",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9.895",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-01",
    botCycle: "119",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9.538",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-05",
    botCycle: "120",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9.139",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-06",
    botCycle: "120",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8.996",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08",
    botCycle: "121",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10.223",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-11",
    botCycle: "121",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10.740",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-11",
    botCycle: "122",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10.885",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-13",
    botCycle: "122",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10.921",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-18",
    botCycle: "123",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10.671",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-19",
    botCycle: "123",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10.984",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-19",
    botCycle: "124",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10.642",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-20",
    botCycle: "124",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11.201",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-22",
    botCycle: "125",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.353",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-25",
    botCycle: "125",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.432",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-27",
    botCycle: "126",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11.435",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28",
    botCycle: "126",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10.546",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "127",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10.178",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-05",
    botCycle: "127",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10.629",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-05",
    botCycle: "128",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.360",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "128",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.539",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-16",
    botCycle: "129",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13.260",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-18",
    botCycle: "129",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "14.231",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-20",
    botCycle: "130",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "14.477",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-22",
    botCycle: "130",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.633",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-24",
    botCycle: "131",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15.144",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-24",
    botCycle: "131",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13.334",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-06",
    botCycle: "132",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.631",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-08",
    botCycle: "132",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.177",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-12",
    botCycle: "133",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12.459",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-14",
    botCycle: "133",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12.832",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-16",
    botCycle: "134",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13.444",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-18",
    botCycle: "134",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11.316",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-27",
    botCycle: "135",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11.304",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-29",
    botCycle: "135",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11.840",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-01",
    botCycle: "136",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13.356",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "136",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.543",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "137",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15.966",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-08",
    botCycle: "137",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17.348",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-09",
    botCycle: "138",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "16.620",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "138",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15.200",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "139",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "20.346",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-16",
    botCycle: "139",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.847",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "140",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "20.961",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-19",
    botCycle: "140",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "20.141",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-22",
    botCycle: "141",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.393",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "141",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.264",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-28",
    botCycle: "142",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22.520",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "142",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23.813",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "143",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.209",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "143",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "24.567",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-03",
    botCycle: "144",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23.994",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "144",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "26.043",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "145",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "25.018",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-06",
    botCycle: "145",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "25.939",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "146",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.744",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "146",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.598",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-12",
    botCycle: "147",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.667",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "147",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.045",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "148",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31.269",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "148",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34.159",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "149",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32.128",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "149",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33.309",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-18",
    botCycle: "150",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "33.924",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-21",
    botCycle: "150",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "26.934",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "151",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "24.584",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-28",
    botCycle: "151",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.386",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "152",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.861",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "152",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.324",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "153",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.212",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "153",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.631",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "154",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.144",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "154",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "30.425",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-13",
    botCycle: "155",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "28.134",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "155",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "29.454",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "156",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30.403",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-20",
    botCycle: "156",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.753",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-24",
    botCycle: "157",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.716",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-24",
    botCycle: "157",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.450",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-28",
    botCycle: "158",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26.830",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-28",
    botCycle: "158",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "27.280",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "159",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "27.706",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "159",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.549",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "160",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31.058",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "160",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "31.433",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "161",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32.606",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "161",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.690",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "162",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31.233",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "162",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.949",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-11",
    botCycle: "163",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32.400",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "163",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33.868",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "164",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "40.460",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "164",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39.096",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "165",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36.495",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "165",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33.377",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "166",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35.358",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "166",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "37.378",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "167",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39.139",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-02",
    botCycle: "167",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "41.093",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "168",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39.478",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "168",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "42.623",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "169",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "46.153",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "169",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "49.817",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "170",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "49.100",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "170",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "44.843",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "171",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "44.716",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "171",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39.871",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "172",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39.043",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "172",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "24.313",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "173",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31.161",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "173",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28.386",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "174",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.646",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "174",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32.562",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "175",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "29.915",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "175",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "22.252",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "176",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "24.007",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "176",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "20.772",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "177",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "20.581",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "177",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "18.732",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "178",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "17.391",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "178",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19.128",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "179",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18.038",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "179",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17.460",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "180",
  },
  {
    botRef: "SPOONERLINK",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18.787",
    sbl: "LINKUSDT",
    base: "LINK",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "180",
  },
];
