/* eslint-disable import/prefer-default-export */
export const spoonerbtc = [
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3752.09",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-02",
    botCycle: "1",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3738.71",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-03",
    botCycle: "1",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3879.03",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-06",
    botCycle: "2",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3779.63",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-10",
    botCycle: "2",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3606.02",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-14",
    botCycle: "3",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3534.42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-15",
    botCycle: "3",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3634.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-16",
    botCycle: "4",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3580",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-20",
    botCycle: "4",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3601.59",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-26",
    botCycle: "5",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3558.01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-26",
    botCycle: "5",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3444.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-30",
    botCycle: "6",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3425.69",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-01-31",
    botCycle: "6",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3478.66",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-01",
    botCycle: "7",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3436.39",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-04",
    botCycle: "7",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3470.16",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-04",
    botCycle: "8",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3418.18",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-06",
    botCycle: "8",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3424.51",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-08",
    botCycle: "9",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3619.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-10",
    botCycle: "9",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3672.29",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-11",
    botCycle: "10",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3623.11",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-11",
    botCycle: "10",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3624.34",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-15",
    botCycle: "11",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3623.73",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-17",
    botCycle: "11",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3691.69",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-18",
    botCycle: "12",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3922.99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-21",
    botCycle: "12",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3977.4",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-22",
    botCycle: "13",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3789.98",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-24",
    botCycle: "13",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3836.98",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-02-28",
    botCycle: "14",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3814.69",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-02",
    botCycle: "14",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3831.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-05",
    botCycle: "15",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3850.01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-09",
    botCycle: "15",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3925.8",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-09",
    botCycle: "16",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3882.38",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-11",
    botCycle: "16",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3891.91",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-14",
    botCycle: "17",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3971",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-17",
    botCycle: "17",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4007.35",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-18",
    botCycle: "18",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3963.65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-18",
    botCycle: "18",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4033.68",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-20",
    botCycle: "19",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3910",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-21",
    botCycle: "19",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3998.4",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-03-27",
    botCycle: "20",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4932.59",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-04",
    botCycle: "20",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5024.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-04",
    botCycle: "21",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4960.19",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-04",
    botCycle: "21",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5010",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-05",
    botCycle: "22",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5015.43",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-07",
    botCycle: "22",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5192.3",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-08",
    botCycle: "23",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5046.16",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-08",
    botCycle: "23",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5297.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-10",
    botCycle: "24",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5143.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-11",
    botCycle: "24",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5096.63",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-15",
    botCycle: "25",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5047.25",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-15",
    botCycle: "25",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5140.87",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-16",
    botCycle: "26",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5194.02",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-19",
    botCycle: "26",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5269.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-19",
    botCycle: "27",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5206.68",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-21",
    botCycle: "27",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5311.42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-22",
    botCycle: "28",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5420.61",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-24",
    botCycle: "28",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5330.06",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-04-30",
    botCycle: "29",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5633.16",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-04",
    botCycle: "29",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5813.86",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-07",
    botCycle: "30",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "6926.23",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-12",
    botCycle: "30",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7485.61",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-13",
    botCycle: "31",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7867.75",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-16",
    botCycle: "31",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8021.53",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-19",
    botCycle: "32",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7870",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-20",
    botCycle: "32",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7997.41",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-24",
    botCycle: "33",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8454.21",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-29",
    botCycle: "33",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8775.51",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-30",
    botCycle: "34",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8645",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-05-30",
    botCycle: "34",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7834.1",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-07",
    botCycle: "35",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7814.68",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-08",
    botCycle: "35",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7920.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-10",
    botCycle: "36",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7767.55",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-11",
    botCycle: "36",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8000.31",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-12",
    botCycle: "37",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10515",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-23",
    botCycle: "37",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11130.33",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-23",
    botCycle: "38",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10725.15",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-24",
    botCycle: "38",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11345.82",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-25",
    botCycle: "39",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12598.31",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-06-27",
    botCycle: "39",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11513.75",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-04",
    botCycle: "40",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11145.67",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-05",
    botCycle: "40",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11648.6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-08",
    botCycle: "41",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12206.16",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-09",
    botCycle: "41",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12747.36",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-10",
    botCycle: "42",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12550.03",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-10",
    botCycle: "42",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11764.32",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-12",
    botCycle: "43",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11299.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-13",
    botCycle: "43",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10833.75",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-20",
    botCycle: "44",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10632.73",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-21",
    botCycle: "44",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10147.26",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-27",
    botCycle: "45",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9546.65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-07-27",
    botCycle: "45",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10178.46",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-01",
    botCycle: "46",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10383.07",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-02",
    botCycle: "46",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10638",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-03",
    botCycle: "47",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10609.77",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-04",
    botCycle: "47",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10894.3",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-04",
    botCycle: "48",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11748.03",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-06",
    botCycle: "48",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11821.73",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-07",
    botCycle: "49",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11597.27",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-08",
    botCycle: "49",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "12052.14",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-09",
    botCycle: "50",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11395.23",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-10",
    botCycle: "50",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10438.01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-16",
    botCycle: "51",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10080.21",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-17",
    botCycle: "51",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10450.05",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-18",
    botCycle: "52",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10322.05",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-21",
    botCycle: "52",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10189.26",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-22",
    botCycle: "53",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10100",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-24",
    botCycle: "53",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10308.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-26",
    botCycle: "54",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9718.53",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-08-28",
    botCycle: "54",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10284.42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-02",
    botCycle: "55",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10426.33",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-06",
    botCycle: "55",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10378.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-12",
    botCycle: "56",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10148.3",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-16",
    botCycle: "56",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10270.69",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-19",
    botCycle: "57",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10034.59",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-21",
    botCycle: "57",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8240.32",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-29",
    botCycle: "58",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7822.83",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-30",
    botCycle: "58",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8119.84",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-09-30",
    botCycle: "59",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8214.74",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-03",
    botCycle: "59",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8173.18",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-07",
    botCycle: "60",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8461.22",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-10",
    botCycle: "60",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8636.6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-11",
    botCycle: "61",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8441.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-11",
    botCycle: "61",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8110.42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-20",
    botCycle: "62",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8116.12",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-22",
    botCycle: "62",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8009.39",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-25",
    botCycle: "63",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9204.45",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-10-29",
    botCycle: "63",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9357.48",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-04",
    botCycle: "64",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9225.06",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-05",
    botCycle: "64",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8680.96",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-15",
    botCycle: "65",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8463.84",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-15",
    botCycle: "65",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7687.48",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-22",
    botCycle: "66",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7402.77",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-22",
    botCycle: "66",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7254.56",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-25",
    botCycle: "67",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "6886.51",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-27",
    botCycle: "67",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7173.07",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-27",
    botCycle: "68",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7387.89",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-29",
    botCycle: "68",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7636.27",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-29",
    botCycle: "69",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7635.04",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-11-30",
    botCycle: "69",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7353.81",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-04",
    botCycle: "70",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7199.97",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-04",
    botCycle: "70",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7547.86",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-08",
    botCycle: "71",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7413.05",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-09",
    botCycle: "71",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6935.38",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-18",
    botCycle: "72",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7387.91",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-23",
    botCycle: "72",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7426.12",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-26",
    botCycle: "73",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7197.81",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-26",
    botCycle: "73",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7415.05",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-29",
    botCycle: "74",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7339.74",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2019-12-30",
    botCycle: "74",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7177.34",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-03",
    botCycle: "75",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7367.62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-05",
    botCycle: "75",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7480.6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-06",
    botCycle: "76",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7764.04",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-07",
    botCycle: "76",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7956.67",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-07",
    botCycle: "77",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8115",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-08",
    botCycle: "77",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8398.27",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-14",
    botCycle: "78",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8681.16",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-19",
    botCycle: "78",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8439.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-24",
    botCycle: "79",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8309.51",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-25",
    botCycle: "79",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8521.08",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-01-26",
    botCycle: "80",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9267.91",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-02",
    botCycle: "80",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9406.66",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-02",
    botCycle: "81",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9313.59",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-03",
    botCycle: "81",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9344.07",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-05",
    botCycle: "82",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10055.98",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-10",
    botCycle: "82",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10184.2",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-11",
    botCycle: "83",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10260.86",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-13",
    botCycle: "83",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9983.65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-18",
    botCycle: "84",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9615.77",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-02-19",
    botCycle: "84",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8730.8",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-02",
    botCycle: "85",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8783.92",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-03",
    botCycle: "85",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8960.13",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-05",
    botCycle: "86",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9001.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-06",
    botCycle: "86",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9164.68",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-07",
    botCycle: "87",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8925",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-07",
    botCycle: "87",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5508.1",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-19",
    botCycle: "88",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "6192.59",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-20",
    botCycle: "88",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6395.87",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-23",
    botCycle: "89",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "6522",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-25",
    botCycle: "89",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6780.14",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-25",
    botCycle: "90",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "6573.77",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-25",
    botCycle: "90",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6197.6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-03-30",
    botCycle: "91",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "6305.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-01",
    botCycle: "91",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6492.4",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-02",
    botCycle: "92",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "6739.45",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-02",
    botCycle: "92",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7034.2",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-06",
    botCycle: "93",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7119.62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-07",
    botCycle: "93",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "6928.42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-16",
    botCycle: "94",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "7122.79",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-19",
    botCycle: "94",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "7175.96",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-23",
    botCycle: "95",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "8634.15",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-04-30",
    botCycle: "95",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8945.11",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-05",
    botCycle: "96",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9697.55",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-09",
    botCycle: "96",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "8887.34",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-11",
    botCycle: "97",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9250.29",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-15",
    botCycle: "97",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9846.86",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-17",
    botCycle: "98",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9591.57",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-18",
    botCycle: "98",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9749.06",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-19",
    botCycle: "99",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9414.51",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-20",
    botCycle: "99",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9010.21",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-27",
    botCycle: "100",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9365",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-29",
    botCycle: "100",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9611.43",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-05-31",
    botCycle: "101",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9582.17",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-02",
    botCycle: "101",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9712.96",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-07",
    botCycle: "102",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9721.37",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-11",
    botCycle: "102",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9441.07",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-15",
    botCycle: "103",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9368.83",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-17",
    botCycle: "103",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9388.43",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-22",
    botCycle: "104",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9512.82",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-24",
    botCycle: "104",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9191.65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-06-29",
    botCycle: "105",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9048.92",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-02",
    botCycle: "105",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9121.85",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-06",
    botCycle: "106",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9228.27",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-07",
    botCycle: "106",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9374.18",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-08",
    botCycle: "107",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9294.19",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-09",
    botCycle: "107",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9308.33",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-12",
    botCycle: "108",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9223.58",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-14",
    botCycle: "108",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9194.8",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-20",
    botCycle: "109",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "9474.09",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-24",
    botCycle: "109",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "9656.19",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-25",
    botCycle: "110",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10977.78",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-30",
    botCycle: "110",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11328.34",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-31",
    botCycle: "111",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11170.8",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-02",
    botCycle: "111",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11458.2",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-05",
    botCycle: "112",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11589.08",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-07",
    botCycle: "112",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11841.07",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-10",
    botCycle: "113",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11686.12",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-10",
    botCycle: "113",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11645.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-13",
    botCycle: "114",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11941.37",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-18",
    botCycle: "114",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11566.78",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-29",
    botCycle: "115",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11835.02",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-02",
    botCycle: "115",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10337.17",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-06",
    botCycle: "116",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10079.74",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-07",
    botCycle: "116",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10335.09",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-08",
    botCycle: "117",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10014.97",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-08",
    botCycle: "117",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10424.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-10",
    botCycle: "118",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10324.88",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-13",
    botCycle: "118",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10574.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-14",
    botCycle: "119",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10834.43",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-18",
    botCycle: "119",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11029.58",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-19",
    botCycle: "120",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10918.37",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-20",
    botCycle: "120",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10532.66",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-24",
    botCycle: "121",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10660.56",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-27",
    botCycle: "121",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10795.45",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-28",
    botCycle: "122",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10696.11",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-29",
    botCycle: "122",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10656.95",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-04",
    botCycle: "123",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "10676.64",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-06",
    botCycle: "123",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "10678.4",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-08",
    botCycle: "124",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11264.79",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-12",
    botCycle: "124",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11410.34",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-12",
    botCycle: "125",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11458.24",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-13",
    botCycle: "125",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11533.06",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-15",
    botCycle: "126",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "11275.57",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-16",
    botCycle: "126",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "11607.58",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-19",
    botCycle: "127",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "12954.55",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-25",
    botCycle: "127",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13226.82",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-27",
    botCycle: "128",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13318.33",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-28",
    botCycle: "128",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13318.25",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-29",
    botCycle: "129",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13181.56",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-30",
    botCycle: "129",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13657.3",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-30",
    botCycle: "130",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13446.65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-02",
    botCycle: "130",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "13855.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "131",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "13600.46",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "131",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "14041.92",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "132",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "14927.96",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-07",
    botCycle: "132",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15571.63",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-08",
    botCycle: "133",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15081.46",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-09",
    botCycle: "133",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "15800.62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "134",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "15959",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-14",
    botCycle: "134",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "16346.78",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-16",
    botCycle: "135",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18211.66",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-22",
    botCycle: "135",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "18666",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-23",
    botCycle: "136",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18758.71",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "136",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "17438.47",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-28",
    botCycle: "137",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18550.25",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "137",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19330.6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-07",
    botCycle: "138",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "18791.78",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-08",
    botCycle: "138",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "18426.43",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-12",
    botCycle: "139",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "19180.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-15",
    botCycle: "139",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "19557.43",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-16",
    botCycle: "140",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "23376.94",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-20",
    botCycle: "140",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "23765.1",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-21",
    botCycle: "141",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "22446.39",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-21",
    botCycle: "141",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "24071.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-23",
    botCycle: "142",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "26219.88",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-27",
    botCycle: "142",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "28236.4",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-30",
    botCycle: "143",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "30669.43",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-02",
    botCycle: "143",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32767.02",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-05",
    botCycle: "144",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37181.74",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-08",
    botCycle: "144",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39978.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-08",
    botCycle: "145",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39175.09",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "145",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36247.81",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "146",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "33286",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "146",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36526.97",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-13",
    botCycle: "147",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37808.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "147",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36693.15",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "148",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35901.94",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-20",
    botCycle: "148",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32636.12",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-22",
    botCycle: "149",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "31729.07",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "149",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33021.06",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "150",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32715.53",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "150",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32875.18",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-28",
    botCycle: "151",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32266.36",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-29",
    botCycle: "151",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34134.63",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-01",
    botCycle: "152",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36564.23",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "152",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "38538.95",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-06",
    botCycle: "153",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39181.01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "153",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39660.42",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "154",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "44954.13",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "154",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "47219.1",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-11",
    botCycle: "155",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "46586.23",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "155",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "48104.35",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "156",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "46874.01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-15",
    botCycle: "156",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "49240.66",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "157",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "56235.15",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-22",
    botCycle: "157",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "47491.43",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-01",
    botCycle: "158",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "47519.58",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "158",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "49606.93",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "159",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "47600",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-04",
    botCycle: "159",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "49082.82",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-06",
    botCycle: "160",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "49755.24",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "160",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "51787.65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "161",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "53468.33",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "161",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "55678.61",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-10",
    botCycle: "162",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57789.75",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-15",
    botCycle: "162",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56879.86",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "163",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "54763.59",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "163",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57096.37",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-17",
    botCycle: "164",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57294.12",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-18",
    botCycle: "164",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "55784.03",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-24",
    botCycle: "165",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "54736.52",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-24",
    botCycle: "165",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56442.62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-29",
    botCycle: "166",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "58173.82",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "166",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "59332.74",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-31",
    botCycle: "167",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "58208.33",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "167",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "58337.72",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "168",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57818.54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "168",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "58577.28",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "169",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "58619.72",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "169",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "61416.31",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "170",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "62250.14",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "170",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56507.87",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-20",
    botCycle: "171",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "53996.73",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "171",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "50530.25",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "172",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "54144.18",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "172",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "55692.21",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "173",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "53564.94",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "173",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "54641.49",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "174",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "56450.19",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-02",
    botCycle: "174",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "57943.48",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "175",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "56783.93",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "175",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "56581.62",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "176",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "55752.54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "176",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "58239",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "177",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "56433.54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "177",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "59216.6",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "178",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "57899.65",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "178",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "49611.07",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "179",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "47276.26",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "179",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "38742.64",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "180",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36537.17",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "180",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "39799.7",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "181",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "36996.45",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "181",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36305",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "182",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "37900",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "182",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36723.89",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "183",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35528.73",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "183",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "36102.54",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "184",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "39080.01",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "184",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "35899.77",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "185",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "34243.9",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "185",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "33199.59",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "186",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "32882.5",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "186",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "34780.63",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "187",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "33751.57",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "187",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "32666",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "188",
  },
  {
    botRef: "SPOONERBTC",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "35119.99",
    sbl: "BTCUSDT",
    base: "BTC",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "188",
  },
];
