/* eslint-disable import/prefer-default-export */
export const surgebotsxp = [
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.6136",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-24",
    botCycle: "1",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.8766",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-24",
    botCycle: "1",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.01",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-26",
    botCycle: "2",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.8775",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-26",
    botCycle: "2",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.7354",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-27",
    botCycle: "3",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.634",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-27",
    botCycle: "3",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.5277",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-28",
    botCycle: "4",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.7975",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-07-31",
    botCycle: "4",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.8523",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-07",
    botCycle: "5",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.7819",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-07",
    botCycle: "5",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.9171",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-08",
    botCycle: "6",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.3873",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-09",
    botCycle: "6",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "4.4231",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-14",
    botCycle: "7",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.5625",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-15",
    botCycle: "7",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.6668",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-15",
    botCycle: "8",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.339",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-16",
    botCycle: "8",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.3711",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-17",
    botCycle: "9",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.479",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-17",
    botCycle: "9",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.294",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-20",
    botCycle: "10",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.5352",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-20",
    botCycle: "10",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.0158",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-21",
    botCycle: "11",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.1589",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-21",
    botCycle: "11",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.5501",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-23",
    botCycle: "12",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.6526",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-27",
    botCycle: "12",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.9058",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-08-31",
    botCycle: "13",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.8409",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-04",
    botCycle: "13",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.0077",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-05",
    botCycle: "14",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.8539",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-05",
    botCycle: "14",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.6835",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-07",
    botCycle: "15",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.7374",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-07",
    botCycle: "15",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.6546",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-08",
    botCycle: "16",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.7701",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-14",
    botCycle: "16",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.5257",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-20",
    botCycle: "17",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.3209",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-21",
    botCycle: "17",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.1462",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-25",
    botCycle: "18",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.1829",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-25",
    botCycle: "18",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.3106",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-26",
    botCycle: "19",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.3526",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-26",
    botCycle: "19",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "0.8336",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-31",
    botCycle: "20",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.8237",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-01",
    botCycle: "20",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.8562",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-02",
    botCycle: "21",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8236",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-02",
    botCycle: "21",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.7853",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-04",
    botCycle: "22",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8222",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-05",
    botCycle: "22",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.9824",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-10",
    botCycle: "23",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.945",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-10",
    botCycle: "23",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.0035",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-11",
    botCycle: "24",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.8935",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-12",
    botCycle: "24",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "0.9819",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-21",
    botCycle: "25",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.0134",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-21",
    botCycle: "25",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.0675",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-22",
    botCycle: "26",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.1017",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-23",
    botCycle: "26",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.1033",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-24",
    botCycle: "27",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0613",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "27",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.1196",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "28",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.8996",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-26",
    botCycle: "28",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.965",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-28",
    botCycle: "29",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.9283",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-28",
    botCycle: "29",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "0.9734",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "30",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.9428",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-02",
    botCycle: "30",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "0.9669",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-03",
    botCycle: "31",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.8661",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-05",
    botCycle: "31",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "0.6817",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-28",
    botCycle: "32",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.6723",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-29",
    botCycle: "32",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.7227",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-02",
    botCycle: "33",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.7641",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-03",
    botCycle: "33",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "0.7211",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "34",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.7263",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "34",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "0.7504",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "35",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.7745",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-06",
    botCycle: "35",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.0402",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "36",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.8338",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "36",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "0.8833",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "37",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "0.9116",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-15",
    botCycle: "37",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "0.9815",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-17",
    botCycle: "38",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.013",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-18",
    botCycle: "38",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.0182",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-25",
    botCycle: "39",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.0508",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "39",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.0394",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-27",
    botCycle: "40",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.265",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-28",
    botCycle: "40",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.423",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "41",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.4686",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "41",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.7676",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "42",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.8242",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-05",
    botCycle: "42",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.7756",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "43",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.0044",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-07",
    botCycle: "43",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.2364",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "44",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.3301",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-10",
    botCycle: "44",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.781",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-13",
    botCycle: "45",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.2803",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-14",
    botCycle: "45",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.1861",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-16",
    botCycle: "46",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.2561",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-17",
    botCycle: "46",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.4892",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-20",
    botCycle: "47",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.0574",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-23",
    botCycle: "47",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.2761",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "48",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.349",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-26",
    botCycle: "48",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.3443",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "49",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.2552",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-27",
    botCycle: "49",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.1643",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "50",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.2336",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "50",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.1566",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-02",
    botCycle: "51",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.2257",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-03",
    botCycle: "51",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.5455",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "52",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.627",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "52",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.5661",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "53",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.6483",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "53",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.9262",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "54",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.0199",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-09",
    botCycle: "54",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.5461",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "55",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.9237",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-14",
    botCycle: "55",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.7539",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-20",
    botCycle: "56",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.5743",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-21",
    botCycle: "56",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.8115",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "57",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.4394",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "57",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.9783",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-26",
    botCycle: "58",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.9607",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-27",
    botCycle: "58",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.6895",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-02",
    botCycle: "59",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.8076",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "59",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.8248",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "60",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.6794",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-03",
    botCycle: "60",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.7093",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "61",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.5303",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "61",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.5881",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "62",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.4137",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "62",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.3059",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-08",
    botCycle: "63",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.6255",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "63",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5.0252",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "64",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.8342",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "64",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "4.618",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "65",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "4.5996",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "65",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "4.7211",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "66",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "4.8722",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "66",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "4.8152",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "67",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.6107",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "67",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.6783",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-21",
    botCycle: "68",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.8165",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-21",
    botCycle: "68",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.7809",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "69",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.8879",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "69",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "5.2262",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "70",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "5.3935",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "70",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5.0102",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "71",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.8198",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "71",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4.9888",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "72",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.7992",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "72",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "5.0727",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "73",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "5.19",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "73",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "4.5015",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "74",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.4038",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "74",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.5931",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "75",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.7603",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "75",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.5901",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "76",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.4239",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "76",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.0614",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "77",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.1274",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "77",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.1229",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "78",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.3026",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "78",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.9026",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "79",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.8495",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "79",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.8929",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "80",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.9535",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "80",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.0797",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "81",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.1833",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "81",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.1819",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "82",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.064",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "82",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.0205",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "83",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.9486",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "83",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.8273",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "84",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.8858",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "84",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.7806",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "85",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.8376",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "85",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.2341",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "86",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.1492",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "86",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.8716",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "87",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.9345",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "87",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.9498",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "88",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.0122",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "88",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.0572",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-06",
    botCycle: "89",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.1131",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-06",
    botCycle: "89",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.5095",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-21",
    botCycle: "90",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.6309",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-24",
    botCycle: "90",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.6894",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "91",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.7435",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "91",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.9003",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "92",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.9612",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "92",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.0059",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "93",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.1669",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-01",
    botCycle: "93",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.2296",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "94",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.1478",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "94",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.1502",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "95",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.2191",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "95",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.2415",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "96",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.2987",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "96",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.19",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "97",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.0295",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "97",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.4477",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "98",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.4524",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "98",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.6819",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "99",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.5419",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-22",
    botCycle: "99",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.9929",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-27",
    botCycle: "100",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.8411",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-28",
    botCycle: "100",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.6864",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-01",
    botCycle: "101",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.7199",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-01",
    botCycle: "101",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.7198",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-03",
    botCycle: "102",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4.025",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-06",
    botCycle: "102",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "3.8232",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-06",
    botCycle: "103",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "3.2051",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "103",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.7378",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-10",
    botCycle: "104",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.8255",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-11",
    botCycle: "104",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.7373",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-11",
    botCycle: "105",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.8249",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-11",
    botCycle: "105",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.7699",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-12",
    botCycle: "106",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.613",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-13",
    botCycle: "106",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.8202",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-16",
    botCycle: "107",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.6067",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-18",
    botCycle: "107",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.0259",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-21",
    botCycle: "108",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.0908",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-22",
    botCycle: "108",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.1468",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-30",
    botCycle: "109",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.3362",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-01",
    botCycle: "109",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.397",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-03",
    botCycle: "110",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.3482",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-04",
    botCycle: "110",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.4429",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-06",
    botCycle: "111",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.5211",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-06",
    botCycle: "111",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.4549",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-07",
    botCycle: "112",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.5335",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-07",
    botCycle: "112",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.584",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-09",
    botCycle: "113",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.4858",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-09",
    botCycle: "113",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.5117",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "114",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.309",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-12",
    botCycle: "114",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.4301",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-16",
    botCycle: "115",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.3377",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "115",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.3195",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-21",
    botCycle: "116",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.2446",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-24",
    botCycle: "116",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.16",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-28",
    botCycle: "117",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.1789",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-28",
    botCycle: "117",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.382",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-06",
    botCycle: "118",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.4095",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-06",
    botCycle: "118",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.4752",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-08",
    botCycle: "119",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.507",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-08",
    botCycle: "119",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.4344",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-10",
    botCycle: "120",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.3525",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-12",
    botCycle: "120",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.889",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-16",
    botCycle: "121",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.7792",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-16",
    botCycle: "121",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.5938",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-16",
    botCycle: "122",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.4375",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-17",
    botCycle: "122",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.4612",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-18",
    botCycle: "123",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.3714",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-18",
    botCycle: "123",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.449",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-19",
    botCycle: "124",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.5055",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-22",
    botCycle: "124",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.3723",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-24",
    botCycle: "125",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.4483",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-24",
    botCycle: "125",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "2.2244",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "126",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "2.2956",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "126",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.2717",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-11-30",
    botCycle: "127",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.2224",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-03",
    botCycle: "127",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.6128",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-06",
    botCycle: "128",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.685",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-07",
    botCycle: "128",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.6971",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-08",
    botCycle: "129",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.6326",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-08",
    botCycle: "129",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.5034",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-13",
    botCycle: "130",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.5038",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-13",
    botCycle: "130",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.509",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-15",
    botCycle: "131",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.5089",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-16",
    botCycle: "131",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.4797",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-16",
    botCycle: "132",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.4969",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-18",
    botCycle: "132",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.594",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-26",
    botCycle: "133",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.6451",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-26",
    botCycle: "133",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.626",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-28",
    botCycle: "134",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.603",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-12-28",
    botCycle: "134",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.8799",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-04",
    botCycle: "135",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.9401",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-05",
    botCycle: "135",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.9051",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-05",
    botCycle: "136",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.6637",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-05",
    botCycle: "136",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.5767",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-07",
    botCycle: "137",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.6272",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-07",
    botCycle: "137",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.5557",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-08",
    botCycle: "138",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.4522",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-08",
    botCycle: "138",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.7867",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-16",
    botCycle: "139",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.6459",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-17",
    botCycle: "139",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.5259",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-19",
    botCycle: "140",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.5748",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-19",
    botCycle: "140",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.5892",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-19",
    botCycle: "141",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.5288",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-20",
    botCycle: "141",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.5195",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-21",
    botCycle: "142",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.5682",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-21",
    botCycle: "142",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.3106",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-23",
    botCycle: "143",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.2607",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-23",
    botCycle: "143",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.2644",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-27",
    botCycle: "144",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.3049",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-27",
    botCycle: "144",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.2824",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-28",
    botCycle: "145",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.3235",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-28",
    botCycle: "145",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.3248",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-30",
    botCycle: "146",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.3096",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-30",
    botCycle: "146",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.3506",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-01-31",
    botCycle: "147",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.3813",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-01",
    botCycle: "147",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.3456",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-13",
    botCycle: "148",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.3887",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-14",
    botCycle: "148",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.4809",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-16",
    botCycle: "149",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.4246",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-17",
    botCycle: "149",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.4255",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-17",
    botCycle: "150",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.4041",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-17",
    botCycle: "150",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.2797",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-21",
    botCycle: "151",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.1198",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-22",
    botCycle: "151",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.2834",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-26",
    botCycle: "152",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.2346",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-27",
    botCycle: "152",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.2362",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-27",
    botCycle: "153",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.2758",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-27",
    botCycle: "153",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.3129",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-02-28",
    botCycle: "154",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.4295",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-01",
    botCycle: "154",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.4459",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-04",
    botCycle: "155",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.3909",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-04",
    botCycle: "155",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "open",
    estimatedPrice: "1.2506",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-07",
    botCycle: "156",
  },
  {
    botRef: "SURGEBOTSXP",
    botVer: "1",
    stratType: "SHORT",
    position: "close",
    estimatedPrice: "1.2907",
    sbl: "SXPUSDT",
    base: "SXP",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2022-03-08",
    botCycle: "156",
  },
];
