/* eslint-disable import/prefer-default-export */
export const tomolo1 = [
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6666",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-10",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.7392",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-12",
    botCycle: "1",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6396",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-19",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8206",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-22",
    botCycle: "2",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.7652",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-23",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.9718",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-09-25",
    botCycle: "3",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.7466",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-10",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.703",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-15",
    botCycle: "4",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6588",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-23",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6192",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-26",
    botCycle: "5",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6256",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-29",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.5881",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-10-29",
    botCycle: "6",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.7178",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-21",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8584",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-23",
    botCycle: "7",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6658",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-11-30",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.7487",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-01",
    botCycle: "8",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6993",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-14",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.6531",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-23",
    botCycle: "9",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.6685",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2020-12-27",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.8588",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-03",
    botCycle: "10",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.7897",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-03",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0031",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-04",
    botCycle: "11",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.1508",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-09",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0817",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-10",
    botCycle: "12",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.165",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-12",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.0951",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-13",
    botCycle: "13",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.296",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-24",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.2185",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-26",
    botCycle: "14",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.2743",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-01-31",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.6369",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-04",
    botCycle: "15",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1.6852",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-08",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.1434",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-12",
    botCycle: "16",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.0274",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-19",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1.9073",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-20",
    botCycle: "17",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.1985",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-24",
    botCycle: "18",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.0662",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-02-24",
    botCycle: "18",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.5046",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-08",
    botCycle: "19",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.3542",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-12",
    botCycle: "19",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.4198",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-19",
    botCycle: "20",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.0308",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-22",
    botCycle: "20",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.4643",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-03-27",
    botCycle: "21",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3.1305",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-04",
    botCycle: "21",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.1479",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-05",
    botCycle: "22",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.9589",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-06",
    botCycle: "22",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3.1252",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "23",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.9341",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "23",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2.5082",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "24",
  },
  {
    botId: undefined,
    botRef: "TOMOLO1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2.9301",
    sbl: "TOMOUSDT",
    base: "TOMO",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "24",
  },
];
