/* eslint-disable import/prefer-default-export */
export const wteth = [
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2086.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "1",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2089.56",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "1",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1974.82",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-07",
    botCycle: "2",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1998.42",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-08",
    botCycle: "2",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2070.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-08",
    botCycle: "3",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2051.85",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "3",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2076.96",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "4",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2072.32",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "4",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2078.92",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-09",
    botCycle: "5",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2066.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "5",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2074.6",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "6",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2146.34",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-10",
    botCycle: "6",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2151.07",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-11",
    botCycle: "7",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2139.8",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-11",
    botCycle: "7",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2153.78",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "8",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2152.02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-12",
    botCycle: "8",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2137.86",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-13",
    botCycle: "9",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2274.88",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "9",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2382.43",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "10",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2337.21",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-14",
    botCycle: "10",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2439.74",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "11",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2444.02",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "11",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2494.750",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-15",
    botCycle: "12",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2440.790",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "12",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2412.350",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-16",
    botCycle: "13",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2478.570",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "13",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2384.630",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-17",
    botCycle: "14",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2138.250",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "14",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2123.030",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-18",
    botCycle: "15",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2238.400",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-19",
    botCycle: "15",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2205.410",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-19",
    botCycle: "16",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2310.910",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-21",
    botCycle: "16",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2377.520",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-21",
    botCycle: "17",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2371.370",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "17",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2456.870",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "18",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2484.610",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "18",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2364.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-22",
    botCycle: "19",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2443.840",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-23",
    botCycle: "19",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2167.430",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-23",
    botCycle: "20",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2255.600",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-23",
    botCycle: "20",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2176.310",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-23",
    botCycle: "21",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2319.980",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-24",
    botCycle: "21",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2245.880",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-24",
    botCycle: "22",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2229.030",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-25",
    botCycle: "22",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2312.170",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-25",
    botCycle: "23",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2240.540",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "23",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2433.110",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "24",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2495.580",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-26",
    botCycle: "24",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2513.270",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-27",
    botCycle: "25",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2644.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "25",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2717.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-28",
    botCycle: "26",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2739.340",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "26",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2763.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "27",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2729.240",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-29",
    botCycle: "27",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2766.410",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "28",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2735.650",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-04-30",
    botCycle: "28",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2772.501",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-01",
    botCycle: "29",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2855.820",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-01",
    botCycle: "29",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2947.870",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-01",
    botCycle: "30",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2934.720",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-02",
    botCycle: "30",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2921.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-02",
    botCycle: "31",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3120.710",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-03",
    botCycle: "31",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3376.830",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "32",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3234.430",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "32",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3446.900",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "33",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3307.120",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-04",
    botCycle: "33",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3260.010",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-05",
    botCycle: "34",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3471.010",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "34",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3527.470",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-06",
    botCycle: "35",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3505.100",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "35",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3474.250",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-07",
    botCycle: "36",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3489.550",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "36",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3543.310",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-08",
    botCycle: "37",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3869.710",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "37",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3915.230",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-09",
    botCycle: "38",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4068.910",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "38",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3855.030",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "39",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3962.370",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-10",
    botCycle: "39",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3941.150",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-11",
    botCycle: "40",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4111.600",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "40",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "4257.960",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "41",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4305.490",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-12",
    botCycle: "41",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3810.150",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "42",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3881.490",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "42",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3906.580",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "43",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3749.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "43",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3845.400",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "44",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3668.840",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "44",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3752.420",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "45",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "4075.710",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "45",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3875.170",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "46",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3763.110",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "46",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3775.310",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "47",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3766.550",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "47",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3419.550",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "48",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3252.290",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "48",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3354.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "49",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3411.400",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "49",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3375.080",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "50",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3080.300",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "50",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2953.260",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "51",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3023.760",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "51",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2500.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "52",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2726.390",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "52",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2570.900",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "53",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2537.080",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "53",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2516.630",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "54",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2379.700",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "54",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2419.310",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "55",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2489.640",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "55",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2622.240",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "56",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2677.300",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "56",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2584.250",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "57",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2549.660",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "57",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2688.320",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "58",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2984.810",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "58",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2871.090",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "59",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2776.850",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "59",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2769.790",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "60",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2752.700",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "60",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2494.740",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "61",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2557.070",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "61",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2394.630",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "62",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2487.890",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "62",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2246.700",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "63",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2319.960",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "63",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2393.920",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "64",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2470.430",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "64",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2385.120",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "65",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2295.180",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "65",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2011.820",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "66",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2063.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "66",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1930.290",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "67",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1965.130",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "67",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1762.680",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "68",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1889.960",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "68",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2096.640",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "69",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2254.850",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "69",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2493.040",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "70",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2621.010",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "70",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2406.170",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "71",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2439.140",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "71",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2575.240",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "72",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2846.790",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "72",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2827.270",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "73",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2751.620",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "73",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2564.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "74",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2415.270",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "74",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2279.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "75",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2363.790",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "75",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2466.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "76",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2617.040",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "76",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2579.520",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "77",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2765.070",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "77",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2835.900",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "78",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2785.580",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "78",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2625.660",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "79",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2778.740",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "79",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2583.060",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "80",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2694.350",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "80",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2751.360",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "81",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2822.820",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "81",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2521.240",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "82",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2483.890",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "82",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2540.210",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "83",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2605.980",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "83",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2554.010",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "84",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2516.760",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "84",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2459.320",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "85",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2419.680",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "85",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2300.370",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "86",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2398.360",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "86",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2368.080",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "87",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2471.630",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "87",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2549.760",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "88",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2578.450",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "88",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2554.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "89",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2459.200",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "89",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2381.600",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "90",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2394.110",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "90",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2360.410",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "91",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2305.270",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "91",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2228.600",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "92",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2234.210",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "92",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2206.140",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "93",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2083.180",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "93",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2169.280",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "94",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2125.040",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "94",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2015.700",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "95",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2026.940",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "95",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1967.030",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "96",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1884.600",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "96",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1911.660",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "97",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2007.070",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "97",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1909.740",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "98",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1992.140",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "98",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1864.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "99",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1728.900",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "99",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1761.300",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "100",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1840.670",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "100",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1879.250",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "101",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1990.340",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "101",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2115.640",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "102",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2082.380",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "102",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2112.580",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "103",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2091.790",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "103",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2173.560",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "104",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2194.910",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "104",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2126.630",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "105",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2189.670",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "105",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2086.300",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "106",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2056.970",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "106",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2061.670",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "107",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2131.660",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-03",
    botCycle: "107",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2218.730",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-03",
    botCycle: "108",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2216.310",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-03",
    botCycle: "108",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2280.880",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "109",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2350.030",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "109",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2301.250",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "110",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2276.310",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-06",
    botCycle: "110",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2319.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "111",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2376.260",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "111",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2140.430",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-08",
    botCycle: "112",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2068.160",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "112",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2155.830",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "113",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2130.470",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "113",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2159.100",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-10",
    botCycle: "114",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2149.300",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-10",
    botCycle: "114",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2124.450",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-10",
    botCycle: "115",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2093.240",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-11",
    botCycle: "115",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2123.480",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-11",
    botCycle: "116",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2147.030",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "116",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2024.120",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "117",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1975.930",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "117",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1894.840",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "118",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1997.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "118",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1898.410",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-15",
    botCycle: "119",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1905.840",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "119",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1927.470",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "120",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1861.720",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-17",
    botCycle: "120",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1853.010",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-17",
    botCycle: "121",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1963.460",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-18",
    botCycle: "121",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1904.010",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "122",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1855.890",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "122",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1821.110",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "123",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1731.620",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "123",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1754.280",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "124",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1774.910",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-21",
    botCycle: "124",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "1863.930",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-21",
    botCycle: "125",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "1954.030",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-21",
    botCycle: "125",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2025.800",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-22",
    botCycle: "126",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2017.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-23",
    botCycle: "126",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2029.610",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-23",
    botCycle: "127",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2054.400",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-23",
    botCycle: "127",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2088.530",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-24",
    botCycle: "128",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2152.530",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-24",
    botCycle: "128",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2166.520",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "129",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2136.640",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "129",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2156.100",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "130",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2353.420",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "130",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2195.700",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "131",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2233.330",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "131",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2291.660",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-28",
    botCycle: "132",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2291.490",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-28",
    botCycle: "132",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2301.200",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-29",
    botCycle: "133",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2313.980",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-29",
    botCycle: "133",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2393.780",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "134",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2356.960",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "134",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2390.280",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "135",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2432.910",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-31",
    botCycle: "135",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2449.630",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-31",
    botCycle: "136",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2603.980",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-01",
    botCycle: "136",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2668.290",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-01",
    botCycle: "137",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2536.020",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "137",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2601.530",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "138",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2600.600",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "138",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2462.920",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "139",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2500.530",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "139",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2590.520",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "140",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2683.540",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-05",
    botCycle: "140",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2763.880",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-05",
    botCycle: "141",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2783.390",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-06",
    botCycle: "141",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2772.500",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-06",
    botCycle: "142",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "2914.840",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "142",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3063.360",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "143",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3044.720",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "143",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3139.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "144",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3113.660",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "144",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "2980.010",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "145",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3093.910",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "145",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3145.550",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-10",
    botCycle: "146",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3084.020",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-10",
    botCycle: "146",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3168.960",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-11",
    botCycle: "147",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3236.620",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-11",
    botCycle: "147",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3148.960",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "148",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3095.290",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "148",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3098.290",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "149",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3044.460",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "149",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3062.150",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "150",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3199.730",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "150",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3290.150",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-14",
    botCycle: "151",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3294.430",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-14",
    botCycle: "151",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3268.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-14",
    botCycle: "152",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3224.740",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "152",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3164.490",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "153",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3268.010",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-16",
    botCycle: "153",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3157.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "154",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3147.180",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "154",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3161.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "155",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3180.830",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-17",
    botCycle: "155",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3056.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "156",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3051.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "156",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3008.480",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-19",
    botCycle: "157",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3214.680",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-20",
    botCycle: "157",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3253.480",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-20",
    botCycle: "158",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3257.970",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "158",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3282.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "159",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3247.790",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "159",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3233.590",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-22",
    botCycle: "160",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3196.010",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-22",
    botCycle: "160",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3255.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-23",
    botCycle: "161",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3345.280",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-23",
    botCycle: "161",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3299.640",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-24",
    botCycle: "162",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3298.840",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-24",
    botCycle: "162",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3189.500",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "163",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3117.860",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "163",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3210.820",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "164",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3169.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-26",
    botCycle: "164",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3121.450",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-26",
    botCycle: "165",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3097.480",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-27",
    botCycle: "165",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3155.460",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-27",
    botCycle: "166",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3261.780",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-28",
    botCycle: "166",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3231.280",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-28",
    botCycle: "167",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3174.330",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-29",
    botCycle: "167",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3175.330",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-29",
    botCycle: "168",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3187.990",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "168",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3179.080",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "169",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3218.550",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-31",
    botCycle: "169",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3346.590",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-31",
    botCycle: "170",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3411.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-31",
    botCycle: "170",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3520.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-01",
    botCycle: "171",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3570.910",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-01",
    botCycle: "171",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3747.850",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-01",
    botCycle: "172",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3753.680",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-02",
    botCycle: "172",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3768.150",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-02",
    botCycle: "173",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3740.000",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-03",
    botCycle: "173",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3893.970",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-03",
    botCycle: "174",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3933.080",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-03",
    botCycle: "174",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3911.220",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-04",
    botCycle: "175",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3862.810",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-04",
    botCycle: "175",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3904.670",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-05",
    botCycle: "176",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3923.400",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-05",
    botCycle: "176",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3957.390",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-06",
    botCycle: "177",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3893.630",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-06",
    botCycle: "177",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "3937.150",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-06",
    botCycle: "178",
  },
  {
    botRef: "WTETH",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "3896.160",
    sbl: "ETHUSDT",
    base: "ETH",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "178",
  },
];
