/* eslint-disable import/prefer-default-export */
export const wtshib = [
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001671",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "1",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001869",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "1",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001819",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "2",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001889",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-13",
    botCycle: "2",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002029",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "3",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002115",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "3",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002078",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "4",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002050",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "4",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001921",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "5",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001926",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-14",
    botCycle: "5",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001786",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "6",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001840",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "6",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001701",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "7",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001771",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "7",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001770",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-15",
    botCycle: "8",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001547",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "8",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001597",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "9",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001440",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "9",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001347",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-16",
    botCycle: "10",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001404",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "10",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001566",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "11",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001679",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "11",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001627",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "12",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001575",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-17",
    botCycle: "12",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001635",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "13",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001574",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-18",
    botCycle: "13",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001445",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "14",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001263",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "14",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001058",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "15",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001062",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "15",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000968",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-19",
    botCycle: "16",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001033",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "16",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000957",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "17",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000915",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "17",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000819",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "18",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000932",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "18",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001002",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "19",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001017",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "19",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001088",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "20",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001000",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-20",
    botCycle: "20",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000818",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "21",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000768",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-21",
    botCycle: "21",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000775",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "22",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000748",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "22",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000723",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "23",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000774",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "23",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000716",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "24",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000768",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "24",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000745",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "25",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000782",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-22",
    botCycle: "25",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000842",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "26",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000925",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "26",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000901",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "27",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000842",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "27",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000807",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "28",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000788",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "28",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000748",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "29",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000762",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-23",
    botCycle: "29",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000817",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "30",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000863",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "30",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000847",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "31",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000910",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "31",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000875",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "32",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000945",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "32",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001045",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-24",
    botCycle: "33",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000961",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "33",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000953",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-25",
    botCycle: "34",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001008",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "34",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000988",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "35",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000949",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-26",
    botCycle: "35",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000910",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-27",
    botCycle: "36",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000873",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "36",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000809",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "37",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000817",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "37",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000751",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "38",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000783",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "38",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000784",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-28",
    botCycle: "39",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000787",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-29",
    botCycle: "39",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000767",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "40",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000774",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-30",
    botCycle: "40",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000792",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "41",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000873",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "41",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000870",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "42",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000938",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-05-31",
    botCycle: "42",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000928",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "43",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000876",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-01",
    botCycle: "43",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000883",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "44",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001007",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "44",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000957",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "45",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000940",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-02",
    botCycle: "45",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000988",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "46",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000972",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-03",
    botCycle: "46",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000917",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "47",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000916",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "47",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000877",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-04",
    botCycle: "48",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000864",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-05",
    botCycle: "48",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000854",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "49",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000845",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-06",
    botCycle: "49",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000864",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "50",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000857",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "50",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000769",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-07",
    botCycle: "51",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000781",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "51",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000715",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "52",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000729",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "52",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000736",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-08",
    botCycle: "53",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000716",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "53",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000731",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-09",
    botCycle: "54",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000727",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "54",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000692",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "55",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000686",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "55",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000692",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "56",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000683",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "56",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000689",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-10",
    botCycle: "57",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000667",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "57",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000680",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-11",
    botCycle: "58",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000641",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "58",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000572",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "59",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000575",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "59",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000594",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "60",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000643",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-12",
    botCycle: "60",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000634",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "61",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000618",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "61",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000664",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "62",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000708",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-13",
    botCycle: "62",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000683",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "63",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000678",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-14",
    botCycle: "63",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000706",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "64",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000709",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "64",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000728",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "65",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000794",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "65",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000861",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "66",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000915",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-15",
    botCycle: "66",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000909",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "67",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000890",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "67",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000846",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "68",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000885",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-16",
    botCycle: "68",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000848",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "69",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000806",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "69",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000787",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-17",
    botCycle: "70",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000754",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-18",
    botCycle: "70",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000717",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "71",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000818",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "71",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000809",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "72",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000764",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-19",
    botCycle: "72",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000761",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-20",
    botCycle: "73",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000739",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "73",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000692",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "74",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000696",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-21",
    botCycle: "74",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000609",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "75",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000633",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "75",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000594",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "76",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000622",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "76",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000658",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "77",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000580",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "77",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000632",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-22",
    botCycle: "78",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000675",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "78",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000669",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "79",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000686",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-23",
    botCycle: "79",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000674",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-24",
    botCycle: "80",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000702",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-25",
    botCycle: "80",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000715",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "81",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000721",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "81",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000718",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "82",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000707",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "82",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000729",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-26",
    botCycle: "83",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000730",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-27",
    botCycle: "83",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000766",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "84",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000800",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-28",
    botCycle: "84",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000832",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "85",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000942",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "85",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000921",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "86",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000924",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-29",
    botCycle: "86",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000868",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-06-30",
    botCycle: "87",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000839",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "87",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000837",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-01",
    botCycle: "88",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000827",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "88",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000831",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-02",
    botCycle: "89",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000868",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-03",
    botCycle: "89",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000878",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-04",
    botCycle: "90",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000874",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "90",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000834",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-05",
    botCycle: "91",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000863",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-06",
    botCycle: "91",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000874",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "92",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000867",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-07",
    botCycle: "92",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000802",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-08",
    botCycle: "93",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000792",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "93",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000805",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-09",
    botCycle: "94",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000797",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-10",
    botCycle: "94",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000770",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-11",
    botCycle: "95",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000785",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-12",
    botCycle: "95",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000754",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "96",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000722",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-13",
    botCycle: "96",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000719",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "97",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000747",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "97",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000732",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-14",
    botCycle: "98",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000722",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-15",
    botCycle: "98",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000687",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-15",
    botCycle: "99",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000668",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-16",
    botCycle: "99",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000677",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-17",
    botCycle: "100",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000685",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-18",
    botCycle: "100",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000665",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "101",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000632",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-19",
    botCycle: "101",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000621",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "102",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000587",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "102",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000592",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-20",
    botCycle: "103",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000649",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-21",
    botCycle: "103",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000648",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-22",
    botCycle: "104",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000645",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-23",
    botCycle: "104",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000641",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-24",
    botCycle: "105",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000655",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-24",
    botCycle: "105",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000635",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "106",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000625",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "106",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000629",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "107",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000624",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-25",
    botCycle: "107",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000628",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "108",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000667",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-26",
    botCycle: "108",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000630",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-27",
    botCycle: "109",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000625",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-28",
    botCycle: "109",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000615",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-29",
    botCycle: "110",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000631",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-30",
    botCycle: "110",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000625",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-31",
    botCycle: "111",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000624",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-07-31",
    botCycle: "111",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000639",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-01",
    botCycle: "112",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000641",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-01",
    botCycle: "112",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000625",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-02",
    botCycle: "113",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000624",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-03",
    botCycle: "113",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000621",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-04",
    botCycle: "114",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000622",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-05",
    botCycle: "114",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000618",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-05",
    botCycle: "115",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000615",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-06",
    botCycle: "115",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000627",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-06",
    botCycle: "116",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000726",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "116",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000703",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "117",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000697",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-07",
    botCycle: "117",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000794",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "118",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000811",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "118",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000758",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "119",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000741",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-08",
    botCycle: "119",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000722",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-09",
    botCycle: "120",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000765",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-10",
    botCycle: "120",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000772",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-10",
    botCycle: "121",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000790",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-12",
    botCycle: "121",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000768",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-13",
    botCycle: "122",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000811",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-14",
    botCycle: "122",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000830",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "123",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000799",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "123",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000824",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-15",
    botCycle: "124",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000871",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-16",
    botCycle: "124",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000809",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-18",
    botCycle: "125",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000803",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-19",
    botCycle: "125",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000809",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-19",
    botCycle: "126",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000823",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-20",
    botCycle: "126",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000843",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "127",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000840",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-21",
    botCycle: "127",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000814",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-22",
    botCycle: "128",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000807",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-22",
    botCycle: "128",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000833",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-23",
    botCycle: "129",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000818",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-23",
    botCycle: "129",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000820",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-24",
    botCycle: "130",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000768",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-24",
    botCycle: "130",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000767",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-25",
    botCycle: "131",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000733",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-26",
    botCycle: "131",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000706",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-27",
    botCycle: "132",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000736",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-28",
    botCycle: "132",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000722",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-28",
    botCycle: "133",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000705",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-29",
    botCycle: "133",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000715",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-29",
    botCycle: "134",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000701",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "134",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000703",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-30",
    botCycle: "135",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000670",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-31",
    botCycle: "135",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000685",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-08-31",
    botCycle: "136",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000674",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-01",
    botCycle: "136",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000694",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-01",
    botCycle: "137",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000719",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-02",
    botCycle: "137",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000703",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-03",
    botCycle: "138",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000702",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-04",
    botCycle: "138",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000714",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-04",
    botCycle: "139",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000738",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-05",
    botCycle: "139",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000747",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-05",
    botCycle: "140",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000736",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-06",
    botCycle: "140",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000715",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "141",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000679",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "141",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000565",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "142",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000616",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "142",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000600",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "143",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000617",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-07",
    botCycle: "143",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000591",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "144",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000647",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "144",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000690",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-08",
    botCycle: "145",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000699",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-09",
    botCycle: "145",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000757",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-09",
    botCycle: "146",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000703",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-10",
    botCycle: "146",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000694",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-10",
    botCycle: "147",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000686",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-11",
    botCycle: "147",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000690",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-11",
    botCycle: "148",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000675",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-12",
    botCycle: "148",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000690",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-12",
    botCycle: "149",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000668",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-12",
    botCycle: "149",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000644",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-13",
    botCycle: "150",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000663",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-14",
    botCycle: "150",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000686",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-15",
    botCycle: "151",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000675",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-16",
    botCycle: "151",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000860",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-17",
    botCycle: "152",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000915",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-17",
    botCycle: "152",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000902",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-17",
    botCycle: "153",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000887",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-17",
    botCycle: "153",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000859",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-17",
    botCycle: "154",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000867",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-17",
    botCycle: "154",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000829",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-18",
    botCycle: "155",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000794",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-18",
    botCycle: "155",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000771",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "156",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000805",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "156",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000815",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-19",
    botCycle: "157",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000769",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-20",
    botCycle: "157",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000707",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-20",
    botCycle: "158",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000694",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-21",
    botCycle: "158",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000710",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-22",
    botCycle: "159",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000713",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-23",
    botCycle: "159",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000765",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-23",
    botCycle: "160",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000759",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "160",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000696",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "161",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000708",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "161",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000732",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-24",
    botCycle: "162",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000733",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-25",
    botCycle: "162",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000717",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-26",
    botCycle: "163",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000715",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-27",
    botCycle: "163",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000707",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-28",
    botCycle: "164",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000708",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-29",
    botCycle: "164",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000713",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-09-30",
    botCycle: "165",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000717",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-01",
    botCycle: "165",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000751",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-01",
    botCycle: "166",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000755",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-02",
    botCycle: "166",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000771",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-02",
    botCycle: "167",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000797",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-03",
    botCycle: "167",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000871",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-03",
    botCycle: "168",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00000844",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-04",
    botCycle: "168",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00000986",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-04",
    botCycle: "169",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001048",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-04",
    botCycle: "169",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001394",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-05",
    botCycle: "170",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001302",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-05",
    botCycle: "170",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00001727",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-05",
    botCycle: "171",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00001833",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-06",
    botCycle: "171",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002235",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-06",
    botCycle: "172",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002375",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-06",
    botCycle: "172",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002295",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-06",
    botCycle: "173",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002313",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-06",
    botCycle: "173",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002817",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-07",
    botCycle: "174",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002939",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-07",
    botCycle: "174",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00003089",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-07",
    botCycle: "175",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002319",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-08",
    botCycle: "175",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002156",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-08",
    botCycle: "176",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002232",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-08",
    botCycle: "176",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002137",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-08",
    botCycle: "177",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002204",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-08",
    botCycle: "177",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002665",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-08",
    botCycle: "178",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002826",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-09",
    botCycle: "178",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002628",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-09",
    botCycle: "179",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002635",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-09",
    botCycle: "179",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002620",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-10",
    botCycle: "180",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002592",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-10",
    botCycle: "180",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002740",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "181",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002962",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "181",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002823",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "182",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00003119",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "182",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00003056",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-11",
    botCycle: "183",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00003012",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-12",
    botCycle: "183",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002932",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-12",
    botCycle: "184",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002846",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-12",
    botCycle: "184",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002908",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-13",
    botCycle: "185",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002896",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-13",
    botCycle: "185",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002921",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-14",
    botCycle: "186",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002869",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-14",
    botCycle: "186",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002762",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-14",
    botCycle: "187",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002741",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-14",
    botCycle: "187",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002522",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-15",
    botCycle: "188",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002684",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-15",
    botCycle: "188",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002569",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-15",
    botCycle: "189",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002582",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-16",
    botCycle: "189",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002553",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "190",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002461",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-17",
    botCycle: "190",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "open",
    estimatedPrice: "0.00002692",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-18",
    botCycle: "191",
  },
  {
    botRef: "WTSHIB",
    botVer: "1",
    stratType: "LONG",
    position: "close",
    estimatedPrice: "0.00002762",
    sbl: "SHIBUSDT",
    base: "SHIB",
    quote: "USDT",
    exch: "binance",
    signalDateTime: "2021-10-18",
    botCycle: "191",
  },
];
