<template>
  <GeneralLayout title="UBXT Token">
    <div
      class="ubxt-info flex flex-col relative h-full w-full bg-mirage pt-20 pb-50 px-40 md:px-20 rounded-3 overflow-y-auto custom-scrollbar"
    >
      <div class="flex flex-col flex-shrink-0 mb-40 md:mb-50">
        <h2 class="text-white leading-md font-black mb-10">WHAT IS THE UBXT TOKEN ?</h2>
        <p class="text-grey-cl-920 text-md leading-md font-bold">
          The UBXT token is a utility token that is based on the ERC20 protocol of the Ethereum blockchain. We created a token to allow a
          transparent, secure and optimized use of our application.
        </p>
      </div>

      <div class="flex flex-col flex-shrink-0 mb-40 md:mb-50">
        <h2 class="text-white leading-md font-black mb-10">HOW CAN I USE MY UBXT ?</h2>
        <div class="flex flex-col">
          <div class="text-grey-cl-920 text-md leading-md font-bold">
            UpBots tokens will have a central role in the platform. UBXT will be mainly used for
            <strong class="text-white">payment of subscriptions</strong>, training courses, and for the payment of the
            <strong class="text-white">profit success fees</strong> generated by an external bot or social copy trading.
          </div>
        </div>
      </div>

      <div class="flex flex-col flex-shrink-0 mb-40 md:mb-50">
        <h2 class="text-white leading-md font-black mb-10">WHAT IS THE BURNING PROGRAM ?</h2>
        <p class="text-grey-cl-920 text-md leading-md font-bold">
          The burning program is an automatic process that will ‘burn’ tokens according to the turnover, in order to reduce the number of
          tokens in circulation.
        </p>
      </div>

      <div class="flex flex-col xl:flex-row flex-shrink-0">
        <div class="ubxt-info__card-left xl:pr-20 xl:pt-20 xl:pb-20">
          <p class="text-xl1 text-turquoise-blue leading-md font-black mb-10 md:mb-40">Performance Fee Burn</p>
          <p class="ubxt-info__card-left-desc w-full text-iceberg text-md font-bold mb-30 xl:mb-40">
            15% of the tokens collected by UpBots for bots and copy trading performance fees will be burned. This program will be active
            until 250,000,000 UBXTs have been burned, i.e. 50% of the total liquidity.
          </p>
          <div class="flex items-center justify-center xl:justify-start mb-30 md:mb-100 xl:mb-0">
            <div class="ubxt-info__logo-img-wrap flex mr-35 md:mr-50">
              <img src="@/assets/images/ubxt-info/ubxt-info-logo.png" alt="ubxt-info-logo" class="w-full h-full" />
            </div>
            <div class="ubxt-info__logo-desc flex w-full text-xxl2 text-iceberg leading-md font-black">Burn of 50% of the tokens</div>
          </div>
        </div>
        <div class="w-full xl:w-auto xl:h-full border border-dashed border-grey-cl-100" />
        <div class="ubxt-info__card-right xl:pl-100 xl:pt-20 xl:pb-30 mt-30 md:mt-40 xl:mt-0">
          <p class="text-xl1 text-turquoise-blue font-black mb-10 md:mb-40">Annual Income Burn</p>
          <p class="ubxt-info__card-right-desc w-full text-iceberg text-md font-bold">
            Every first quarter of the year, a certain% of the net income will be used to burn tokens.
          </p>
          <div class="flex justify-center xl:justify-start items-end">
            <CircleInfo
              title="15%"
              desc="Q4 2021"
              :circle-size="$breakpoint.smAndDown ? '88' : '160'"
              :title-size="$breakpoint.smAndDown ? '27' : '50'"
            />
            <CircleInfo
              title="10%"
              desc="Q4 2022"
              :circle-size="$breakpoint.smAndDown ? '66' : '120'"
              :title-size="$breakpoint.smAndDown ? '21' : '40'"
            />
            <CircleInfo
              title="5%"
              desc="Q4 2023"
              :circle-size="$breakpoint.smAndDown ? '46' : '84'"
              :title-size="$breakpoint.smAndDown ? '16' : '30'"
            />
            <CircleInfo
              title="2%"
              desc="Q4 2024"
              :circle-size="$breakpoint.smAndDown ? '28' : '50'"
              :title-size="$breakpoint.smAndDown ? '11' : '20'"
            />
          </div>
        </div>
      </div>
    </div>
  </GeneralLayout>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

import GeneralLayout from "@/views/GeneralLayout.vue";
import CircleInfo from "@/components/ubxt-info/CircleInfo.vue";

@Component({ name: "UBXTInfo", components: { GeneralLayout, CircleInfo } })
export default class UBXTInfo extends Vue {
  /* DATA */
  subscriptionData: any = [
    {
      price: "$250 in UBXT*",
      list: [
        "10 % discount on performance fees",
        "10 % discount on UpBots subscription",
        "Participation in the UBXT Profit Pool**",
        "VIP zone access level 1***",
      ],
      active: false,
    },
    {
      price: "$1,000 in UBXT*",
      list: [
        "20 % discount on performance fees",
        "30 % discount on UpBots subscription",
        "Participation in the UBXT Profit Pool**",
        "VIP zone access level 2***",
      ],
      active: false,
    },
    {
      price: "$5,000 in UBXT*",
      list: [
        "35 % discount on performance fees",
        "50 % discount on UpBots subscription",
        "Participation in the UBXT Profit Pool**",
        "VIP zone access level 3***",
      ],
      active: false,
    },
    {
      price: "$15,000 in UBXT*",
      list: [
        "50 % discount on performance fees",
        "100 % discount on UpBots subscription",
        "Participation in the UBXT Profit Pool**",
        "VIP zone access level 4***",
      ],
      active: false,
    },
  ];
}
</script>

<style lang="scss" scoped>
.ubxt-info {
  h2 {
    @apply text-xxl1;
  }

  @media (max-width: 767px) {
    h2 {
      @apply text-xl1;
    }
  }
}

.ubxt-info {
  &__logo-img-wrap {
    max-width: 120px;
  }
  &__logo-desc {
    max-width: 243px;
  }
  &__card-left-desc {
    max-width: 433px;
  }
  &__card-right-desc {
    max-width: 600px;
    margin-bottom: 130px;
  }
  &__card-left {
    width: 44.9%;
  }
  &__card-right {
    width: 54.9%;
  }
  @media (max-width: 1279px) {
    &__card-left {
      @apply w-full;
    }
    &__card-right {
      @apply w-full;
    }
    &__card-left-desc {
      @apply max-w-full;
    }
    &__card-right-desc {
      @apply max-w-full mb-56;
    }
    &__logo-desc {
      max-width: 155px;
    }
  }
  @media (max-width: 767px) {
    &__logo-img-wrap {
      max-width: 75px;
    }
    &__card-right-desc {
      margin-bottom: 25px;
    }
    &__logo-desc {
      font-size: 30px;
    }
  }
}
</style>
